### PR TITLE
Made general improvements to FavoritesManager and fixed #380

### LINKED ISSUE #380: Infinite alumni connect
When you remove a favorite, if you're fast enough you can hit the undo button more than once and get multiples of one feature in your favorites
device-2017-04-05-153710

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/381)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 311 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2ZdRF--UpbwVjAUQV:-Kh2ZdRF--UpbwVjAUQW:b-93p77k) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L311)):*
> ```Java
> 				updateHintMessageVisibility();
> 				// The snackbar should be dismissed immediately but if a user is quick enough they can hit the button twice
> 				snackbar.setAction("Undo", null);
> ```

Can't you just set the snackbar to disabled? I think that would be better than actually changing the binding function... If not, this is fine

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2_8n1sZraE1GT-7D6:-Kh2_8n1sZraE1GT-7D7:b73iz99) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L54)):*
> ```Java
> 	public int removeFavorite(Feature feature) {
> 		int count = 0;
> 		for (Iterator<String> iterator = favoriteFeatureIdList.iterator(); iterator.hasNext(); count++) {
> ```

Definitely a comment here about why you did it this way. Also, this sort of breaks our Builder pattern that we had been implementing... Any thoughts about what we should do about that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 311 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2ZdRF--UpbwVjAUQV:-Kh2tb40ORr9-rFuDE8r:bjom9wo) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L311)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can't you just set the snackbar to disabled? I think that would be better than actually changing the binding function... If not, this is fine
</blockquote></details>

No, you can't. There is another slightly more complicated way that I could do it in the FavoritesManager, which could be considered better

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2_8n1sZraE1GT-7D6:-Kh2u-GO6TgeTLXQtSI3:b-u3ut25) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L54)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Definitely a comment here about why you did it this way. Also, this sort of breaks our Builder pattern that we had been implementing... Any thoughts about what we should do about that?
</blockquote></details>

This function is used in one place, and didn't use the builder pattern. We could alternatively add a putBackLastRemovedFeature function, and that would actually fix the snackbar problem too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 311 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2ZdRF--UpbwVjAUQV:-Kh2wPAr2EbbgHv4-c8-:b-u4pglc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L311)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

No, you can't. There is another slightly more complicated way that I could do it in the FavoritesManager, which could be considered better
</blockquote></details>

What about `v.setEnabled(false)`?

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2_8n1sZraE1GT-7D6:-Kh2wVrKCRJdfp1wUoH2:b-pgnt2x) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L54)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

This function is used in one place, and didn't use the builder pattern. We could alternatively add a putBackLastRemovedFeature function, and that would actually fix the snackbar problem too
</blockquote></details>

Hmmm... Let's do that. We could call it `undoRemoveFavorite`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 311 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2ZdRF--UpbwVjAUQV:-Kh2widYMEfa6XQVTeR8:bq6lfmn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L311)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What about `v.setEnabled(false)`?
</blockquote></details>

Oh I guess we could do that... but undoRemoveFavorite already takes care of it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 311 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2ZdRF--UpbwVjAUQV:-Kh2wyJ-Ot7hKZQPwPni:b-ww8jxx) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L311)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Oh I guess we could do that... but undoRemoveFavorite already takes care of it
</blockquote></details>

Show me what you think the best solution is. I think v.setEnabled(false) is definitely important to do either way, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by coreywoodfield** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 311 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2ZdRF--UpbwVjAUQV:-Kh2yGAFhOTf3PbYrNAJ:bmvv1px) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L311)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Show me what you think the best solution is. I think v.setEnabled(false) is definitely important to do either way, right?
</blockquote></details>

yeah i guess it is, because the favorites manager will work fine and not add it twice, but the adapter still adds it twice...

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2_8n1sZraE1GT-7D6:-Kh2yat18xuy-20b2r_B:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L54)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Hmmm... Let's do that. We could call it `undoRemoveFavorite`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh2_8n1sZraE1GT-7D6:-Kh33kD8CmvU_PMcuw7s:biumxzn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b175dd4d3c2f995e90dc56430e2e43406b1b0e82/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L54)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think this is what I meant... I'll talk to you about this one when I get in.

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 29 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh33c8QuBC4PaRYRmEf:-Kh33c8QuBC4PaRYRmEg:b-gli1wf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9511c651ee05767e5dee8a766b5bc2ac9f104157/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L29)):*
> ```Java
> 	private List<String> favoriteFeatureIdList;
> 	private SharedPreferences preferences;
> 	private int indexOfRemoved;
> ```

Why do we need to save this here? Can't we just pass it in when we need it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 29 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh33c8QuBC4PaRYRmEf:-Kh351BgNuKc9w8SwPsK:b3r66hx) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9511c651ee05767e5dee8a766b5bc2ac9f104157/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why do we need to save this here? Can't we just pass it in when we need it?
</blockquote></details>

We save it so we don't need to pass it in, so that undoRemoveFavorite is self contained

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 29 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh33c8QuBC4PaRYRmEf:-Kh35H4W0RgRuXGw-ZRV:belhv7u) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9511c651ee05767e5dee8a766b5bc2ac9f104157/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L29)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

We save it so we don't need to pass it in, so that undoRemoveFavorite is self contained
</blockquote></details>

Due to the small period of time that the index is needed, I would feel better about passing it in rather than having to save it in the Favorites (which only needs it in one case). I have an idea for this. I'll talk to you about it in a few minutes when I get back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by coreywoodfield** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FavoritesManager.java, line 29 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-Kh33c8QuBC4PaRYRmEf:-Kh3GwBLeqtaJGMLHPAw:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9511c651ee05767e5dee8a766b5bc2ac9f104157/support/src/main/java/edu/byu/support/feature/FavoritesManager.java#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Due to the small period of time that the index is needed, I would feel better about passing it in rather than having to save it in the Favorites (which only needs it in one case). I have an idea for this. I'll talk to you about it in a few minutes when I get back
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/381#-:-Kh3IDxGnq33V75AsnoO:bnfp4nl)*

**Pull request merged**
