### PR TITLE
Fix/morebugs

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/180)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180#-KcYsTncL1Bbct-fqa2m:-KcYsTncL1Bbct-fqa2n:b2p7elb) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/11555d8085dc49f0a7ddef987cead9b1d1ef67a2/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L29)):*
> ```Java
> 	}
> 
> 	protected static Bundle getArgsBundleWithTitle(String title, int capacity) {
> ```

Why is capacity needed? For simplicity's sake, I would probably go without the capacity (we will only waste 9 spaces of memory in the worst case. And we will never have to double the capacity since we never pass in more than 10

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180#-KcYsTncL1Bbct-fqa2m:-KcYtAjaz9KgPWThBGQP:bruf62j) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/11555d8085dc49f0a7ddef987cead9b1d1ef67a2/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why is capacity needed? For simplicity's sake, I would probably go without the capacity (we will only waste 9 spaces of memory in the worst case. And we will never have to double the capacity since we never pass in more than 10
</blockquote></details>

 Default capacity for bundles is 0. I can take it out, I just figured it would be convenient for the times when we did know that capacity beforehand

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180#-KcYsTncL1Bbct-fqa2m:-KcYtNl8TYruHyBZmRQ7:b-m94ymo) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/11555d8085dc49f0a7ddef987cead9b1d1ef67a2/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L29)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

 Default capacity for bundles is 0. I can take it out, I just figured it would be convenient for the times when we did know that capacity beforehand
</blockquote></details>

Ah. Umm... Yeah. Still take it out for simplicity's sake

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180#-KcYsTncL1Bbct-fqa2m:-KcYtuWxi6CtjwVgeDPN:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/11555d8085dc49f0a7ddef987cead9b1d1ef67a2/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Ah. Umm... Yeah. Still take it out for simplicity's sake
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/180#-:-KcYuF4uc_FUtjqjSo4A:bnfp4nl)*

**Pull request merged**
