### PR TITLE
Changed text size and padding in default_list_item

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/124)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/res/layout/default_list_item.xml, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/124#-Ka8KQ_vcQe-DeeEqzGN:-Ka8KQ_vcQe-DeeEqzGO:b-bwo3mm) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3b4f2c7ac42ce1189a373035bf700cd2625870cc/support/src/main/res/layout/default_list_item.xml#L6)):*
> ```XML
>     android:layout_height="wrap_content"
>     android:background="@drawable/custom_ripple"
>     android:padding="8dp"
> ```

Did you feel that we needed more padding? Could you slack me some screenshots of each?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/124)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/res/layout/default_list_item.xml, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/124#-Ka8KQ_vcQe-DeeEqzGN:-KaECVc1ZvARRTkzMOZq:biki8cp) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3b4f2c7ac42ce1189a373035bf700cd2625870cc/support/src/main/res/layout/default_list_item.xml#L6)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Did you feel that we needed more padding? Could you slack me some screenshots of each?
</blockquote></details>

When Seth changed the text size, he changed the padding too. All the other default list items have 8dp of padding. I was just reverting that to make this one uniform with the rest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/124)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/124)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/124#-:-KaEH9iUSwu0p1gg_Re3:bnfp4nl)*

**Pull request merged**
