### PR TITLE
Fixes #293

### LINKED ISSUE #293: Add Features: Search
Problem:
If any text is entered into the search bar, the entire list of features disappears.

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/303)

### CODE REVIEW

**Comment by coreywoodfield** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/adapter/ByuSearchableRecyclerAdapter.java, line 49 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303#-Ke_hzwGL60M-58f1dHE:-Ke_hzwHlehSin1BtbnP:bvn8hja) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/31ce85976b5ef9750af61b81502f1ee6a8ac286d/support/src/main/java/edu/byu/support/adapter/ByuSearchableRecyclerAdapter.java#L49)):*
> ```Java
> 	public ByuSearchableRecyclerAdapter(List<DataType> list) {
> 		super(list);
> 		unfilteredList = new ArrayList<>(list);
> ```

you need to check if the list is null before you initialize an ArrayList with it (`unfiltered list = list == null ? new ArrayList<>() : new ArrayList<>(list);`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303)*

**Comment by coreywoodfield** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303)*

**Comment by romrell4** [comment]
Reviewed 1 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303)*

**Comment by romrell4** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303)*

**Comment by romrell4** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303)*

**Comment by romrell4** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303#-:-Ke_sN72qm4zopjEPKy9:b-yncq6h)*

**Comment by coreywoodfield** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/303#-:-Ke_sPHr6BB4gA-PJ6Tm:bg7igk9)*

**Pull request merged**
