### PR TITLE
Feature/mpn

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/84)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[app/build.gradle, line 9 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2CcdmRLUyGz_3uqSe:-KV2CcdnOt9ZaR1-B3DZ:b-88j4ub) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/build.gradle#L9)):*
> ```Gradle
>     defaultConfig {
>         // todo: change this to edu.byu.suite before release
>         applicationId "edu.byu.suite"
> ```

Change this back for now

---

*[app/src/main/AndroidManifest.xml, line 36 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2CvDIbf3fKizzeFfG:-KV2CvDIbf3fKizzeFfH:b-kuz2w1) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/AndroidManifest.xml#L36)):*
> ```XML
> 		</service>
> 
> 		<service
> ```

Comment about what these two do

---

*[app/src/main/java/edu/byu/suite/notifications/ByuFcmNotificationService.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2DjZeaqopzPd14rqV:-KV2DjZeaqopzPd14rqW:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/java/edu/byu/suite/notifications/ByuFcmNotificationService.java#L18)):*
> ```Java
> 		super.onMessageReceived(remoteMessage);
> 
> 		Intent intent = new Intent(this, ViewNotificationActivity.class).setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
> ```

Comment

---

*[app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2E1XGyQD-2DS0EfhI:-KV2E1XGyQD-2DS0EfhJ:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java#L20)):*
> ```Java
> 	@Override
> 	protected void onCreate(Bundle savedInstanceState) {
> 		super.onCreate(savedInstanceState);
> ```

Comment

---

*[app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2E4cGwo7HSFrj4x2L:-KV2E4cGwo7HSFrj4x2M:b-mgxp8i) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java#L26)):*
> ```Java
> 									 .setMessage(intent.getStringExtra(MESSAGE))
> 									 .setCancelable(false)
> 									 .setNegativeButton("OK", (dialogInterface, i) -> finish())
> ```

positive

---

*[app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2EIdPSiYrqLKTKrdE:-KV2EIdPSiYrqLKTKrdF:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java#L29)):*
> ```Java
> 									 .show();
> 
> 		if (intent.getBooleanExtra(SHOULD_VIBRATE, false)) {
> ```

Comment

---

*[app/src/main/res/drawable/ic_warning_black_24dp.png, line 0 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2EMeWl7GLtGHB6PLR:-KV2EMeWl7GLtGHB6PLS:b22quet) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/res/drawable/ic_warning_black_24dp.png#L0)):*
Remove this

---

*[app/src/main/res/values/strings.xml, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2EYMs7rxa3XxZWJPK:-KV2EYMs7rxa3XxZWJPL:b-5e5v89) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/res/values/strings.xml#L6)):*
> ```XML
>     <string name="action_settings">Settings</string>
>     <string name="action_search">Search</string>
> 	<string name="ok">OK</string>
> ```

Remove if you'd like

---

*[support/src/main/java/edu/byu/support/login/mpn/Device.java, line 22 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2F8v8flYio2heecNA:-KV2F8v8flYio2heecNB:bas5vmi) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/support/src/main/java/edu/byu/support/login/mpn/Device.java#L22)):*
> ```Java
> 	}
> 
> 	public Long getId() {
> ```

Remove unused getters/setters

---

*[support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2FiCOMHN18Uo7hag8:-KV2FiCOMHN18Uo7hag9:b-a487ft) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java#L24)):*
> ```Java
> public class RegisterWithMpnService extends Service {
> 	private static final String TAG = RegisterWithMpnService.class.getSimpleName();
> 	public static final int LOGOUT = 0;
> ```

Make action an enum

---

*[support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java, line 68 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2GI66s95KjJDV19ps:-KV2Fw8l8te9-9WOEkd6:b-bbmw6m) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java#L68)):*
> ```Java
> 				});
> 			} else {
> 				AccountResolver.remove(this, AccountResolver.getAccount(this));
> ```

add stopSelf

---

*[support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java, line 85 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2H0nQiYfOhxMctEW2:-KV2H0nQiYfOhxMctEW3:b-3687i7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java#L85)):*
> ```Java
> 			final String deviceIdPrefKey = getString(R.string.device_id_pref_key);
> 			final SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(this);
> 			if (token == null) {
> ```

Tons of comments in this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by coreywoodfield** [comment]
Review status: 14 of 47 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[app/src/main/AndroidManifest.xml, line 36 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2CvDIbf3fKizzeFfG:-KVBjDaY_AdafoKyFYaL:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/AndroidManifest.xml#L36)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment about what these two do
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/notifications/ByuFcmNotificationService.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2DjZeaqopzPd14rqV:-KVBkAolOmlWTXsO861Z:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/java/edu/byu/suite/notifications/ByuFcmNotificationService.java#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2E1XGyQD-2DS0EfhI:-KVBqV-8PuIMh9JoxONG:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2E4cGwo7HSFrj4x2L:-KVBqKUg7YxePZg_JZ19:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> positive
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2EIdPSiYrqLKTKrdE:-KVBqVbFisypTj_IiM1W:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/java/edu/byu/suite/notifications/ViewNotificationActivity.java#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment
</details>
Done.

---

*[support/src/main/java/edu/byu/support/login/mpn/Device.java, line 22 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2F8v8flYio2heecNA:-KVBqkgte3WTqAKvp7JF:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/support/src/main/java/edu/byu/support/login/mpn/Device.java#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove unused getters/setters
</details>
Done.

---

*[support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2FiCOMHN18Uo7hag8:-KVBtUxyV7YqtDpBJZQe:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Make action an enum
</details>
Done.

---

*[support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java, line 68 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2GI66s95KjJDV19ps:-KVBtVeBU3zeiuFc5RhK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> add stopSelf
</details>
Done.

---

*[app/src/main/res/drawable/ic_warning_black_24dp.png, line  at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2EMeWl7GLtGHB6PLR:-KVBqa9JuRLgLeacV-2N:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/res/drawable/ic_warning_black_24dp.png#L)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove this
</details>
Done.

---

*[app/src/main/res/values/strings.xml, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2EYMs7rxa3XxZWJPK:-KVBqg5etHFuD3UlQkpB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/src/main/res/values/strings.xml#L6)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove if you'd like
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by coreywoodfield** [comment]
Review status: 13 of 47 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[app/build.gradle, line 9 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2CcdmRLUyGz_3uqSe:-KVBwn29gIn33LD_YGtp:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/app/build.gradle#L9)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Change this back for now
</details>
Done.

---

*[support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java, line 85 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KV2H0nQiYfOhxMctEW2:-KVBwmDxxqS5VsF-uxOm:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9584277632e771c21471cbd3a3cacf8edfe916df/support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java#L85)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Tons of comments in this one
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-:-KVCGu-jIkP9DxOv1qA2:bnfp4nl)*

**Comment by romrell4** [comment]
Reviewed 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KXvU2zo2gxp6R6MnJmf:-KXvU2zpag07_JLIJaB2:bl62yyq) (no related file):*
Continue merging dev until we are ready for the first release

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 9 of 9 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KXvU2zo2gxp6R6MnJmf:-KZSvnsqrTcHh67tx-Qw:bsxigyn) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Continue merging dev until we are ready for the first release
</blockquote></details>

Don't mark it done until we're ready for the first release :) Otherwise, I continue getting notifications that I still have to do something on it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by coreywoodfield** [comment]
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KXvU2zo2gxp6R6MnJmf:-KZTDuZ_0kGeXpiH8XUD:b8kj4qy) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't mark it done until we're ready for the first release :) Otherwise, I continue getting notifications that I still have to do something on it :)
</blockquote></details>

If I don't mark it as done, I keep getting notifications :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 71 of 71 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r17.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r19.
Review status: 66 of 67 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r21.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r22.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KaIWV3Pq8GBx8pQXm85:-KaIWV3Pq8GBx8pQXm86:bkatehs) (no related file):*
Is mpn fixed and done and everything?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-KaIWV3Pq8GBx8pQXm85:-KaIWhSxqT-pfRNf_SOL:b-fglyyu) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is mpn fixed and done and everything?
</blockquote></details>

It worked last time I tested it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/84#-:-KaIaTI6KQVoMDeLEWah:bnfp4nl)*

**Pull request merged**
