### PR TITLE
Feature/login

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/128)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 52 of 52 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 90 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-KaxlTVw28Kzco0sgTGN:-KaxlTVxYhyRmLfw3r2L:bsrsarm) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L90)):*
> ```Java
> 
> 	@Override
> 	protected void onNewIntent(Intent intent) {
> ```

Comment about how this will be called sorta like onStart when the stack gets popped

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 98 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-KaxlaOigC84cAaVyjUB:-KaxlaOigC84cAaVyjUC:b-xhxpi9) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L98)):*
> ```Java
> 	}
> 
> 	// Todo: add a log to adobe analytics here
> ```

Resolve TODO

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 116 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-KaxlvCPvDcBvO3-7dzV:-KaxlvCPvDcBvO3-7dzW:b-85dcju) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L116)):*
> ```Java
> 					startActivity(new Intent(this, Class.forName(feature.getActivityName())));
> 				} catch (ClassNotFoundException e) {
> 					e.printStackTrace();
> ```

LOG.e

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 120 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-Kaxm06Ek1QI4dmDvZZ9:-Kaxm06Ek1QI4dmDvZZA:b-4v07xc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L120)):*
> ```Java
> 			}), null);
> 			return;
> 		}
> ```

else instead

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 125 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-Kaxm1XCVHn0u4VU5QrN:-Kaxm1XCVHn0u4VU5QrO:b-85dcju) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L125)):*
> ```Java
> 			startActivity(new Intent(this, Class.forName(feature.getActivityName())));
> 		} catch (ClassNotFoundException e) {
> 			e.printStackTrace();
> ```

LOG.e

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 93 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-Kaxn2MdZyitx0SZrAYv:-Kaxn2Me3RRI_LxsRz8d:b-mx8csg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/support/src/main/java/edu/byu/support/login/LoginActivity.java#L93)):*
> ```Java
> 	}
> 
> 	public void handleLogin(EditText usernameEdit, EditText passwordEdit) {
> ```

Just pass in the Strings if you can (.getText().toString())

---

*[support/src/main/java/edu/byu/support/login/LoginSuccessfulCallback.java, line 27 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-Kaxntocudi36zCcBmC6:-Kaxntocudi36zCcBmC7:b-85dcju) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/support/src/main/java/edu/byu/support/login/LoginSuccessfulCallback.java#L27)):*
> ```Java
> 			}
> 		} catch (OperationCanceledException | IOException | AuthenticatorException e) {
> 			e.printStackTrace();
> ```

LOG.e

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 90 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-KaxlTVw28Kzco0sgTGN:-KaxpYbpOnBn3CnyHWWD:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L90)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about how this will be called sorta like onStart when the stack gets popped
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 98 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-KaxlaOigC84cAaVyjUB:-Kaxp_OuzMzzv0b1ACRN:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L98)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Resolve TODO
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 116 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-KaxlvCPvDcBvO3-7dzV:-KaxpkRiMS3fQi1O7TIA:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L116)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

LOG.e
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 120 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-Kaxm06Ek1QI4dmDvZZ9:-KaxpyHmC3nC0Fh3xxDL:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L120)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

else instead
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 125 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-Kaxm1XCVHn0u4VU5QrN:-Kaxq7gCrDEDjYol9C6Y:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L125)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

LOG.e
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 93 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-Kaxn2MdZyitx0SZrAYv:-KaxqMmRO6bXG9Gb1a8_:b-ddi5xu) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/support/src/main/java/edu/byu/support/login/LoginActivity.java#L93)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Just pass in the Strings if you can (.getText().toString())
</blockquote></details>

This is a bit more convenient, as username and password are already fields in the class, which are set and used in this function. I'll still change it if you really want me to though

---

*[support/src/main/java/edu/byu/support/login/LoginSuccessfulCallback.java, line 27 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-Kaxntocudi36zCcBmC6:-Kaxqd3Mn5tUt6XpYitU:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fd32f250430d31c22da7ae3a22c3fb0ba689b99d/support/src/main/java/edu/byu/support/login/LoginSuccessfulCallback.java#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

LOG.e
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128)*

**Comment by romrell4** [comment]
Reviewed 1 of 52 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/128#-:-Kaxr2wqh4n-atdngSvw:bnfp4nl)*

**Pull request merged**
