### PR TITLE
Makes map settings backwards compatible with v1 settings. Fixes #325

### LINKED ISSUE #325: Default map value not always set
The map style value has sometimes not been loading up when someone first gets the app

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/327)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/SettingsFragment.java, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327#-Kf8AiLK1w5WrVufSoVy:-Kf8AiLMxgUxvLqDpmsJ:bgiog65) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f9f649c7071015e5ff8969f88a777853b40af93a/app/src/main/java/edu/byu/suite/mainScreen/SettingsFragment.java#L14)):*
> ```Java
> 		super.onCreate(savedInstanceState);
> 		switch (PreferenceManager.getDefaultSharedPreferences(getActivity()).getString(getString(R.string.map_preference_key), "normal")) {
> 			case "normal":
> ```

Could we make these a little more static? Maybe string.xml?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327)*

**Comment by coreywoodfield** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/SettingsFragment.java, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327#-Kf8AiLK1w5WrVufSoVy:-Kf8DAZ_d97v3bTU2r1m:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f9f649c7071015e5ff8969f88a777853b40af93a/app/src/main/java/edu/byu/suite/mainScreen/SettingsFragment.java#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could we make these a little more static? Maybe string.xml?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/SettingsFragment.java, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327#-Kf8AiLK1w5WrVufSoVy:-Kf8DVFDrkYe0g9EyzLt:b-7wzyxb) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f9f649c7071015e5ff8969f88a777853b40af93a/app/src/main/java/edu/byu/suite/mainScreen/SettingsFragment.java#L14)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove "map"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/SettingsFragment.java, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327#-Kf8AiLK1w5WrVufSoVy:-Kf8EMjLYocGQJWNUuSs:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f9f649c7071015e5ff8969f88a777853b40af93a/app/src/main/java/edu/byu/suite/mainScreen/SettingsFragment.java#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove "map"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/327#-:-Kf8EWTmNvOjMacfllS3:bnfp4nl)*

**Pull request merged**
