### PR TITLE
Fixed #202. Also fixes #176

### LINKED ISSUE #176: University Class Schedule: not very convenient formatting
The section details is currently formatted as shown in the following example:
```
TTh 12:00p - 1:15p JFSB B137
Available Seats: 28/38
```
I think it'd be more clear if it was as follows:
```
TTh 12:00p - 1:15p
JFSB B137
Available Seats: 28/38
```
Also, this row is clickable in iOS and shows where the building is on a map. @romrell4 do we want to add this functionality to Android?

### LINKED ISSUE #202: University Class Schedule
Winter 2017 -> BUS M -> 205R -> Pop up

Winter 2017 -> BUS M -> 430 -> View all Sections -> Search for "da"

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/271)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeBPMVEeSmsA0XydQt-:-KeBPMVEeSmsA0XydQt0:bqiszy0) (no related file):*
Fix search

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeBPd6eNOZXhp06pEmh:-KeBPd6eNOZXhp06pEmi:b-xxq1ow) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9e20caf8ab8ec93b05773fe6b79e96bd17efb319/app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java#L26)):*
> ```Java
> 			public void onSuccess(Call<ClassScheduleResponseWrapper> call, retrofit2.Response<ClassScheduleResponseWrapper> response) {
> 				ByuRecyclerAdapter<DataType> adapter = getPopulatedAdapter(response.body().getRegOfferingsService().getResponse());
> 				if (adapter != null) {
> ```

Comment about when this could be null

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeExS-A9lZNMeA7Tw1b:-KeExS-A9lZNMeA7Tw1c:b-2ndxgz) (no related file):*
Fix #176 as well while we're on this branch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by coreywoodfield** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeBPMVEeSmsA0XydQt-:-KeHCosNP4jcq9lF5lz6:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix search
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeBPd6eNOZXhp06pEmh:-KeHEXIdnKhokjEmZOBd:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9e20caf8ab8ec93b05773fe6b79e96bd17efb319/app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment about when this could be null
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by romrell4** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 40 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJmgx219af5VJhMZaI:-KeJmgx219af5VJhMZaJ:b-pp1cpr) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L40)):*
> ```Java
> 		getSupportActionBar().setSubtitle(course.getCourseTitle());
> 
> 		// Again, same information as v1, but displayed in a recycler view instead of in a billion text views
> ```

Remove this comment and change the data to match iOS. It's close, but not there yet. Also, why aren't we using details? We should be using detail rows

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 89 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJllvd7Qp_GsuUIX80:-KeJllvghU-IVY2gpFQP:b-lpa39s) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L89)):*
> ```Java
> 		@Override
> 		public int getItemViewType(int position) {
> 			return get(position) instanceof DefaultRowWithClickListener ? R.layout.default_list_item_wrap_indicator : R.layout.default_list_item_detail;
> ```

Why are we wrapping this one? Could you send me a screenshot of the row when it gets too long and how the wrapping looks?

---

*[support/src/main/java/edu/byu/support/ByuConstants.java, line 15 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJpufl3yYUJgdS2ulv:-KeJpufmTot1-B49I0v2:bv5343q) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/support/src/main/java/edu/byu/support/ByuConstants.java#L15)):*
> ```Java
> 	public static final String SUBTITLE = "subtitle";
> 	public static final String BUILDING = "building";
> 	public static final String BUILDING_ACRONYM = "acronym";
> ```

Wh aren't these in the BuildingActivity? Are they being used by anyone else who isn't already importing it?

---

*[support/src/main/java/edu/byu/support/client/campusLocation/controller/BuildingActivity.java, line 40 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJqxYxHLo4h7N_SqwG:-KeJqxYxHLo4h7N_SqwH:bzd1l12) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/support/src/main/java/edu/byu/support/client/campusLocation/controller/BuildingActivity.java#L40)):*
> ```Java
> 			initializeView(building);
> 		} else {
> 			// I added this because the SectionDetailsActivity wants to link here but doesn't have a complete building object
> ```

Instead of adding all this logic here, the university class schedule activity should load the buildings itself and pass the building in. I think this is a better solution because from the iOS app, university class schedule is the ONLY one that doesn't have a building object

---

*[support/src/main/java/edu/byu/support/client/campusLocation/controller/BuildingMapFragment.java, line 36 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJrV2kyzwSYWwQTjSN:-KeJrV2kyzwSYWwQTjSO:b-m1fnje) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/support/src/main/java/edu/byu/support/client/campusLocation/controller/BuildingMapFragment.java#L36)):*
> ```Java
> 	public void onMapReady(GoogleMap googleMap) {
> 		super.onMapReady(googleMap);
> 		Building building = getArguments().getParcelable(BUILDING_ARGUMENT);
> ```

If I understand correctly, all we really did here was inline the setUpMap function?

---

*[support/src/main/java/edu/byu/support/client/registrationClient/model/Section.java, line 87 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJsU6Wj2Vs5ebD1Kdu:-KeJsU6Wj2Vs5ebD1Kdv:b-rc9vi7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/support/src/main/java/edu/byu/support/client/registrationClient/model/Section.java#L87)):*
> ```Java
> 	}
> 
> 	public String getBuildingNotNull() {
> ```

Call this "getNullSafeBuilding"

---

*[support/src/main/java/edu/byu/support/client/registrationClient/model/Section.java, line 143 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJsWrn0cYm-u9mwiwn:-KeJsWrn0cYm-u9mwiwo:btdk6z9) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/support/src/main/java/edu/byu/support/client/registrationClient/model/Section.java#L143)):*
> ```Java
> 		if (instructor != null && instructor.toLowerCase().contains(lowerCaseQuery)
> 			// Building is almost never null, but it was once, so we have to check it
> 			|| building != null && building.toLowerCase().contains(lowerCaseQuery)
> ```

should we just use getNullSafeBuilding here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/client/campusLocation/controller/BuildingMapFragment.java, line 36 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJrV2kyzwSYWwQTjSN:-KeKmtXOUxQ1F2Sbjvnz:b-pxvsrn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/support/src/main/java/edu/byu/support/client/campusLocation/controller/BuildingMapFragment.java#L36)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

If I understand correctly, all we really did here was inline the setUpMap function?
</blockquote></details>

I made the onInfoWindowClickListener simpler as well

---

*[support/src/main/java/edu/byu/support/client/registrationClient/model/Section.java, line 143 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJsWrn0cYm-u9mwiwn:-KeKmzwPp2Vd3nwvFF9r:bb7lgjf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cac1f5223581087baa0641a18abedaad8d0baa5c/support/src/main/java/edu/byu/support/client/registrationClient/model/Section.java#L143)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

should we just use getNullSafeBuilding here
</blockquote></details>

nope

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeZHYOzMqh52UA6OSRu:-KeZHYP0EAxI6Sy2oMbS:b4k7b9k) (no related file):*
Fix date formatting on last activity. Should be yyyy-MM-dd. Also, all that day should be in a detail view

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by coreywoodfield** [comment]
Review status: 4 of 12 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeZHYOzMqh52UA6OSRu:-Ke_WbbGII64WngTKvdX:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix date formatting on last activity. Should be yyyy-MM-dd. Also, all that day should be in a detail view
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 40 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJmgx219af5VJhMZaI:-Ke_WhjLmNYo4sAC2ZBw:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e54fb838b66f2fa39d0aa041ee08f82a03277195/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove this comment and change the data to match iOS. It's close, but not there yet. Also, why aren't we using details? We should be using detail rows
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/ByuConstants.java, line 15 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJpufl3yYUJgdS2ulv:-Ke_XgCbmd7x0Hz1VGsE:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e54fb838b66f2fa39d0aa041ee08f82a03277195/support/src/main/java/edu/byu/support/ByuConstants.java#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Wh aren't these in the BuildingActivity? Are they being used by anyone else who isn't already importing it?
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/client/registrationClient/model/Section.java, line 87 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJsU6Wj2Vs5ebD1Kdu:-Ke_WBjQI59EGO6qQjZw:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e54fb838b66f2fa39d0aa041ee08f82a03277195/support/src/main/java/edu/byu/support/client/registrationClient/model/Section.java#L87)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Call this "getNullSafeBuilding"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-Ke_bi-egrSSn29wMQcb:-Ke_bi-egrSSn29wMQcc:b-jh1c5o) (no related file):*
Add iOS functionality

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 64 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-Ke_cXBzdfYakR3PtPuz:-Ke_cXC-phRtp0ZMCbcC:bswmlg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3900284861ecf7e5e6867f580c6417c0b7124126/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L64)):*
> ```Java
> 	@NonNull
> 	private DefaultRow getLocationRow(Section section) {
> 		return section.getBuilding() != null
> ```

What would happen here if the building was TBA or something that's isn't in our buildings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 64 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-Ke_cXBzdfYakR3PtPuz:-Ke_d-c0mpzCdael2-5l:b-6c4w9h) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3900284861ecf7e5e6867f580c6417c0b7124126/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L64)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What would happen here if the building was TBA or something that's isn't in our buildings?
</blockquote></details>

what building

---

*[support/src/main/java/edu/byu/support/client/campusLocation/controller/BuildingActivity.java, line 40 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeJqxYxHLo4h7N_SqwG:-Ke_cfzVdN9JyY4J3Rk2:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e54fb838b66f2fa39d0aa041ee08f82a03277195/support/src/main/java/edu/byu/support/client/campusLocation/controller/BuildingActivity.java#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead of adding all this logic here, the university class schedule activity should load the buildings itself and pass the building in. I think this is a better solution because from the iOS app, university class schedule is the ONLY one that doesn't have a building object
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by coreywoodfield** [comment]
Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-KeExS-A9lZNMeA7Tw1b:-Ke_ejlx_MBwmw0WQQRl:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix #176 as well while we're on this branch
</blockquote></details>

Done.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-Ke_bi-egrSSn29wMQcb:-Ke_ejTqDZ0hzAM2Fv_A:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add iOS functionality
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 60 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-Ke_f1NPWLHQyIdh1QfM:-Ke_f1NPWLHQyIdh1QfN:b-r8otvu) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3548ab5a388a473d638178aa70223d89abc11596/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L60)):*
> ```Java
> 			public void onSuccess(Call<BuildingsWrapper> call, Response<BuildingsWrapper> response) {
> 				for (BuildingsWrapper.BuildingWrapper wrapper : response.body().getBuildingInformationList()) {
> 					if (buildings.containsKey(wrapper.getBuildingAdditionalData().getAcronym())) {
> ```

Comment here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 60 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-Ke_f1NPWLHQyIdh1QfM:-Ke_fjIyqGBKQ0MrpKLK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3548ab5a388a473d638178aa70223d89abc11596/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L60)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/271#-:-Ke_fsKrZdrWRfUwK9bq:bnfp4nl)*

**Pull request merged**
