### PR TITLE
Hotfix/calendars

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/393)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA25WZRjXNjG2NQyjJ:-KjA25WaZ6QWB0TZ5hf_:bija7qw) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L39)):*
> ```Java
> public class CalendarActivity extends ByuRecyclerViewActivity {
> 	public static String CALENDAR_TAG = "calendar";
> 	private int offset = 3;
> ```

static final (all caps)

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2HO9I7WnbMtc2hEa:-KjA2HO9I7WnbMtc2hEb:bgzumlc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L39)):*
> ```Java
> 				dismissProgressDialog();
> 				List<CampusCalendar> campusCalendars = response.body();
> 				campusCalendars.add(0, new CampusCalendar("Academic", "395"));
> ```

Don't add at the 0 index. Add it to the end, then sort them

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2R-cE9nhwTVwILOP:-KjA2R-dHfxom7qzTCPM:b2s2ria) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L57)):*
> ```Java
> 			listItems.add(new EventListItem(getString(R.string.event_end_title_text), getString(R.string.calendar_long_date_time_format, event.getEndDateTime()), EventListItemType.DEFAULT_WITH_DETAIL));
> 		}
> 		if (!event.getDescription().replaceAll("\\W", "").isEmpty()) {
> ```

What is this?

---

*[app/src/main/java/edu/byu/suite/features/calendars/model/Event.java, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2_UHWrfZqMTQZOPP:-KjA2_UHWrfZqMTQZOPQ:bxmod39) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/model/Event.java#L19)):*
> ```Java
> 
> public class Event extends ByuParcelable implements Comparable<Event>, ByuSearchableRecyclerAdapter.Queryable {
> 	private String moreInformationUrl;
> ```

Can we put these in a more helpful order? Probably eventId, title, start, end, allDay, description, moreInformationUrl, locationName. Also change the order of the constructor, getters, and parcelable

---

*[app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2otcKSwsQ-h3ppnH:-KjA2otcKSwsQ-h3ppnI:b-agnmqg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java#L41)):*
> ```Java
> 	@Override
> 	protected String getBaseUrl() {
> 		return "https://calendar-test.byu.edu/api/";
> ```

remove -test

---

*[app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2rI4NveOb7On_JGP:-KjA2rI4NveOb7On_JGQ:byp18fd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java#L52)):*
> ```Java
> 	protected Converter.Factory getConverter() {
> 		return GsonConverterFactory.create(new GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.UPPER_CAMEL_CASE)
> 				.registerTypeAdapter(Date.class, new JsonDateDeserializer(Collections.singletonList(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US))))
> ```

Remove

---

*[app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java, line 83 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2ulN6U39evwCG4D0:-KjA2ulN6U39evwCG4D1:ba4ikhi) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java#L83)):*
> ```Java
> 
> 			return new Event(
> 					getString("MoreInformationUrl"),
> ```

Reorder

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by poolguy** [comment]
Review status: 2 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA25WZRjXNjG2NQyjJ:-KjADU1AxxVfT6sl2Npl:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L39)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

static final (all caps)
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2HO9I7WnbMtc2hEa:-KjAE81AUf5oM4W5LoC8:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L39)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't add at the 0 index. Add it to the end, then sort them
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2R-cE9nhwTVwILOP:-KjADAOlpNktpQI8sajK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/model/Event.java, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2_UHWrfZqMTQZOPP:-KjAFQcggKWmD387GETw:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/model/Event.java#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we put these in a more helpful order? Probably eventId, title, start, end, allDay, description, moreInformationUrl, locationName. Also change the order of the constructor, getters, and parcelable
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2otcKSwsQ-h3ppnH:-KjADGpGo9bl3npBeT1l:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

remove -test
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2rI4NveOb7On_JGP:-KjADJqmtA_chevNtj4s:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java, line 83 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2ulN6U39evwCG4D0:-KjAFRF8UPfcBRjdsyVU:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/service/CalendarsClient.java#L83)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Reorder
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA25WZRjXNjG2NQyjJ:-KjAL0maROUSADVbrUtI:b-8nyi3w) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L39)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 42 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjAL4j1Oze7_-eEKznr:-KjAL4j1Oze7_-eEKzns:b-99ki2r) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/849b5eabf3df7403ea6c6e0b289fb830382cca7a/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L42)):*
> ```Java
> 				List<CampusCalendar> campusCalendars = response.body();
> 				campusCalendars.add(new CampusCalendar("Academic", "395"));
> 				Collections.sort(campusCalendars, (o1, o2) -> o1.getTitle().compareTo(o2.getTitle()));
> ```

If you'd prefer, you could just make the object comparable. Then you wouldn't have to have the lambda here. Have you done that before?

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2R-cE9nhwTVwILOP:-KjAK2IlJCpEqGn8wr2t:bseg0dc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L57)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems like there's some duplicated code here... Is there anyway to simplify? It looks like we could have a function like this:

```java
addData(List<EventListItem> list, boolean condition, EventListItem... rows)
```

Talk to me if you have questions on this one

---

*[app/src/main/java/edu/byu/suite/features/calendars/model/EventListItemType.java, line 11 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjAKrIONrhZreq0n1_X:-KjAKrIONrhZreq0n1_Y:b-3xqx4u) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/849b5eabf3df7403ea6c6e0b289fb830382cca7a/app/src/main/java/edu/byu/suite/features/calendars/model/EventListItemType.java#L11)):*
> ```Java
> 	DEFAULT_WITH_DETAIL,
> 	TEXT_VIEW,
> 	BUTTON
> ```

What is button used for? Normally I don't like buttons in table views...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by poolguy** [comment]
Review status: 3 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA25WZRjXNjG2NQyjJ:-KjALMS4xnTufxm7AC1g:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L39)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 42 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjAL4j1Oze7_-eEKznr:-KjANmkL38oblCzohtv7:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/849b5eabf3df7403ea6c6e0b289fb830382cca7a/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

If you'd prefer, you could just make the object comparable. Then you wouldn't have to have the lambda here. Have you done that before?
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/model/EventListItemType.java, line 11 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjAKrIONrhZreq0n1_X:-KjALkXxtBahWU7Ta5_j:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/849b5eabf3df7403ea6c6e0b289fb830382cca7a/app/src/main/java/edu/byu/suite/features/calendars/model/EventListItemType.java#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is button used for? Normally I don't like buttons in table views...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by romrell4** [comment]
Reviewed 1 of 8 files at r1, 7 of 7 files at r3.
Review status: 8 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 66 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjATLfQhPoIq2WOOwsg:-KjATLfQhPoIq2WOOwsh:b2s2ria) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2c96725b54b0d0a7044f7812427baffc685637fd/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L66)):*
> ```Java
> 			}
> 		}
> 		if (!event.getDescription().replaceAll("\\W", "").isEmpty()) {
> ```

What is this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r4.
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjA2R-cE9nhwTVwILOP:-KjATpn43kcshf-ByKhQ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/760022e3d82aeec2a07041bae8f3ad166d37a2d8/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It seems like there's some duplicated code here... Is there anyway to simplify? It looks like we could have a function like this:

```java
addData(List<EventListItem> list, boolean condition, EventListItem... rows)
```

Talk to me if you have questions on this one
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 66 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjATLfQhPoIq2WOOwsg:-KjATbJFJZR221mrIs3f:b66o5cu) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2c96725b54b0d0a7044f7812427baffc685637fd/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L66)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

Sometimes the service will return "  " as the description and it looks like the trim function in our deserializer isn't catching it. So here I check for whitespace instead of null.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 66 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjATLfQhPoIq2WOOwsg:-KjAVg9tRg42n2lK4b12:bkq28us) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2c96725b54b0d0a7044f7812427baffc685637fd/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L66)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Sometimes the service will return "  " as the description and it looks like the trim function in our deserializer isn't catching it. So here I check for whitespace instead of null.
</blockquote></details>

TextUtils.isEmpty

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by poolguy** [comment]
Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 66 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393#-KjATLfQhPoIq2WOOwsg:-KjAhDrA6y-4TRFtpAmM:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2c96725b54b0d0a7044f7812427baffc685637fd/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L66)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TextUtils.isEmpty
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/393)*

**Pull request merged**
