### PR TITLE
Closes #242

### LINKED ISSUE #242: My Next Class functionality
The functionality of this page has been changed on iOS since we built it. Please reflect the new functionality

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/251)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java, line 213 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251#-KdSnuL2JCzAISDdPehH:-KdSnuL2JCzAISDdPehI:bw8pyor) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b0fa8b4a868acff960dff07fe41760e638b22fad/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java#L213)):*
> ```Java
> 				startActivity(intent);
> 			});
> 			findViewById(R.id.nextClassLayout).setOnClickListener(view -> {
> ```

Move this above the other one (since it's on top in the layout, right?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251)*

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251)*

**Comment by poolguy** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java, line 213 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251#-KdSnuL2JCzAISDdPehH:-KdSopKG1ac0nSiAHxC4:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c0a91e8f2cd622bdcedaf36d80fa2a208bba6b6a/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java#L213)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move this above the other one (since it's on top in the layout, right?)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java, line 296 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251#-KdStVk46slu0z8jFOmH:-KdStVk46slu0z8jFOmI:b1jcdj5) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/edfd17b42626ad06afaecd4db616a77674980c74/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java#L296)):*
> ```Java
> 		// be considered the "next class"
> 		if (!course.getClassPeriod().endsWith("a") && !course.getClassPeriod().endsWith("p")) {
> 			currentCourseCalendar.add(Calendar.YEAR, 100);
> ```

Set it back in time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251)*

**Comment by poolguy** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java, line 296 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251#-KdStVk46slu0z8jFOmH:-KdSx_MRTdaEAaYHA6lX:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/25b60f20459277836dd8fdfaa47d60823509bfc0/app/src/main/java/edu/byu/suite/features/myNextClass/controller/MyNextClassMainActivity.java#L296)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Set it back in time
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/251#-:-KdSxmpSkH6i-qWX9qsG:bnfp4nl)*

**Pull request merged**
