### PR TITLE
Fixed maps

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/105)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 47 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KY6PQbLxnAZPns9lHEt:-KY6PQbLxnAZPns9lHEu:bt56565) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e5cc11f4f6d42034f1ae6060a17f5683697f6fec/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L47)):*
> ```Java
> import static android.opengl.GLES10.GL_MAX_TEXTURE_SIZE;
> 
> public class AedLocatorMainActivity extends ByuActivity {
> ```

Why so many changes to AED?

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KY6P-mAoMYKOMiRwmFq:-KY6P-mAoMYKOMiRwmFr:biev71p) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fc07d866f87a9b9505121b1f24344b28f52d16cc/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L52)):*
> ```Java
> import static android.opengl.GLES10.GL_MAX_TEXTURE_SIZE;
> 
> public class AedLocatorMainActivity extends ByuActivity implements LocationListener, GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener {
> ```

We have been preferring explicit inner classes rather than implementing interfaces at the class level

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 135 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KY6PGp7qOhsbtbfsGds:-KY6PGp7qOhsbtbfsGdt:b-emyn05) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fc07d866f87a9b9505121b1f24344b28f52d16cc/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L135)):*
> ```Java
> 		} else if (requestCode == REQUEST_ACCESS_FINE_LOCATION_TAG && grantResults[0] == PackageManager.PERMISSION_DENIED) {
> 			shouldOpenAllAedsActivity = true;
> 			startAllAedsActivity();
> ```

What is this doing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 153 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KYFuY6lAzENl4LDylv8:-KYFuY6lAzENl4LDylv9:brarzfd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f81451f8527189327f69b8463a4231e6cb58f54e/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L153)):*
> ```Java
> 				aedList = response.body().getAeds();
> 				viewAllAedsMenuItem.setEnabled(true);
> 				if (shouldOpenAllAedsActivity) {
> ```

Comments

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 186 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KYFufpL6BJ4-4K2sEEl:-KYFufpL6BJ4-4K2sEEm:b-3bk01q) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f81451f8527189327f69b8463a4231e6cb58f54e/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L186)):*
> ```Java
> 	}
> 
> 	private void startAllAedsActivity() {
> ```

Comment above here letting the user know when it could get called

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/model/Aed.java, line 99 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KYFvGOE6FxhgP2H4R6b:-KYFvGOE6FxhgP2H4R6c:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f81451f8527189327f69b8463a4231e6cb58f54e/app/src/main/java/edu/byu/suite/features/aedLocator/model/Aed.java#L99)):*
> ```Java
> 	@Override
> 	public CharSequence getDetailText() {
> 		return metersToAed == 0f ? "" : String.valueOf(getFeetToAed() + " ft");
> ```

Comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KY6P-mAoMYKOMiRwmFq:-KYFzR76ZTTZg9TyDO5B:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/fc07d866f87a9b9505121b1f24344b28f52d16cc/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We have been preferring explicit inner classes rather than implementing interfaces at the class level
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 153 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KYFuY6lAzENl4LDylv8:-KYFzLKHIV4TyNgGA0ZO:bb7f2mf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f81451f8527189327f69b8463a4231e6cb58f54e/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L153)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comments
</blockquote></details>

done

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 186 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KYFufpL6BJ4-4K2sEEl:-KYFzNJd0yte-a1AeVz6:bb7f2mf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f81451f8527189327f69b8463a4231e6cb58f54e/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L186)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment above here letting the user know when it could get called
</blockquote></details>

done

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/model/Aed.java, line 99 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-KYFvGOE6FxhgP2H4R6b:-KYFzQPwL7N-ubc2_Uok:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f81451f8527189327f69b8463a4231e6cb58f54e/app/src/main/java/edu/byu/suite/features/aedLocator/model/Aed.java#L99)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/105#-:-KYG-7FtG4NHi-wF14Ec:bnfp4nl)*

**Pull request merged**
