### PR TITLE
Fix/cougarcash

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/183)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 10 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 75 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/183#-Kce5BxEFv_JvAzDEF6V:-Kce5BxH4Mi-3aeNP5Y4:bm67pg7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/94f0002ff8de110f7a46013239e455d8a3b71a3e/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L75)):*
> ```Java
> 		super.onNewIntent(intent);
> 		// When another activity clears top and resumes this one, let's reload the balance
> 		loadBalance();
> ```

Go ahead and load all the data

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/183)*

**Comment by coreywoodfield** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 75 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/183#-Kce5BxEFv_JvAzDEF6V:-Kce6SmdTJTTaYuqf_JA:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/94f0002ff8de110f7a46013239e455d8a3b71a3e/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L75)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Go ahead and load all the data
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/183)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/183)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/183#-:-Kce6VkydKZPs_IRD_C_:bnfp4nl)*

**Pull request merged**
