### PR TITLE
MapMyClasses: closes #162

### LINKED ISSUE #162: Map My Classes: No message on empty list
Name of Tester: Seth
Feature: Map My Classes

How to produce error:
Should display message that says "No classes found for [yearTerm]" on list fragment when there aren't any classes found for the specified yearTerm

Expected Result:

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/257)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/ClassListFragment.java, line 38 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-KdWNWLvti-5VY7ZYU8N:-KdWNWLvti-5VY7ZYU8O:b-d9avlk) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/56f3f437bc238bf0be3b8cab3e3d7374bc1896cb/app/src/main/java/edu/byu/suite/features/mapMyClasses/ClassListFragment.java#L38)):*
> ```Java
> 		ByuRecyclerView recyclerView = (ByuRecyclerView) view.findViewById(R.id.recyclerView);
> 		recyclerView.setAdapter(adapter);
> 		viewSwitcher = (ViewSwitcher) view.findViewById(R.id.viewSwitcher);
> ```

No need to save this viewSwitcher here. Can't you just use findViewById in the load function?

---

*[app/src/main/res/layout/map_my_classes_fragment_list.xml, line 2 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-KdWNqFN3uNoIJe-B4Mi:-KdWNqFN3uNoIJe-B4Mj:bm6kx6l) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/56f3f437bc238bf0be3b8cab3e3d7374bc1896cb/app/src/main/res/layout/map_my_classes_fragment_list.xml#L2)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
> ```

No that I think about it, can't we reuse the same xml file that we did for the activities?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257)*

**Comment by poolguy** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/ClassListFragment.java, line 38 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-KdWNWLvti-5VY7ZYU8N:-KdgnV2gTkr_KFZPqNVr:b948ldr) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/56f3f437bc238bf0be3b8cab3e3d7374bc1896cb/app/src/main/java/edu/byu/suite/features/mapMyClasses/ClassListFragment.java#L38)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

No need to save this viewSwitcher here. Can't you just use findViewById in the load function?
</blockquote></details>

Sort of. I have to save the view. Which isn't a problem.

---

*[app/src/main/res/layout/map_my_classes_fragment_list.xml, line 2 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-KdWNqFN3uNoIJe-B4Mi:-KdgmfwOBrrSGbPXVo1w:bs210nv) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/56f3f437bc238bf0be3b8cab3e3d7374bc1896cb/app/src/main/res/layout/map_my_classes_fragment_list.xml#L2)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

No that I think about it, can't we reuse the same xml file that we did for the activities?
</blockquote></details>

The only reason we wouldn't is because the activity one has a toolbar in it. We should be able to use it, I would just have to do a view.GONE on the toolbar.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257)*

**Comment by romrell4** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/ClassListFragment.java, line 38 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-KdWNWLvti-5VY7ZYU8N:-KdgnnR5hX4B0GcFJDhF:b-mmuxq1) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/56f3f437bc238bf0be3b8cab3e3d7374bc1896cb/app/src/main/java/edu/byu/suite/features/mapMyClasses/ClassListFragment.java#L38)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Sort of. I have to save the view. Which isn't a problem.
</blockquote></details>

Ah. If you're going to have to do that, just save the viewswitcher :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/res/layout/map_my_classes_fragment_list.xml, line 2 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-KdWNqFN3uNoIJe-B4Mi:-Kdgp1NA3f_xCLj_sg6G:b-mb0vhn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/56f3f437bc238bf0be3b8cab3e3d7374bc1896cb/app/src/main/res/layout/map_my_classes_fragment_list.xml#L2)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

The only reason we wouldn't is because the activity one has a toolbar in it. We should be able to use it, I would just have to do a view.GONE on the toolbar.
</blockquote></details>

Look into the include

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257)*

**Comment by poolguy** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/ClassListFragment.java, line 38 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-KdWNWLvti-5VY7ZYU8N:-KdguxQXaw13c7Cz8epY:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/56f3f437bc238bf0be3b8cab3e3d7374bc1896cb/app/src/main/java/edu/byu/suite/features/mapMyClasses/ClassListFragment.java#L38)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Ah. If you're going to have to do that, just save the viewswitcher :)
</blockquote></details>

Done.

---

*[support/src/main/res/layout/recycler_view_switcher_layout.xml, line 2 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-KdWNqFN3uNoIJe-B4Mi:-KdguwON9aha7ABEK1YO:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/56f3f437bc238bf0be3b8cab3e3d7374bc1896cb/support/src/main/res/layout/recycler_view_switcher_layout.xml#L2)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Look into the include
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257)*

**Comment by romrell4** [comment]
Reviewed 1 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/257#-:-KdgvVIbTwfOGr4izUkc:bnfp4nl)*

**Pull request merged**
