### PR TITLE
Hotfix/calendars event view

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/276)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 146 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276#-KeFMWCQ8qK6mQXYAm5j:-KeFMWCQ8qK6mQXYAm5k:b-dyrzw5) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/53acf4acf875d97f9c5e2f6c3b659e1687f162ca/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L146)):*
> ```Java
> 				// make the location row clickable to display a dialog with the full text onClick.
> 				if (data.getMainText().equals(getResources().getString(R.string.event_location_title_text))) {
> 					itemView.setEnabled(true);
> ```

Use a second constructor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276)*

**Comment by poolguy** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 146 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276#-KeFMWCQ8qK6mQXYAm5j:-KeFOiL33ncz34P4jCRQ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/53acf4acf875d97f9c5e2f6c3b659e1687f162ca/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L146)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use a second constructor
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/model/EventListItem.java, line 11 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276#-KeFUrl15c9NUIkBI4r5:-KeFUrl15c9NUIkBI4r6:b-l6mkjh) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0532ea63d76c1b4ffef603248271ada1a2cabf9d/app/src/main/java/edu/byu/suite/features/calendars/model/EventListItem.java#L11)):*
> ```Java
> 	private String detailText;
> 	private EventListItemType eventListItemType;
> 	private boolean isRowEnabled = false;
> ```

rename

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276)*

**Comment by poolguy** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/model/EventListItem.java, line 11 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276#-KeFUrl15c9NUIkBI4r5:-KeFV7eFyH51njQh1qDp:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0532ea63d76c1b4ffef603248271ada1a2cabf9d/app/src/main/java/edu/byu/suite/features/calendars/model/EventListItem.java#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/276#-:-KeFWs4kN5c9EJ7BlmZj:bnfp4nl)*

**Pull request merged**
