### PR TITLE
Feature/map my finals2

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/85)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/build.gradle, line 36 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85#-KVB_r_cdJEcpanCZSbf:-KVB_r_cdJEcpanCZSbg:byp18fd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3ce930a662c317858edfcc24c44db24bd738abf7/app/build.gradle#L36)):*
> ```Gradle
> 	compile fileTree(dir: 'libs', include: ['*.jar'])
> 	compile project(':support')
> 	compile 'com.android.support:appcompat-v7:25.0.0'
> ```

Remove

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/controller/ClassMapFragment.java, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85#-KVBaYgzt9pUcTPoWFTM:-KVBaYh-WHc4qKpslKP4:byp1ktf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3ce930a662c317858edfcc24c44db24bd738abf7/app/src/main/java/edu/byu/suite/features/mapMyClasses/controller/ClassMapFragment.java#L101)):*
> ```Java
> 			}
> 			marker.setTag(buildingCourses);
> 			getMap().setOnInfoWindowClickListener(marker1 -> {
> ```

Rename

---

*[app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java, line 98 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85#-KVBbD099miSwVJRHbPF:-KVBbD099miSwVJRHbPG:byp1ktf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3ce930a662c317858edfcc24c44db24bd738abf7/app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java#L98)):*
> ```Java
> 			}
> 			marker.setTag(buildingExams);
> 			getMap().setOnInfoWindowClickListener(marker1 -> {
> ```

Rename

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85)*

**Comment by poolguy** [comment]
Review status: 32 of 41 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/build.gradle, line 36 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85#-KVB_r_cdJEcpanCZSbf:-KVBh3JG64WhIGf4DNbJ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3ce930a662c317858edfcc24c44db24bd738abf7/app/build.gradle#L36)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/controller/ClassMapFragment.java, line 101 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85#-KVBaYgzt9pUcTPoWFTM:-KVBhWZZ8fggQWvrGhKg:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3ce930a662c317858edfcc24c44db24bd738abf7/app/src/main/java/edu/byu/suite/features/mapMyClasses/controller/ClassMapFragment.java#L101)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Rename
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java, line 98 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85#-KVBbD099miSwVJRHbPF:-KVBhX1xTuq8GjroHPOj:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3ce930a662c317858edfcc24c44db24bd738abf7/app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java#L98)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Rename
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85)*

**Comment by romrell4** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/85#-:-KVBjcEQQatPuUUaZS7l:bnfp4nl)*

**Pull request merged**
