### PR TITLE
Hotfix/aed locator

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/132)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbRnoLYJYYfK430QLeh:-KbRnoLYJYYfK430QLei:b-tgkt32) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/69d371bc7ab1c95cbd474385d35421ec9b024e3f/support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java#L45)):*
> ```Java
> 
> 		// Force timeout of locationRequest after 10 seconds
> 		schedule = Executors.newScheduledThreadPool(1).schedule(new Runnable() {
> ```

Interesting... Was this a bug? What was happening?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbRnoLYJYYfK430QLeh:-KbWJo19_2kXuyM9LlMl:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/69d371bc7ab1c95cbd474385d35421ec9b024e3f/support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Interesting... Was this a bug? What was happening?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by poolguy** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbRnoLYJYYfK430QLeh:-KbWdI5zfT742X5j4yAq:b-zd3arl) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/69d371bc7ab1c95cbd474385d35421ec9b024e3f/support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java#L45)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Changed to 4 seconds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 123 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbWxGRG-10yq1QXrOxM:-KbWxGRINJAbLN8ufgBY:bsa9yj2) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5e545781bba79a8f32e36257cf8c521d77713530/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L123)):*
> ```Java
> 	private void startAllAedsActivity() {
> 		if (aedList != null) {
> 			startActivityForResult(new Intent(this, AllAedsActivity.class).putParcelableArrayListExtra(AllAedsActivity.AED_LIST, aedList).putExtra(REQUEST_CODE_TAG, REQUEST_SHOW_ALL_AEDS), REQUEST_SHOW_ALL_AEDS);
> ```

Why are we using REQUEST_SHOW_ALL_AEDS twice? What is this doing? Comments would help :)

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AllAedsMapFragment.java, line 68 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbWxhNULDOQMtum-v9r:-KbWxhNULDOQMtum-v9s:b-a32lc8) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5e545781bba79a8f32e36257cf8c521d77713530/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AllAedsMapFragment.java#L68)):*
> ```Java
> 
> 		getMap().setOnInfoWindowClickListener(marker -> {
> 			// Only if the user's location is known, send the user back to the main activity to see their proximity to the selected AED. Otherwise do nothing.
> ```

Why are you doing this? Can't you see the AED picture and details without having the user's location?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by poolguy** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 123 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbWxGRG-10yq1QXrOxM:-KbXKjFlEc6I9ikrX-zE:buyydde) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5e545781bba79a8f32e36257cf8c521d77713530/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L123)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why are we using REQUEST_SHOW_ALL_AEDS twice? What is this doing? Comments would help :)
</blockquote></details>

Fixed it.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AllAedsMapFragment.java, line 68 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbWxhNULDOQMtum-v9r:-KbXKok3pyTzPpiAEuHR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5e545781bba79a8f32e36257cf8c521d77713530/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AllAedsMapFragment.java#L68)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why are you doing this? Can't you see the AED picture and details without having the user's location?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 31 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbXNjs7nFopR1q6zwqQ:-KbXNjs7nFopR1q6zwqR:b8ie45a) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7d887bea54ea125bece9893f94f1ca19a969dc1/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L31)):*
> ```Java
> 	public static final String AED_TAG = "aed";
> 	public static final String REQUEST_CODE_TAG = "requestCode";
> 	public static final int REQUEST_SHOW_ALL_AEDS = 0;
> ```

REQUEST_LOCATION_SUCCESSFUL or something like that

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 32 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbXNrdb6KUBlWPSGCZk:-KbXNrdb6KUBlWPSGCZl:b6pn24y) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7d887bea54ea125bece9893f94f1ca19a969dc1/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L32)):*
> ```Java
> 	public static final String REQUEST_CODE_TAG = "requestCode";
> 	public static final int REQUEST_SHOW_ALL_AEDS = 0;
> 	public static final int REQUEST_LOCATION_DENIED = 2; // A psf with a value of 1 cannot be used because the parent class is already using a requestCode with the value of 1
> ```

REQUEST_LOCATION_FAILED

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 131 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbXOBmmM4skRzLR3kAw:-KbXOBmmM4skRzLR3kAx:b2nhexc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7d887bea54ea125bece9893f94f1ca19a969dc1/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L131)):*
> ```Java
> 	private void startAllAedsActivity() {
> 		if (aedList != null) {
> 			startActivityForResult(new Intent(this, AllAedsActivity.class).putParcelableArrayListExtra(AllAedsActivity.AED_LIST, aedList).putExtra(REQUEST_CODE_TAG, REQUEST_SHOW_ALL_AEDS), hasAccessToUserLocation ? REQUEST_SHOW_ALL_AEDS : REQUEST_LOCATION_DENIED);
> ```

Fix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by poolguy** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 31 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbXNjs7nFopR1q6zwqQ:-KbXP8JWzx7CrLJ4PUaO:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7d887bea54ea125bece9893f94f1ca19a969dc1/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

REQUEST_LOCATION_SUCCESSFUL or something like that
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 32 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbXNrdb6KUBlWPSGCZk:-KbXP8evo9xcxZv5p83h:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7d887bea54ea125bece9893f94f1ca19a969dc1/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

REQUEST_LOCATION_FAILED
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java, line 131 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbXOBmmM4skRzLR3kAw:-KbXPdDXsiDdKF08PzX8:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7d887bea54ea125bece9893f94f1ca19a969dc1/app/src/main/java/edu/byu/suite/features/aedLocator/controller/AedLocatorMainActivity.java#L131)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbqWZIj3-4xae9JdM1d:-KbqWZIk4vIk8tis-FM2:b-ld66ff) (no related file):*
Fix the bugs that you were working on

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-KbqWZIj3-4xae9JdM1d:-Kc-GwySPB4vYNovfglF:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fix the bugs that you were working on
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java, line 35 at r6](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-Kc-L4cjXC63M4WJmBya:-Kc-L4cjXC63M4WJmByb:byh5cnk) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4529b0b890b5094069fc2b9b9947ce7ac6244427/support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java#L35)):*
> ```Java
> 	private GoogleApiClient googleApiClient;
> 	protected Location currentLocation;
> 	public static boolean hasRequestedLocation;
> ```

Make private and default to false

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java, line 35 at r6](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-Kc-L4cjXC63M4WJmBya:-Kc-OFWBIs6n7h2770Nh:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4529b0b890b5094069fc2b9b9947ce7ac6244427/support/src/main/java/edu/byu/support/activity/ByuLocationActivity.java#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make private and default to false
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/132#-:-Kc-U9YrR7FOuS9bbVlP:bnfp4nl)*

**Pull request merged**
