### PR TITLE
Renamed usages of 'app' in whats new to 'feature'. Resolves #341

### LINKED ISSUE #341: Rename app to feature throughout app

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/342)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/whatsNew/WhatsNewDialog.java, line 123 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/342#-KfRzuGRl9Jrw6KOMA7W:-KfRzuGRl9Jrw6KOMA7X:b-bgvs11) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/deac09d871efa43456003f69addd4824eac1c36f/app/src/main/java/edu/byu/suite/mainScreen/whatsNew/WhatsNewDialog.java#L123)):*
> ```Java
> 		CollectionUtils.filter(updatedFeatures, featurePredicate);
> 		if (!updatedFeatures.isEmpty()) {
> 			data.add(new HeaderAdapter.Header("Changed Features"));
> ```

Let's go with "Updated Features" for the text here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/342)*

**Comment by coreywoodfield** [comment]
Review status: 4 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/whatsNew/WhatsNewDialog.java, line 123 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/342#-KfRzuGRl9Jrw6KOMA7W:-KfS2YIzmRUwlKqtTXHM:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/deac09d871efa43456003f69addd4824eac1c36f/app/src/main/java/edu/byu/suite/mainScreen/whatsNew/WhatsNewDialog.java#L123)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's go with "Updated Features" for the text here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/342)*

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/342)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/342#-:-KfS2uGc58o5NDtJYUfo:bnfp4nl)*

**Pull request merged**
