### PR TITLE
Added missing icons

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/65)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/65#-KTAc8mZs47JpAYiLtBZ:-KTAc8m_JsfQWSNfe7Xf:bu6jkw5) (no related file):*
Are these the new outline icons? Or the old v1 icons?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/65)*

**Comment by romrell4** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/65)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/65#-KTAc8mZs47JpAYiLtBZ:-KTAiKxJnq5-PdBXlDQT:bjg0yqx) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Are these the new outline icons? Or the old v1 icons?
</details>
I got them from Kate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/65)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/65#-:-KTAvyOMGe1XIXZbdevN:bnfp4nl)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/65)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/65#-:-KTAw5YAXiUAORLw7gNg:bnfp4nl)*

**Pull request merged**
