### PR TITLE
Fixes stuff

### LINKED ISSUE #352: Parking: Use tabLayout to switch between permanent and temporary in AddVehicleActivity

### PR DESCRIPTION
**Pull request by coreywoodfield**
Resolves #352, makes sure data sent to the server is the same data the user selected, makes sure model (nickname) is correctly sent to server

---
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/378)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 40 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378#-KguGqbJdJb4rnbAXGJ-:-KguGqbJdJb4rnbAXGJ0:bwwlxcn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/458d163a9736867bf5679aad63d58d23cf9ba30e/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L40)):*
> ```Java
> public class AddVehicleActivity extends ByuActivity {
> 	private final String TAG = AddVehicleActivity.class.getSimpleName();
> 	private TabLayout tabLayout;
> ```

You'll have to explain this pull request to me when I get back :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378)*

**Comment by coreywoodfield** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 40 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378#-KguGqbJdJb4rnbAXGJ-:-KgzXSWskbsHy97xQNA_:b-q8dcos) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/09e7ca702cac0885f9661eca78aa54b0d67333b0/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You'll have to explain this pull request to me when I get back :)
</blockquote></details>

Half of it is cus seth suggested that the buttons be switched for a tab layout, since the buttons required so much logic. The other half is that while I was swapping the buttons for a tab layout I found some other bugs that I fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378)*

**Comment by romrell4** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 108 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378#-Kh2d4QByTuY1CJMN1YG:-Kh2d4QByTuY1CJMN1YH:bnuuo1n) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c52fbf0382ea9f903d5db9850e9870e1e3a3453b/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L108)):*
> ```Java
> 					.show();
> 			isPermanent = false;
> 		} else if (userEligibility.isCanRegisterPerm() && !userEligibility.isCanRegisterTemp()) {
> ```

Explain to me how you got rid of all this logic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378)*

**Comment by coreywoodfield** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 108 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378#-Kh2d4QByTuY1CJMN1YG:-Kh2tATYuVhaYXJkYmD_:b-mn1x7u) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c52fbf0382ea9f903d5db9850e9870e1e3a3453b/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L108)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Explain to me how you got rid of all this logic
</blockquote></details>

I replaced the buttons with tabs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378)*

**Comment by romrell4** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 108 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378#-Kh2d4QByTuY1CJMN1YG:-Kh2woi1qfF_oWrhaiD0:b573023) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c52fbf0382ea9f903d5db9850e9870e1e3a3453b/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L108)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

I replaced the buttons with tabs
</blockquote></details>

I'll be back in the office in an hour. Explain it to me then

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378)*

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 99 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378#-Kh3MKwQwAjHU7BeBODb:-Kh3MKwRsAVqxLBOFbzv:b6ak4lp) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6eee1b04f6f77c62ee360b071fcb077bdaa9630/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L99)):*
> ```Java
> 		if (userEligibility.isCanRegisterTemp()) {
> 			tabLayout.addTab(tabLayout.newTab().setTag(Boolean.FALSE).setText(R.string.temporary_vehicle));
> 			if (!userEligibility.isCanRegisterPerm()) {
> ```

Comment above this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/378#-:-Kh3NtFSN3hvzuBQcVXK:bnfp4nl)*

**Pull request merged**
