### PR TITLE
Added Alumni Connect Activity

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/97)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 74 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXCsFcfV5eco-dNlntQ:-KXCsFcfV5eco-dNlntR:b-g1uw3s) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a8ee9947ec7af2762cf6c6110f7c42d68142e9b4/app/src/main/AndroidManifest.xml#L74)):*
> ```XML
> 			<meta-data
> 				android:name="description"
> 				android:value="Help BYU identify outstanding alumni" />
> ```

Change to match iOS

---

*[app/src/main/AndroidManifest.xml, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXCsK4tKQbliz-KRl6B:-KXCsK4tKQbliz-KRl6C:b-5bk5mi) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a8ee9947ec7af2762cf6c6110f7c42d68142e9b4/app/src/main/AndroidManifest.xml#L77)):*
> ```XML
> 			<meta-data
> 				android:name="featureId"
> 				android:value="alumni" />
> ```

Is this the same as iOS?

---

*[app/src/main/res/layout/alumni_connect_activity.xml, line 16 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXD-ZAjdJWR5P1sQk1p:-KXD-ZAk9gN7BF4SX4T7:b-e32i7z) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/80f12f78e95e5b16ce1affd34c0587695ab04e9c/app/src/main/res/layout/alumni_connect_activity.xml#L16)):*
> ```XML
> 			android:scaleType="centerInside"
> 			android:padding="8dp"
> 			android:src="@drawable/splash_alumni_connect"
> ```

Do the screen percentage here

---

*[app/src/main/res/layout/copyright_activity.xml, line 14 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXD-bUtSE9R6kFnJJDX:-KXD-bUtSE9R6kFnJJDY:boviroy) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/80f12f78e95e5b16ce1affd34c0587695ab04e9c/app/src/main/res/layout/copyright_activity.xml#L14)):*
> ```XML
> 	<ImageView
> 			android:id="@+id/image"
> 			android:layout_width="match_parent"
> ```

Do screen percentage here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97)*

**Comment by coreywoodfield** [comment]
Review status: 5 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 74 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXCsFcfV5eco-dNlntQ:-KXD0VDjwFj0k1bClFbe:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a8ee9947ec7af2762cf6c6110f7c42d68142e9b4/app/src/main/AndroidManifest.xml#L74)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Change to match iOS
</details>
Done.

---

*[app/src/main/AndroidManifest.xml, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXCsK4tKQbliz-KRl6B:-KXD06Nti5yG-Si8Qqm9:b-de2pjo) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a8ee9947ec7af2762cf6c6110f7c42d68142e9b4/app/src/main/AndroidManifest.xml#L77)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Is this the same as iOS?
</details>
no it's the same as v1. i'm pretty sure we haven't been getting the id's from ios, we just get them from v1

---

*[app/src/main/res/layout/alumni_connect_activity.xml, line 16 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXD-ZAjdJWR5P1sQk1p:-KXD1tnGkcyCOEuYy6K3:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/80f12f78e95e5b16ce1affd34c0587695ab04e9c/app/src/main/res/layout/alumni_connect_activity.xml#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Do the screen percentage here
</details>
Done.

---

*[app/src/main/res/layout/copyright_activity.xml, line 14 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXD-bUtSE9R6kFnJJDX:-KXD1uspFRG1V3RmWVfz:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/80f12f78e95e5b16ce1affd34c0587695ab04e9c/app/src/main/res/layout/copyright_activity.xml#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Do screen percentage here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/AndroidManifest.xml, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-KXCsK4tKQbliz-KRl6B:-KXD2_iRqFjbjKTDY-oV:buvoad) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a8ee9947ec7af2762cf6c6110f7c42d68142e9b4/app/src/main/AndroidManifest.xml#L77)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary>
> no it's the same as v1. i'm pretty sure we haven't been getting the id's from ios, we just get them from v1
</details>
I think those match almost 1 for 1. There was only one that was wrong. The reason that we need them to match is so we can have the analytics for both platforms overlap. I'll double check it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/97#-:-KXD2t2EZYykfvNXAbZp:bnfp4nl)*

**Pull request merged**
