### PR TITLE
Fixed bug in PersonDirectory

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/115)

### CODE REVIEW

**Comment by coreywoodfield** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java, line 220 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115#-KZYWp6Q9bPN0oHwRCyn:-KZYWp6Q9bPN0oHwRCyo:b3vhtec) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e11eeb34d4ff237d6029ae32ada6426f8084a1e8/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java#L220)):*
> ```Java
> 					return;
> 				}
> 				showErrorDialog(byuError.getReadableMessage(), null);
> ```

This used to be like this (passing in null as the onClickListener) but then Hammad changed it, and I'm not sure why. It should definitely be null. I think Hammad doesn't realize that showErrorDialog("error", null) is **not** equivalent to showErrorDialog("error"). I'll send him a message explaining that.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java, line 232 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115#-KZYWlUdmFJIYm9ROeAR:-KZYWlUecre_99bVqVV-:b-ma2sz6) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e11eeb34d4ff237d6029ae32ada6426f8084a1e8/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java#L232)):*
> ```Java
> 			enqueueCall(createCall(), new ByuCallback<PersonResponseWrapper>(this) {
> 				@Override
> 				public void onSuccess(Call<PersonResponseWrapper> call, Response<PersonResponseWrapper> response) {
> ```

This part was a bug

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java, line 243 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115#-KZYX8vaMeQ7t_RywnCX:-KZYX8vaMeQ7t_RywnCY:b-tfebj9) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e11eeb34d4ff237d6029ae32ada6426f8084a1e8/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java#L243)):*
> ```Java
> 				@Override
> 				public void onFailure(Call<PersonResponseWrapper> call, ByuError byuError) {
> 					showErrorDialog(byuError.getReadableMessage(), null); // Don't kick them out
> ```

This is also just me reverting a change that Hammad made

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java, line 244 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115#-KZYXAsmiGRo4gva53T8:-KZYXAsmiGRo4gva53T9:bucrl1s) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e11eeb34d4ff237d6029ae32ada6426f8084a1e8/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java#L244)):*
> ```Java
> 				public void onFailure(Call<PersonResponseWrapper> call, ByuError byuError) {
> 					showErrorDialog(byuError.getReadableMessage(), null); // Don't kick them out
> 					personAdapter.remove(personAdapter.getItemCount() - 1); // But don't try to load any more data
> ```

This is new - it seemed like a good idea

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115)*

**Comment by romrell4** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java, line 232 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115#-KZYWlUdmFJIYm9ROeAR:-KZbfh4n0TSFNcnUupOi:b-x4v25p) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e11eeb34d4ff237d6029ae32ada6426f8084a1e8/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java#L232)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

This part was a bug
</blockquote></details>

How was this a bug? It looks like you just inlined a variable...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java, line 232 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115#-KZYWlUdmFJIYm9ROeAR:-KZbfzkHBozylHI6-KJ7:b8p7snt) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e11eeb34d4ff237d6029ae32ada6426f8084a1e8/app/src/main/java/edu/byu/suite/features/personDirectory/controller/PersonDirectoryMainActivity.java#L232)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

How was this a bug? It looks like you just inlined a variable...
</blockquote></details>

Yes, that fixes the bug. What was happening was that we saved the index of the last position in the list (where `null` was) and then we added everything before that position. Then we tried to take out `null` by removing from the index where `null` *had* been before we inserted stuff. but `null` wasn't there anymore so it wasn't behaving as expected, and the app crashed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/115#-:-KZbgWBZGfFhAS4zLLgq:bnfp4nl)*

**Pull request merged**
