### PR TITLE
Fixed stuff

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/93)

### CODE REVIEW

**Comment by coreywoodfield** [comment]
Pretty sure everything works - I can't test class rolls, as I'm not an instructor, or Map My Classes, as maps are still broken, but I'm pretty sure I didn't break anything

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-:-KWeV2f1sr2I52whCq29:bd8e566)*

**Comment by romrell4** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java, line 79 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWisa3fujm5fdglae0T:-KWisa3fujm5fdglae0U:b-oljulb) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/85d6881a1167b0c9d4fd49e4c1171f83dd57d9a9/app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java#L79)):*
> ```Java
> 				 * action needs to be ignored.
> 				 */
> 				if (!ignoreOnItemSelectedFlag) {
> ```

Why did you get rid of this? Did you fix the double call issue?

---

*[app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java, line 109 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitROrwY3C9ARY86Kp:-KWitROrwY3C9ARY86Kq:b-w2ut5q) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/85d6881a1167b0c9d4fd49e4c1171f83dd57d9a9/app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java#L109)):*
> ```Java
> 				} else {
> 					showErrorDialog(CLASS_NOT_FOUND_MESSAGE, null);
> 					spinner.setSelection(oldSemesterPosition);
> ```

Why could you remove this?

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java, line 76 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitfdAmdTIUDM4Q9x5:-KWitfdAmdTIUDM4Q9x6:b-6s7qrg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c25e62bd480659ee5ce8029b3038e46cd12a83b8/app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java#L76)):*
> ```Java
> 		getMenuInflater().inflate(R.menu.dropdown_spinner_menu, menu);
> 		spinner = (Spinner) menu.findItem(R.id.dropdown_spinner_menu_item).getActionView();
> 		spinnerAdapter = SpinnerUtils.setupAdapter(this, spinner, yearTerms);
> ```

Capitalize "up" (like in the other function)

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java, line 103 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitmdlTUzOmaAuoUpf:-KWitmdlTUzOmaAuoUpg:b9v5uor) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/85d6881a1167b0c9d4fd49e4c1171f83dd57d9a9/app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java#L103)):*
> ```Java
> 
> 	@Override
> 	public boolean onOptionsItemSelected(MenuItem item) {
> ```

Why could we remove this?

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/MyLotsActivity.java, line 133 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitrH6ifM5gXmQZ6br:-KWitrH6ifM5gXmQZ6bs:b-a28fi2) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c25e62bd480659ee5ce8029b3038e46cd12a83b8/app/src/main/java/edu/byu/suite/features/parking/controller/MyLotsActivity.java#L133)):*
> ```Java
> 			//Display dialog with lot choices. Make choices clickable.
> 			if (lotTypeDescriptions != null) {
> 				ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, R.layout.default_simple_list_item_centered, lotTypeDescriptions);
> ```

Do you have to have the second one? I thought Java 8 assumes it...

---

*[support/src/main/java/edu/byu/support/utils/SpinnerUtils.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWiuXhSL6nTgyASJmbX:-KWiuXhSL6nTgyASJmbY:b-xjjkry) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c25e62bd480659ee5ce8029b3038e46cd12a83b8/support/src/main/java/edu/byu/support/utils/SpinnerUtils.java#L18)):*
> ```Java
> import retrofit2.Response;
> 
> import java.util.List;
> ```

Does this not allow passing in a callback anymore? Why not?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r2.
Review status: 9 of 76 files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWjPxXbOtOgqidT-spz:-KWjPxXczWaLRVWK5jUa:b-ll9eb4) (no related file):*
Add param to Util

---

*[app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java, line 109 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitROrwY3C9ARY86Kp:-KWjMPfk1tgFWgOqDxA1:b-p4jp5o) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/85d6881a1167b0c9d4fd49e4c1171f83dd57d9a9/app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java#L109)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Why could you remove this?
</details>
Use ViewSwitcher

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93)*

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r2, 47 of 66 files at r3, 22 of 22 files at r4, 1 of 6 files at r5.
Review status: 75 of 80 files reviewed at latest revision, 4 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 169 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWjXoBB4l6dYBcU2tIu:-KWjXoBB4l6dYBcU2tIv:b-dacdb0) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0f012274aa113c4d9436c3e4e2968e1d22fb475b/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L169)):*
> ```Java
> 	public void onCreate(Bundle savedInstanceState) {
> 		super.onCreate(savedInstanceState);
> //		GoogleApiClient.Builder builder = new GoogleApiClient.Builder(getActivity(), this, this);
> ```

Figure out your business

---

*[support/src/main/java/edu/byu/support/utils/SpinnerUtils.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWiuXhSL6nTgyASJmbX:-KWjY5r-M2ZJ2hy24TyD:ba70f55) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c25e62bd480659ee5ce8029b3038e46cd12a83b8/support/src/main/java/edu/byu/support/utils/SpinnerUtils.java#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Does this not allow passing in a callback anymore? Why not?
</details>
You gonna fix this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93)*

**Comment by coreywoodfield** [comment]
Review status: 75 of 80 files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java, line 109 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitROrwY3C9ARY86Kp:-KWjVzbM3gApCdHDuyZ2:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/85d6881a1167b0c9d4fd49e4c1171f83dd57d9a9/app/src/main/java/edu/byu/suite/features/classRolls/controller/ClassRollsMainActivity.java#L109)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Use ViewSwitcher
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java, line 76 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitfdAmdTIUDM4Q9x5:-KWjWJgru1DIV36gg2eR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c25e62bd480659ee5ce8029b3038e46cd12a83b8/app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java#L76)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Capitalize "up" (like in the other function)
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java, line 103 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitmdlTUzOmaAuoUpf:-KWjWL5hQu0KMaBrl-FB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/85d6881a1167b0c9d4fd49e4c1171f83dd57d9a9/app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java#L103)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Why could we remove this?
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/MyLotsActivity.java, line 133 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWitrH6ifM5gXmQZ6br:-KWjWMJLHwwA5QnHUf60:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c25e62bd480659ee5ce8029b3038e46cd12a83b8/app/src/main/java/edu/byu/suite/features/parking/controller/MyLotsActivity.java#L133)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Do you have to have the second one? I thought Java 8 assumes it...
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93)*

**Comment by romrell4** [comment]
Reviewed 5 of 6 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93)*

**Comment by coreywoodfield** [comment]
Review status: 75 of 80 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWjPxXbOtOgqidT-spz:-KWjbBxZcbLuedKyZSDO:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Add param to Util
</details>
Done.

---

*[support/src/main/java/edu/byu/support/utils/SpinnerUtils.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWiuXhSL6nTgyASJmbX:-KWjbEZ4Ua0qcpULlbJX:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c25e62bd480659ee5ce8029b3038e46cd12a83b8/support/src/main/java/edu/byu/support/utils/SpinnerUtils.java#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> You gonna fix this?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93)*

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/utils/SpinnerUtils.java, line 58 at r6](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-KWjeTbIBWOj4kYJbTVq:-KWjeTbIBWOj4kYJbTVr:b-j1q3p8) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7fabe71e2ea209fa8be5bd8ec28856dd38d56d5d/support/src/main/java/edu/byu/support/utils/SpinnerUtils.java#L58)):*
> ```Java
> 	private final static String ERROR_MESSAGE = "Error Loading Year Terms.";
> 
> 	public static ArrayAdapter<YearTerm> setUpAdapterWithYearTerms(final ByuActivity activity, final Spinner spinner, @Nullable final OnItemSelectedListener onItemSelectedListener) {
> ```

It feels like these two functions have a lot of duplicate code. Is there a way to make this a pass through?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/93#-:-KWn2xKyqnONAaokdSg4:bnfp4nl)*

**Pull request merged**
