### PR TITLE
Hotfix/bugs

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/133)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXGIISAkAA4MM-WgtR:-KbXGIISAkAA4MM-WgtS:b-4etscb) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L77)):*
> ```Java
> 			public void onFailure(Call<List<Event>> call, ByuError byuError) {
> 				showErrorDialog(byuError.getReadableMessage(), null);
> 				adapter.stopLoading();
> ```

Put comment about why we don't kick them out anymore

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 123 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXKMwwrJn5DF7-vOxc:-KbXKMwwrJn5DF7-vOxd:bhj1q8l) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L123)):*
> ```Java
> 			public void onFailure(Call<TransactionWrapper> call, ByuError byuError) {
> 				dismissProgressDialog();
> 				showErrorDialog(byuError.getReadableMessage(), null);
> ```

If we aren't going to kick them out, add an empty text thingy

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 86 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXKqK69JHXTxk25vdc:-KbXKqK69JHXTxk25vdd:bz91lpv) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L86)):*
> ```Java
> 
> 	public LearningSuiteClient.Api getApi() {
> 		if (api == null) {
> ```

Figure out the answer or
Put a TODO

---

*[support/src/main/java/edu/byu/support/adapter/LoadingAdapter.java, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXM9kSXA8eVBtCUvsH:-KbXM9kSXA8eVBtCUvsI:bi87ub7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/support/src/main/java/edu/byu/support/adapter/LoadingAdapter.java#L16)):*
> ```Java
> 
> public abstract class LoadingAdapter<DataType> extends ByuRecyclerAdapter<DataType> {
> 	private static final int LOADING = 0;
> ```

rename to something about view_type

---

*[support/src/main/java/edu/byu/support/adapter/LoadingAdapter.java, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXMUqVgFZ8BbKZOFAV:-KbXMUqVgFZ8BbKZOFAW:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/support/src/main/java/edu/byu/support/adapter/LoadingAdapter.java#L58)):*
> ```Java
> 		} else {
> 			addAllToList(getItemCount() - 1, page);
> 			notifyItemChanged(getItemCount() - 1);
> ```

Comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133)*

**Comment by coreywoodfield** [comment]
Review status: 14 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXGIISAkAA4MM-WgtR:-KbXNMYxshhDYZenWYC6:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L77)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put comment about why we don't kick them out anymore
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 123 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXKMwwrJn5DF7-vOxc:-KbXNlymEdvHLAV5dIhM:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L123)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

If we aren't going to kick them out, add an empty text thingy
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java, line 86 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXKqK69JHXTxk25vdc:-KbXO0cQIgqNv0dJHTap:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/app/src/main/java/edu/byu/suite/features/learningSuite/activity/CourseDetailActivity.java#L86)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Figure out the answer or
Put a TODO
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/adapter/LoadingAdapter.java, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXM9kSXA8eVBtCUvsH:-KbXODMRIe581eHq-wJK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/support/src/main/java/edu/byu/support/adapter/LoadingAdapter.java#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

rename to something about view_type
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/adapter/LoadingAdapter.java, line 58 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-KbXMUqVgFZ8BbKZOFAV:-KbXOn5WjXFPau3VJ9Ge:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cf4d0f2dd79d96428a7846242afb316a6d45aac6/support/src/main/java/edu/byu/support/adapter/LoadingAdapter.java#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/133#-:-KbXSIvHQwBY3Av1MgOc:bnfp4nl)*

**Pull request merged**
