### PR TITLE
Add lowScoresToDrop message to assignments in LS: closes #216

### LINKED ISSUE #216: LearningSuite dropped scores
Add "Lowest score is dropped" to sections

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/315)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java, line 62 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KeorxXGMLBH9LNrQGZQ:-KeorxXGMLBH9LNrQGZR:b-7moe6) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/119ca2f043f8f2d5d57a377b2bc34b868d416213/support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java#L62)):*
> ```Java
> 		public void bind(Header data, ByuClickListener<Header> listener) {
> 			textView.setText(data.text);
> 			if (data.detailText != null) {
> ```

Is there a way we use detail text rather than just adding it to the textView?

---

*[support/src/main/res/layout/default_list_item_header_bold_detail.xml, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-Keos7mKAz2JqV3lTyj4:-Keos7mKAz2JqV3lTyj5:b2vza7a) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/119ca2f043f8f2d5d57a377b2bc34b868d416213/support/src/main/res/layout/default_list_item_header_bold_detail.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

Probably don't need this if we concatenate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java, line 62 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KeorxXGMLBH9LNrQGZQ:-KepF2TrEX7OMSGdCihs:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/119ca2f043f8f2d5d57a377b2bc34b868d416213/support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java#L62)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is there a way we use detail text rather than just adding it to the textView?
</blockquote></details>

Done.

---

*[support/src/main/res/layout/default_list_item_header_bold_detail.xml, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-Keos7mKAz2JqV3lTyj4:-KepF2qO1i4EyZN8ffT5:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/119ca2f043f8f2d5d57a377b2bc34b868d416213/support/src/main/res/layout/default_list_item_header_bold_detail.xml#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Probably don't need this if we concatenate
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315)*

**Comment by romrell4** [comment]
Reviewed 1 of 4 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java, line 82 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFCEPml_50wJZPNnE:-KepFCEPml_50wJZPNnF:bbtbfo9) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java#L82)):*
> ```Java
> 					headerBuilder.setSpan(new ForegroundColorSpan(ContextCompat.getColor(getActivity(), R.color.textLight)), category.getTitle().length(), headerText.length(), Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
> 				} else {
> 					headerText = category.getTitle();
> ```

You can do this outside of the if/else, then you can just append in the if. Does that make sense?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315)*

**Comment by romrell4** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/restrooms/fragment/RestroomListFragment.java, line 53 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFS7XdYkM3AnuTkVs:-KepFS7XdYkM3AnuTkVt:bkkun0b) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/app/src/main/java/edu/byu/suite/features/restrooms/fragment/RestroomListFragment.java#L53)):*
> ```Java
> 		for (int i = 0; i < rooms.size(); i++) {
> 			if (i != 0) {
> 				data.add(new HeaderAdapter.Header(""));
> ```

Why did we change this? I'm totally okay with it, just wondering

---

*[support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java, line 76 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFkdsvkvCrk6-KEVs:-KepFkdsvkvCrk6-KEVt:bt5xzi0) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java#L76)):*
> ```Java
> 		}
> 
> 		public SpannableStringBuilder getText() {
> ```

Is there a reason you pass back a builder? Should you just return the Spannable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java, line 82 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFCEPml_50wJZPNnE:-KepGNjN3tNZmt_3uAA2:b-fr10if) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java#L82)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can do this outside of the if/else, then you can just append in the if. Does that make sense?
</blockquote></details>

Oh cool! Does this work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java, line 82 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFCEPml_50wJZPNnE:-KepFjmDYgpKOUqnmviF:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java#L82)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You can do this outside of the if/else, then you can just append in the if. Does that make sense?
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/restrooms/fragment/RestroomListFragment.java, line 53 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFS7XdYkM3AnuTkVs:-KepGDneIV307Z7PvRU1:b-mvw7at) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/app/src/main/java/edu/byu/suite/features/restrooms/fragment/RestroomListFragment.java#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did we change this? I'm totally okay with it, just wondering
</blockquote></details>

For some reason it was throwing an error after I made the constructor to append the String to the SpannableStringBuilder. No idea why it wouldn't work (even after I added a null check to the constructor). Rather than get tangled trying to figure it out, I just made it an empty String. I've tested it and it works fine.

---

*[support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java, line 76 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFkdsvkvCrk6-KEVs:-KepGhc-kaX3w6glGb3r:bp3mt60) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java#L76)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is there a reason you pass back a builder? Should you just return the Spannable?
</blockquote></details>

Not sure. It works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java, line 76 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFkdsvkvCrk6-KEVs:-KepHDZd0ORYrpTy_YZm:b-i1uaqt) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java#L76)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Not sure. It works.
</blockquote></details>

Lol. @coreywoodfield could you look at this? I'm not sure if a SpannableStringBuilder is the correct data type to return

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java, line 76 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-KepFkdsvkvCrk6-KEVs:-KepWPwS3zL5b4juCsgy:b-ecra06) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ea926afbd246358c83713113da35b629e8d8d85a/support/src/main/java/edu/byu/support/adapter/HeaderAdapter.java#L76)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Lol. @coreywoodfield could you look at this? I'm not sure if a SpannableStringBuilder is the correct data type to return
</blockquote></details>

A SpannableStringBuilder is a Spannable, and there's no way to get a Spannable different from itself from it. This seems to be the correct way to use it. And if it ain't broke, don't fix it ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/315#-:-Kesnza38VRHEdwQRUem:bnfp4nl)*

**Pull request merged**
