### PR TITLE
Feature/calendars

### PR DESCRIPTION
**Pull request by coreywoodfield**
it's not quite done (we need to figure out why the time zone stuff isn't working) but everything else is pretty much done if you want to start looking at it

---
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/73)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[gradle.properties, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzEztfDSKkMmWJBqG:-KTzzEztfDSKkMmWJBqH:b-ze3zef) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/gradle.properties#L21)):*
> ```INI
> 
> android.enableBuildCache=true
> org.gradle.jvmargs=-Xmx1536M
> ```

Put a comment here :)

---

*[app/src/main/AndroidManifest.xml, line 377 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzGq5ukzkD3UApWxS:-KTzzGq5ukzkD3UApWxT:b-89817p) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/AndroidManifest.xml#L377)):*
> ```XML
> 					android:name="featureId"
> 					android:value="calendars" />
> 			
> ```

Do it

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 94 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-17SiCDlZ2BPwsP69:-KU-17SiCDlZ2BPwsP6A:b-2l4t18) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L94)):*
> ```Java
> 			@Override
> 			public void bind(Event data, ByuClickListener<Event> listener) {
> 				text.setText(data.getSummary());
> ```

Comments in here

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 103 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-1v_SEZMBlOIoleb0:-KU-1v_TBjHPMYnzeZ1w:b-owqtn6) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L103)):*
> ```Java
> 			@StringRes
> 			private int getDateFormat(Event event) {
> 				return event.isAllDay()
> ```

Comment here for each case

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-0Ta7VFn1yPzcbf-M:-KU-0Ta7VFn1yPzcbf-N:b-p4lx0b) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L26)):*
> ```Java
> 
> public class CalendarsMainActivity extends ByuActivity {
> 	private static final List<Calendar> CALENDARS = Arrays.asList(
> ```

[self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"All", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Academics", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/4", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Alumni", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/5", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Arts & Entertainment", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/9", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Athletics & Recreation", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/10", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Conferences & Camps", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/6", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Devotionals & Forums", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/7", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Employment & Careers", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/46", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Health & Wellness", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/47", @"url",
                           nil]];
    [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
                           @"Service & Clubs", @"name",
                           @"webcal://calendar.byu.edu/iCal/Export/49", @"url",
                           nil]];

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 34 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-2E9LZJK7sMRwC6by:-KU-2E9LZJK7sMRwC6bz:b-jxc2l0) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L34)):*
> ```Java
> 		ViewUtils.setTextOrHide((TextView) findViewById(R.id.event_location), findViewById(R.id.event_location_row), event.getLocation());
> 		if (event.isAllDay()) {
> 			((TextView) findViewById(R.id.date_header)).setText("Date:");
> ```

Pull it out. Also comments

---

*[app/src/main/res/values/strings.xml, line 182 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-1dQMT3Nvq61V_U3e:-KU-1dQMT3Nvq61V_U3f:b4umk52) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/res/values/strings.xml#L182)):*
> ```XML
> 
> 	
> 	
> ```

Put everything that you learned about the formats here

---

*[support/src/main/java/edu/byu/support/ByuConstants.java, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzfr3od3eyL8gnPEU:-KTzzfr3od3eyL8gnPEV:b-6nzv6e) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/support/src/main/java/edu/byu/support/ByuConstants.java#L17)):*
> ```Java
> 	public static final String SUBTITLE = "subtitle";
> 
> 	public static final TimeZone TIME_ZONE = TimeZone.getTimeZone("America/Denver");
> ```

Remove this?

---

*[support/src/main/res/layout/default_list_item_detail_below_indicator2.xml, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzy98hZ_DLPdIrQD2:-KTzzy98hZ_DLPdIrQD3:bv0cmoa) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/support/src/main/res/layout/default_list_item_detail_below_indicator2.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

Put this in your own feature's res

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[gradle.properties, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzEztfDSKkMmWJBqG:-KU-4k_n5Vo303Mowuxj:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/gradle.properties#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Put a comment here :)
</details>
Done.

---

*[app/src/main/AndroidManifest.xml, line 377 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzGq5ukzkD3UApWxS:-KU-5ahp4fKNwrZH0I6S:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/AndroidManifest.xml#L377)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Do it
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 94 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-17SiCDlZ2BPwsP69:-KU-634mTFWkuLTjVfYk:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L94)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comments in here
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 103 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-1v_SEZMBlOIoleb0:-KU-68sUZduxmvDLYQgW:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L103)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment here for each case
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 34 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-2E9LZJK7sMRwC6by:-KU-ANEEX2GZYKAI9JR-:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Pull it out. Also comments
</details>
Done.

---

*[app/src/main/res/values/strings.xml, line 182 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-1dQMT3Nvq61V_U3e:-KU-AO0s-roTJBpKRKvO:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/res/values/strings.xml#L182)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Put everything that you learned about the formats here
</details>
Done.

---

*[support/src/main/java/edu/byu/support/ByuConstants.java, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzfr3od3eyL8gnPEU:-KU-AQQSRC7TbJjUpMNs:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/support/src/main/java/edu/byu/support/ByuConstants.java#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove this?
</details>
Done.

---

*[support/src/main/res/layout/default_list_item_detail_below_indicator2.xml, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzy98hZ_DLPdIrQD2:-KU-ASikXn8C3j8UiTI8:b-glngd9) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/support/src/main/res/layout/default_list_item_detail_below_indicator2.xml#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Put this in your own feature's res
</details>
Is there any harm to leaving it in support? I don't think it's so implausible that another feature someday needs a default row that has two rows of detail text

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by coreywoodfield** [comment]
Review status: 13 of 19 files reviewed at latest revision, 9 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-0Ta7VFn1yPzcbf-M:-KU-E2WDl3Qe3VbOx-_W:b-dw6jnr) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"All", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Academics", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/4", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Alumni", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/5", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Arts & Entertainment", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/9", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Athletics & Recreation", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/10", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Conferences & Camps", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/6", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Devotionals & Forums", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/7", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Employment & Careers", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/46", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Health & Wellness", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/47", @"url",
>                            nil]];
>     [self.items addObject:[NSDictionary dictionaryWithObjectsAndKeys:
>                            @"Service & Clubs", @"name",
>                            @"webcal://calendar.byu.edu/iCal/Export/49", @"url",
>                            nil]];
</details>
I tried and those all gave me 404s

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-0Ta7VFn1yPzcbf-M:-KU3fXmSta5n4oCIUsHm:bad5zcb) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L26)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary>
> I tried and those all gave me 404s
</details>
They should work with https instead of webcal

---

*[support/src/main/res/layout/default_list_item_detail_below_indicator2.xml, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzy98hZ_DLPdIrQD2:-KU3g0DMnnMn5vwKrPQP:bqrzuk) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/support/src/main/res/layout/default_list_item_detail_below_indicator2.xml#L1)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary>
> Is there any harm to leaving it in support? I don't think it's so implausible that another feature someday needs a default row that has two rows of detail text
</details>
Let's move it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by coreywoodfield** [comment]
Review status: 17 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU-0Ta7VFn1yPzcbf-M:-KU3k2WFty7gJkF-bJSC:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> They should work with https instead of webcal
</details>
Done.

---

*[support/src/main/res/layout/default_list_item_detail_below_indicator2.xml, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KTzzy98hZ_DLPdIrQD2:-KU3lFj_sDct7lrqqnvq:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/468589af015dee9a4b39aef5ff83dcd5ffd6c0f5/support/src/main/res/layout/default_list_item_detail_below_indicator2.xml#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Let's move it
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU3q3TTxHrDWcE_hiaC:-KU3q3TTxHrDWcE_hiaD:b-k2py22) (no related file):*
Reload data in three month incremenets

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU3q3TTxHrDWcE_hiaC:-KU4LvBhff8xU2nDUuxT:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Reload data in three month incremenets
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU3q3TTxHrDWcE_hiaC:-KU4ObGfHNL8BtQCDe_J:b-x0leza) (no related file):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary>
> Done.
</details>
Extract out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by coreywoodfield** [comment]
Review status: 20 of 21 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-KU3q3TTxHrDWcE_hiaC:-KUTcIBT8Nn-_vG44eK4:bu52j7o) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Extract out
</details>
Turns out it's not as easy as I expected and would involve logic in multiple classes being extracted into multiple other classes (the recycler view and the recycler adapter) and there would be logic that just can't be extracted well. I think it'll make the most sense if we just leave them there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by romrell4** [comment]
Reviewed 3 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73)*

**Comment by romrell4** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/73#-:-KUU12NybdA6PV7dSJbw:bnfp4nl)*

**Pull request merged**
