### PR TITLE
Feature/settings

### PR DESCRIPTION
**Pull request by cwoodfie**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/54)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 23 of 37 files at r1.
Review status: 23 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivity.java, line 75 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZHCaNGQh087ub4WyJ:-KRZHCaNGQh087ub4WyK:b-vrc4x3) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3312f2443fb4a136ee2034ae7d7858774b8b0471/app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivity.java#L75)):*
> ```Java
> 	}
> 
> 	private void loadFeatures() {
> ```

Don't do this. Keep it private

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Review status: 23 of 37 files reviewed at latest revision, all discussions resolved.

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivity.java, line 75 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZHCaNGQh087ub4WyJ:-KRZHuAKyHG7XlRdtTSE:b-125mzs) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/3312f2443fb4a136ee2034ae7d7858774b8b0471/app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivity.java#L75)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Don't do this. Keep it private
</details>
By the way, this is just a test. Don't worry about making this change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Reviewed 2 of 37 files at r1.
Review status: 25 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Reviewed 2 of 37 files at r1.
Review status: 27 of 37 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java, line 62 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZJ7dsbK38XJOf9LDt:-KRZJ7dsbK38XJOf9LDu:b3b5sq2) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java#L62)):*
> ```Java
> 		return new AlertDialog.Builder(getActivity()).setTitle(String.format(Locale.US, "What's New - Version %s", ByuConstants.getVersionName(getActivity())))
> 													 .setView(dialog)
> 													 .setNeutralButton("Close", (dialogInterface, i) -> ((FavoritesActivity) getActivity()).loadFeatures())
> ```

What is this one doing? We change to using a different lambda?

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java, line 116 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZJZ3nnLv8INAZlCEb:-KRZJZ3nnLv8INAZlCEc:b2ngtjn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java#L116)):*
> ```Java
> 		}
> 
> 		List<Object> data = new ArrayList<>(newApps.size() + updatedApps.size() + 2);
> ```

+2?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Reviewed 6 of 37 files at r1.
Review status: 33 of 37 files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/res/layout/whats_new_app_view.xml, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZK8NTL9bf1g__9xX0:-KRZK8NTL9bf1g__9xX1:bvnupyo) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/res/layout/whats_new_app_view.xml#L12)):*
> ```XML
> 			android:layout_alignParentStart="true"
> 			android:layout_width="60dp"
> 			android:layout_height="60dp"
> ```

Let's put this value into a dimensions file (It might already be there since we use the feature images so often)

---

*[app/src/main/res/values/strings.xml, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZKRJtD7M4uHICN8VB:-KRZKRJuFDooNe5PHxJy:bluhrl9) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/res/values/strings.xml#L19)):*
> ```XML
> 	<string name="whatsNewMenuItemText">What\'s New</string>
> 	<string name="new_apps">New Apps</string>
> 	<string name="changed_apps">Changed Apps</string>
> ```

"Features" instead of "Apps". Make sure this is consistent in your code too.

---

*[support/src/main/AndroidManifest.xml, line 11 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZKcaUW-cW60PcpY-o:-KRZKcaUW-cW60PcpY-p:b-1ei2bg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/support/src/main/AndroidManifest.xml#L11)):*
> ```XML
> 	-->
> 
> 	<uses-feature android:name="android.hardware.screen.portrait"/>
> ```

Did we decide that we were going to use this? I can't remember

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 56 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZQ28YZdO1T_AJsFYq:-KRZQ28YZdO1T_AJsFYr:bh35pvr) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/support/src/main/java/edu/byu/support/login/LoginActivity.java#L56)):*
> ```Java
> 	protected void onCreate(Bundle icicle) {
> 		super.onCreate(icicle);
> 		setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
> ```

Is this needed if we already add the stuff to the manifest?

---

*[support/src/main/res/layout/login_activity.xml, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZQEiK9vZ_yoiaKPKd:-KRZQEiK9vZ_yoiaKPKe:buhsvna) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/support/src/main/res/layout/login_activity.xml#L12)):*
> ```XML
> 			android:id="@+id/toolbar" />
> 
> 	<ScrollView
> ```

What's up with the scroll view?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Reviewed 4 of 37 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java, line 62 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZJ7dsbK38XJOf9LDt:-KR_Oz4CiriCmjJnqCa0:b3k95m0) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java#L62)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> What is this one doing? We change to using a different lambda?
</details>
Have you done it yet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/assets/db/version-history/data/63.json, line 4 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KR_PrKqYm70KkwQm10I:-KR_PrKqYm70KkwQm10J:b-dnmq52) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/assets/db/version-history/data/63.json#L4)):*
> ```JSON
>   "suite_version": [
>     {
>       "version_num": 63,
> ```

Update to be 69 (after copying all other versions as well from v1 master)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Reviewed 1 of 37 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by cwoodfie** [comment]
Review status: 36 of 43 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/assets/db/version-history/data/63.json, line 4 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KR_PrKqYm70KkwQm10I:-KR_dRiuWhBux3zudBSO:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/assets/db/version-history/data/63.json#L4)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Update to be 69 (after copying all other versions as well from v1 master)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by romrell4** [comment]
Reviewed 6 of 7 files at r2, 1 of 2 files at r3.
Review status: 42 of 44 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by cwoodfie** [comment]
Review status: 41 of 44 files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java, line 62 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZJ7dsbK38XJOf9LDt:-KR_dZWM0SFVeA-jgPzB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java#L62)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Have you done it yet?
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java, line 116 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZJZ3nnLv8INAZlCEb:-KR_d_gP_8TYUgiWt9d_:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/java/edu/byu/suite/mainScreen/controller/WhatsNewDialog.java#L116)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> +2?
</details>
Done.

---

*[app/src/main/res/layout/whats_new_app_view.xml, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZK8NTL9bf1g__9xX0:-KR_dqQhE9HrAIxVz49G:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/res/layout/whats_new_app_view.xml#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Let's put this value into a dimensions file (It might already be there since we use the feature images so often)
</details>
Done.

---

*[app/src/main/res/values/strings.xml, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZKRJtD7M4uHICN8VB:-KR_eIuodkey6VtthFYm:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/app/src/main/res/values/strings.xml#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> "Features" instead of "Apps". Make sure this is consistent in your code too.
</details>
Done.

---

*[support/src/main/res/layout/login_activity.xml, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-KRZQEiK9vZ_yoiaKPKd:-KR_eMdOd2sTTd7bX6rV:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2f9de44d4ab7a60ba2293aa800d3c36df94786db/support/src/main/res/layout/login_activity.xml#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> What's up with the scroll view?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Comment by cwoodfie** [comment]
:lgtm:

---

Review status: 41 of 44 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54#-:-KR_ei5zH8WUGyJGnyL2:bnfp4nl)*

**Comment by romrell4** [comment]
Reviewed 1 of 7 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/54)*

**Pull request merged**
