### PR TITLE
Feature/gro

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/121)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 68 of 68 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kUEThvL1Gkgk8dx0f:-K_kUEThvL1Gkgk8dx0g:baqyduu) (no related file):*
Make FavoritesActivity singleTop

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kUJjkI6Xn-qe5ogPz:-K_kUJjkI6Xn-qe5ogQ-:b-mern3c) (no related file):*
Look into making static variables for all visibleFeatures, categories, favorites, what's new, etc

---

*[app/src/main/java/edu/byu/suite/mainScreen/AddFeatureActivity.java, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kOxdlRMjX6_rkaaHM:-K_kOxdlRMjX6_rkaaHN:b-83q21o) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/AddFeatureActivity.java#L15)):*
> ```Java
> import edu.byu.support.fragment.ByuFragment;
> 
> public class AddFeatureActivity extends ByuActivity {
> ```

Change to AddFeatures

---

*[app/src/main/java/edu/byu/suite/mainScreen/AllFeaturesFragment.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kQ0-3WGvibv_kBUHo:-K_kQ0-3WGvibv_kBUHp:b62nn0k) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/AllFeaturesFragment.java#L41)):*
> ```Java
> 		adapter = new FeatureRecyclerAdapter(null, FeatureDisplayMode.ALL, getActivity());
> 		adapter.setByuClickListener((data, view1, position) -> startActivity(new Intent(getActivity(), FeatureDetailActivity.class).putExtra(CategoryActivity.FEATURE, data)));
> ```

Remove spaces

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kUgvTGO-UOfsGrVVI:-K_kUgvTGO-UOfsGrVVJ:b-g2wh60) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L78)):*
> ```Java
> 		} else {
> 			showProgressDialog();
> 			Log.d(TAG, "onCreate: initializing loader");
> ```

Remove this (when it's working)

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 177 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kVAuNimsvdsHKTHty:-K_kVAuNimsvdsHKTHtz:b-kcqx1e) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L177)):*
> ```Java
> 		Bundle args = new Bundle();
> 		args.putBoolean(LOGGING_OUT, true);
> 		getLoaderManager().restartLoader(0, args, this);
> ```

put in psf

---

*[app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java, line 33 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kWOofxfGGT4NEDtch:-K_kWOofxfGGT4NEDtci:bgmm234) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java#L33)):*
> ```Java
>  * Created by cwoodfie on 7/11/16.
>  */
> public class WhatsNewDialog extends DialogFragment implements LoaderManager.LoaderCallbacks {
> ```

Let's get a ton of comments in here... It feels like reading a foreign language...

---

*[support/src/main/java/edu/byu/support/feature/FeatureLoader.java, line 48 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kX7-08kLgTwDxYh2j:-K_kX7-08kLgTwDxYh2k:bsplabw) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeatureLoader.java#L48)):*
> ```Java
> 		super(context);
> 		this.loggingOut = loggingOut;
> 		Log.d(TAG, "FeatureLoader: constructor " + this);
> ```

Remove tags when we're done

---

*[support/src/main/java/edu/byu/support/feature/FeatureLoader.java, line 76 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kZTaZmxQStkiG3l8C:-K_kZTa_1BeKxs1FmCpS:b-ut8hf7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeatureLoader.java#L76)):*
> ```Java
> 
> 		FeaturesWrapper featuresWrapper = new FeaturesWrapper();
> 		loadAllFeatures(featuresWrapper);
> ```

Let's rename this to populateAllFeatures

---

*[support/src/main/java/edu/byu/support/feature/FeatureLoader.java, line 145 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kZrj5Nj20AAhDRgSw:-K_kZrj5Nj20AAhDRgSx:b8oyp16) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeatureLoader.java#L145)):*
> ```Java
> 		for (Feature feature : allFeatures) {
> 			if (feature.getGroGroup() == null) {
> 				featuresWrapper.idToFeatureMap.put(feature.getId(), feature);
> ```

Rename to idToVisibleFeatureMap

---

*[support/src/main/java/edu/byu/support/feature/FeaturesWrapper.java, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kQwiU4N5dhbBApGLu:-K_kQwiU4N5dhbBApGLv:buc3kym) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeaturesWrapper.java#L14)):*
> ```Java
>  */
> public class FeaturesWrapper {
> 	Map<String, Feature> idToFeatureMap;
> ```

private

---

*[support/src/main/java/edu/byu/support/feature/FeaturesWrapper.java, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kRCj5HInTo_w_oml5:-K_kRCj5HInTo_w_oml6:bwikrpv) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeaturesWrapper.java#L39)):*
> ```Java
> 	}
> 
> 	public List<Feature> getFavorites(FavoritesUtil favoritesUtil) {
> ```

Rename FavoritesManager

---

*[support/src/main/java/edu/byu/support/login/internal/authenticator/clients/gro/GroGroupClient.java, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kRZJD2BFTgD70g-MO:-K_kRZJD2BFTgD70g-MP:b7lgbkc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/login/internal/authenticator/clients/gro/GroGroupClient.java#L21)):*
> ```Java
> 
> 	@Override
> 	public ByuApiGenerator.AuthType getAuthType() {
> ```

Look into the other way

---

*[support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_ka7w_bJL2KCS-5FMk:-K_ka7w_bJL2KCS-5FMl:byp6rt5) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java#L23)):*
> ```Java
> import retrofit2.Response;
> 
> public class RegisterWithMpnService extends Service implements ByuCallManager {
> ```

Revert

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kUEThvL1Gkgk8dx0f:-K_kbIXcM-9wpe6vnR3J:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make FavoritesActivity singleTop
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/AddFeatureActivity.java, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kOxdlRMjX6_rkaaHM:-K_keVrsjMtlNGNRyolp:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/AddFeatureActivity.java#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change to AddFeatures
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/AllFeaturesFragment.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kQ0-3WGvibv_kBUHo:-K_keZ5sAH3OEnEW9egm:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/AllFeaturesFragment.java#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove spaces
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 177 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kVAuNimsvdsHKTHty:-K_keplDJWa3F3-Hn4D4:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L177)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

put in psf
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java, line 33 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kWOofxfGGT4NEDtch:-K_kh1TpRRUY44bv5gMO:b-712nq3) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java#L33)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's get a ton of comments in here... It feels like reading a foreign language...
</blockquote></details>

I added a few but didn't really find a whole lot that was terribly difficult to understand... it honestly seems pretty self explanatory to me

---

*[support/src/main/java/edu/byu/support/feature/FeatureLoader.java, line 76 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kZTaZmxQStkiG3l8C:-K_kiuCCbbYZ71PzHBul:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeatureLoader.java#L76)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's rename this to populateAllFeatures
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/feature/FeatureLoader.java, line 145 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kZrj5Nj20AAhDRgSw:-K_kiv9JXNoK_N5EVczt:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeatureLoader.java#L145)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Rename to idToVisibleFeatureMap
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/feature/FeaturesWrapper.java, line 14 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kQwiU4N5dhbBApGLu:-K_kivuc7-AsOkozqjm6:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeaturesWrapper.java#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

private
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/feature/FeaturesWrapper.java, line 39 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kRCj5HInTo_w_oml5:-K_kj0kA_MR5H1dqr7Uu:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeaturesWrapper.java#L39)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Rename FavoritesManager
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_ka7w_bJL2KCS-5FMk:-K_kj_hlMy85bUvuEnWm:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/login/mpn/RegisterWithMpnService.java#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Revert
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by romrell4** [comment]
Reviewed 4 of 70 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java, line 142 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kmVGgHtPO94J0LqAJ:-K_kmVGgHtPO94J0LqAK:b-u5edaw) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/11d19cd43e46dbaed440922442d85f175ea0c30c/app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java#L142)):*
> ```Java
> 
> 		if (!newApps.isEmpty()) {
> 			data.add("New Apps");
> ```

"New Features"

---

*[app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java, line 143 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kmUFx8asPURMRYkx8:-K_kmUFyzJEe-3W0qI0O:b-p0dj1v) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/11d19cd43e46dbaed440922442d85f175ea0c30c/app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java#L143)):*
> ```Java
> 		if (!newApps.isEmpty()) {
> 			data.add("New Apps");
> 			Collections.sort(newApps);
> ```

Remove sorting

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by coreywoodfield** [comment]
Review status: 47 of 52 files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 78 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kUgvTGO-UOfsGrVVI:-K_knr6iOo3xrDkWYRZS:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L78)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove this (when it's working)
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java, line 142 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kmVGgHtPO94J0LqAJ:-K_knzQ5YtoMTU85K8GL:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/11d19cd43e46dbaed440922442d85f175ea0c30c/app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java#L142)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

"New Features"
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java, line 143 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kmUFx8asPURMRYkx8:-K_knsQY2nu_QkkGrjQB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/11d19cd43e46dbaed440922442d85f175ea0c30c/app/src/main/java/edu/byu/suite/mainScreen/WhatsNewDialog.java#L143)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove sorting
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/feature/FeatureLoader.java, line 48 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kX7-08kLgTwDxYh2j:-K_ko-nbV6bwYzEdLtnK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cdb4345acbfebb4c590a608ac782f64290dfec85/support/src/main/java/edu/byu/support/feature/FeatureLoader.java#L48)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove tags when we're done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by romrell4** [comment]
Reviewed 1 of 70 files at r1, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by coreywoodfield** [comment]
Review status: 50 of 52 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_kUJjkI6Xn-qe5ogPz:-K_krgxr1TDgqaSC9pQu:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Look into making static variables for all visibleFeatures, categories, favorites, what's new, etc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by romrell4** [comment]
Reviewed 1 of 70 files at r1, 1 of 16 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_ktBKb7gRQZbhJjhN1:-K_ktBKb7gRQZbhJjhN2:b-1efnko) (no related file):*
Let me know when you're done testing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_ktBKb7gRQZbhJjhN1:-K_ktDg4W-jQEBhfa1OH:b3ksm) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let me know when you're done testing
</blockquote></details>

k

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_ktBKb7gRQZbhJjhN1:-K_ktOWGoriWGhbswpOz:b-lmmpvj) (no related file):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

k
</blockquote></details>

Mark this as done when you're done testing :p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_ktBKb7gRQZbhJjhN1:-K_ktVNgoTfoBzwsfF2P:b3ksm) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Mark this as done when you're done testing :p
</blockquote></details>

k

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by romrell4** [comment]
Reviewed 1 of 16 files at r2, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FeatureLoader.java, line 26 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_l3_sVU4o1c3YAViwn:-K_l3_sWftB0u_BBwLx4:bju33qw) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a1e96812e6644d32f0fbec5d0f0f5d5a039ead7e/support/src/main/java/edu/byu/support/feature/FeatureLoader.java#L26)):*
> ```Java
> import java.util.concurrent.CountDownLatch;
> 
> import static edu.byu.support.login.internal.authenticator.AuthTokenFactory.buildBearerTokenAuthentication;
> ```

What's up with the static import? Just import AuthTokenFactory. That way people all know where the method is coming from.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FeatureLoader.java, line 26 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-K_l3_sVU4o1c3YAViwn:-K_ozF_MIPj0VQ-tjwj2:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a1e96812e6644d32f0fbec5d0f0f5d5a039ead7e/support/src/main/java/edu/byu/support/feature/FeatureLoader.java#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What's up with the static import? Just import AuthTokenFactory. That way people all know where the method is coming from.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/121#-:-K_pDxAJcAsxtNi0Mv7P:bnfp4nl)*

**Pull request merged**
