### PR TITLE
Added 'Add All' button to category activity

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/137)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/CategoryActivity.java, line 55 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/137#-KbvoJQTnE3nhU3dOXTK:-KbvoJQULot2xNPTQRvO:b-kfiek7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2e6e32c8754b8218d629f95a94703c374df6dd36/app/src/main/java/edu/byu/suite/mainScreen/CategoryActivity.java#L55)):*
> ```Java
> 				if (!favoritesManager.isFavorite(feature)) {
> 					favoritesManager.addFavorite(feature);
> 					adapter.notifyItemChanged(i);
> ```

Change this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/137)*

**Comment by coreywoodfield** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/CategoryActivity.java, line 55 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/137#-KbvoJQTnE3nhU3dOXTK:-KbvosRDb09pM_pK6f1U:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2e6e32c8754b8218d629f95a94703c374df6dd36/app/src/main/java/edu/byu/suite/mainScreen/CategoryActivity.java#L55)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/137)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/137)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/137#-:-Kbvp9_yJFqKCEXdv2Je:bnfp4nl)*

**Pull request merged**
