### PR TITLE
Analytics

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/130)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 88 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/130#-KbHcmdYqjieeccEM6Ef:-KbHcmdYqjieeccEM6Eg:bm26h8i) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c2d317db9973876daeba4862a7b615ca6fa4fafc/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L88)):*
> ```Java
> 	}
> 
> 	protected void launchFeature(final Activity activity, final Feature feature) {
> ```

Why does this all look like a new function? Didn't this exist before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/130)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 88 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/130#-KbHcmdYqjieeccEM6Ef:-KbQcJVj1vta2-RiLQjh:befc0dj) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c2d317db9973876daeba4862a7b615ca6fa4fafc/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L88)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why does this all look like a new function? Didn't this exist before?
</blockquote></details>

I'm not sure why I put that there, it looks like we're not even using it.  I've just removed it. The real method "launchFeature" is in FavoritesActivity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/130)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/130)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/130#-:-KbQdjX5en-sNI9loC0N:bnfp4nl)*

**Pull request merged**
