### PR TITLE
Bug fix: Fixed problem with vehicle attribute dialog in the AddVehicl…

### PR DESCRIPTION
**Pull request by poolguy**
…eActivity where the index of the selected item was saved regardless of whether the user clicked 'cancel' or 'ok'

---
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/112)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/112#-KZNWxRWi2z-84Cr9pM4:-KZNWxRXhMs3hVJtkFvQ:bwmi1me) (no related file):*
Can you also look into a reported bug from iOS? There was an issue that the textbox allowed you to enter a space character into the license plate field. Does Android let you do that currently?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/112)*

**Comment by poolguy** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/112#-KZNWxRWi2z-84Cr9pM4:-KZN_xHZs1RVn7hs7B0x:b-w68loz) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can you also look into a reported bug from iOS? There was an issue that the textbox allowed you to enter a space character into the license plate field. Does Android let you do that currently?
</blockquote></details>

Yes that was already taken care of. Also, just merged with dev, everything is working as it should.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/112)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/112)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/112#-:-KZRr7kYUmgVDXeLtPEH:bnfp4nl)*

**Pull request merged**
