### PR TITLE
Fixes #359

### LINKED ISSUE #359: Weird wrapping on galleries info
image

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/374)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 42 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpQe354O1F9M6CbM88:-KgpQe36fqzZV6MSDqfS:bpzgwjb) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L42)):*
> ```Java
> 	private ArtworkPagerAdapter pagerAdapter = new ArtworkPagerAdapter(getSupportFragmentManager());
> 	private ViewPager viewPager;
> 	private ViewAnimator viewAnimator;
> ```

What's the difference between these classes?

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 81 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpQsIdZ41_V1TfAhYW:-KgpQsIdZ41_V1TfAhYX:b-xike8f) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L81)):*
> ```Java
> 			public void onSuccess(Call<ArtworkResponseWrapper> call, Response<ArtworkResponseWrapper> response) {
> 				artworkList = response.body().getArtworkList();
> 				if (!artworkList.isEmpty()) {
> ```

What was this fixing? Was there another bug here?

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 53 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpQxO-0fODictRXNkE:-KgpQxO-0fODictRXNkF:btv2ua0) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L53)):*
> ```Java
> 
> 		((TextView) view.findViewById(R.id.nameText)).setText(artwork.getName());
> 		((TextView) view.findViewById(R.id.authorText)).setText(artwork.getAuthor().trim().replaceAll(" +", " "));
> ```

Was there some bad data here?

---

*[app/src/main/res/layout/galleries_fragment_artwork.xml, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpR4-6qnSLuPYEEfFm:-KgpR4-78ZJn0vyFNihq:bqk4d1h) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/res/layout/galleries_fragment_artwork.xml#L70)):*
> ```XML
> 			android:layout_height="wrap_content"
> 			android:textColor="@color/white"
> 			android:textStyle="italic"
> ```

Was it true that iOS didn't do this? If so, you can remove this... Did we solve the wrapping error?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 42 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpQe354O1F9M6CbM88:-Kgq91qndOyCFMkJm5xg:bn68mhe) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What's the difference between these classes?
</blockquote></details>

ViewAnimator can have more than 2 children, ViewSwitcher can only have 2

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 81 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpQsIdZ41_V1TfAhYW:-Kgq971F0AKR4QMzStBX:b-psfjxm) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L81)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What was this fixing? Was there another bug here?
</blockquote></details>

This was not fixing the main bug, this was fixing the bug where the list of images was empty. In that case there would just be nothing displayed. I added a textView that said that there were no images, as we do in other activities

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 53 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpQxO-0fODictRXNkE:-Kgq9Jyww-F9Ast_xcqW:b-50uvjc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Was there some bad data here?
</blockquote></details>

The image you gave with bad wrapping wrapped badly cus they put like 10 spaces in between the "Information Desk:" and the phone number. I saw two options - make it only one line, and add ellipses in the middle, or take out the excess spaces. Adding ellipses had undesired effects in many other pictures, so I figured taking out excess (and unnecessary) whitespace was the best solution

---

*[app/src/main/res/layout/galleries_fragment_artwork.xml, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpR4-6qnSLuPYEEfFm:-Kgq9jC1ymTMb5ke58bv:b-1tacty) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/res/layout/galleries_fragment_artwork.xml#L70)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Was it true that iOS didn't do this? If so, you can remove this... Did we solve the wrapping error?
</blockquote></details>

Yes, iOS doesn't italicize. There wasn't a wrapping error, the data just didn't lend itself to wrapping well. So I took out excess spaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 42 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpQe354O1F9M6CbM88:-KgsjlYj7zEVdl7pX7CM:b-bdxsx1) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L42)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

ViewAnimator can have more than 2 children, ViewSwitcher can only have 2
</blockquote></details>

Interesting... Did we need more than two here? Is that because you added the empty text?

---

*[app/src/main/res/layout/galleries_fragment_artwork.xml, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpR4-6qnSLuPYEEfFm:-KgsjSQLXhMKEvEA_3pI:bxqhzp9) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/res/layout/galleries_fragment_artwork.xml#L70)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Yes, iOS doesn't italicize. There wasn't a wrapping error, the data just didn't lend itself to wrapping well. So I took out excess spaces.
</blockquote></details>

Gotcha. So now do the two platforms looks alike when it comes to displaying details?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 42 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpQe354O1F9M6CbM88:-KgtWz5TcG7KyudHy0xV:b2nhtan) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Interesting... Did we need more than two here? Is that because you added the empty text?
</blockquote></details>

Yup

---

*[app/src/main/res/layout/galleries_fragment_artwork.xml, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpR4-6qnSLuPYEEfFm:-KgtX-svoaMhMO7ZtAd5:b-9lvgm3) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/res/layout/galleries_fragment_artwork.xml#L70)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Gotcha. So now do the two platforms looks alike when it comes to displaying details?
</blockquote></details>

In iOS the details are at the bottom, and in android they're at the top. There are slight differences in font size. But besides that, they're basically the same. Should we linkify the texts, so that addresses/phone numbers/emails/websites are clickable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/layout/galleries_fragment_artwork.xml, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpR4-6qnSLuPYEEfFm:-KgtcorNkm0nzQjblBkN:b-jxvjd3) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/res/layout/galleries_fragment_artwork.xml#L70)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

In iOS the details are at the bottom, and in android they're at the top. There are slight differences in font size. But besides that, they're basically the same. Should we linkify the texts, so that addresses/phone numbers/emails/websites are clickable?
</blockquote></details>

How hard would it be to move the details to the bottom? Seth wasn't able to figure it out. If you can do that, it would be great. Also, send me a screenshot or two of times where there would be a phone number, email, url, etc. Then I'll let you know if we should linkify it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by coreywoodfield** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/layout/galleries_fragment_artwork.xml, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpR4-6qnSLuPYEEfFm:-KgtjnlDCK_Vc4660fgD:buifgkk) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/res/layout/galleries_fragment_artwork.xml#L70)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

How hard would it be to move the details to the bottom? Seth wasn't able to figure it out. If you can do that, it would be great. Also, send me a screenshot or two of times where there would be a phone number, email, url, etc. Then I'll let you know if we should linkify it
</blockquote></details>

Moving it to the bottom took one line. I'll send you screenshots with stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/layout/galleries_fragment_artwork.xml, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpR4-6qnSLuPYEEfFm:-KgtwgI2o2-V6DgxDmdC:b-518r2b) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/res/layout/galleries_fragment_artwork.xml#L70)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Moving it to the bottom took one line. I'll send you screenshots with stuff
</blockquote></details>

Linkify

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/res/layout/galleries_fragment_artwork.xml, line 70 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-KgpR4-6qnSLuPYEEfFm:-Kgu4C3JbgE5jQWYJYNT:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c6086e666f59abb20e6ed139e89a635c4f219b15/app/src/main/res/layout/galleries_fragment_artwork.xml#L70)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Linkify
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-Kgu4eyOFKjuaZwdusH_:-Kgu4eyOFKjuaZwdusHa:b-nwljqr) (no related file):*
Remove logic for extra spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-Kgu4eyOFKjuaZwdusH_:-KgzeFUy5owCyyfhvGR3:b-vymyii) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove logic for extra spaces
</blockquote></details>

I did that yesterday

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/374#-:-Kh2colLeTeKF7-OXMYD:bnfp4nl)*

**Pull request merged**
