### PR TITLE
Hotfix/parking text edit

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/248)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/EditVehicleDialog.java, line 55 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/248#-KdSd9eBrX6Z6JXY6XR1:-KdSd9eBrX6Z6JXY6XR2:b8vy1up) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1514857f66c58826f7d54b5f74d323dbe63be2d7/app/src/main/java/edu/byu/suite/features/parking/controller/EditVehicleDialog.java#L55)):*
> ```Java
> 		editText.setText(vehicle.getLicenseNumber());
> 		editText.setSelection(editText.getText().length());
> 		editText.setFilters(new InputFilter[]{new InputFilter.AllCaps(), new InputFilter.LengthFilter(16), (charSequence, i, i1, spanned, i2, i3) -> {
> ```

Extract the InputFilter[] into a ParkingUtils class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/248)*

**Comment by poolguy** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/EditVehicleDialog.java, line 55 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/248#-KdSd9eBrX6Z6JXY6XR1:-KdSeeI-nVTnBrNzSJDr:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1514857f66c58826f7d54b5f74d323dbe63be2d7/app/src/main/java/edu/byu/suite/features/parking/controller/EditVehicleDialog.java#L55)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Extract the InputFilter[] into a ParkingUtils class
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/248)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/248)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/248#-:-KdSeorjjAaZDwPhpWzG:bnfp4nl)*

**Pull request merged**
