### PR TITLE
Feature/retry

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/75)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r1, 6 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 36 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUcxvx_b5BfeccK72GB:-KUcxvx_b5BfeccK72GC:b8rfl8) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d81b436255ca113075b2e7d98835593ae3d186d6/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L36)):*
> ```Java
> 	}
> 
> 	public ByuCallback(ByuCallManager callManager, String defaultErrorMessage, String pathToReadableError, boolean shouldRetry) {
> ```

Comment above about when to use

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 40 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUczIDrlNgCh-DNK6pI:-KUczIDrlNgCh-DNK6pJ:b98hix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d81b436255ca113075b2e7d98835593ae3d186d6/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L40)):*
> ```Java
> 		this.pathToReadableError = pathToReadableError;
> 		this.callManager = callManager;
> 		this.shouldRetry = shouldRetry;
> ```

retryCounter

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 66 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUcykYpOn9IV_KWPP7X:-KUcykYpOn9IV_KWPP7Y:b-amjfy7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d81b436255ca113075b2e7d98835593ae3d186d6/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L66)):*
> ```Java
> 					onFailure(call, new ByuError(readableError != null ? readableError : defaultErrorMessage));
> 				} catch (IOException ignore) {
> 					onFailure(call, new ByuError(response, defaultErrorMessage, pathToReadableError));
> ```

Change to retry on all exception

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 107 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUczYzU4s-cdU8vtTmb:-KUczYzVnJuGaTrWfGkA:bm1nd32) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d81b436255ca113075b2e7d98835593ae3d186d6/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L107)):*
> ```Java
> 	}
> 
> 	public ByuCallback<T> reuse() {
> ```

Comment above this one as well (as to when to use it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75)*

**Comment by coreywoodfield** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 36 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUcxvx_b5BfeccK72GB:-KUd3wOfAqS089iHwTDz:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d81b436255ca113075b2e7d98835593ae3d186d6/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L36)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment above about when to use
</details>
Done.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 40 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUczIDrlNgCh-DNK6pI:-KUd3X7cBJuW4x5hnohv:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d81b436255ca113075b2e7d98835593ae3d186d6/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L40)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> retryCounter
</details>
Done.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 66 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUcykYpOn9IV_KWPP7X:-KUd3XuutcfepqQj2mP2:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d81b436255ca113075b2e7d98835593ae3d186d6/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L66)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Change to retry on all exception
</details>
Done.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 107 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUczYzU4s-cdU8vtTmb:-KUd3bPdAhqzY_Sk6Pl5:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d81b436255ca113075b2e7d98835593ae3d186d6/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L107)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment above this one as well (as to when to use it)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 24 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUd7SWK27Mu3I0RMhkC:-KUd7SWLstSWWB82wQRH:b-3yh05o) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f3318e64aecd7b961991b2ae4d21258db6a6a370/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L24)):*
> ```Java
> 
> 	public ByuCallback(ByuCallManager callManager) {
> 		this(callManager, "The server encountered an error. Please try again later.");
> ```

Extract this as a psf

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 32 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUd8-aqPIXp2iNcI6SJ:-KUd8-ar1zN7wi7mZXkE:bqvkdnn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f3318e64aecd7b961991b2ae4d21258db6a6a370/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L32)):*
> ```Java
> 
> 	public ByuCallback(ByuCallManager callManager, String defaultErrorMessage, String pathToReadableError) {
> 		this.defaultErrorMessage = defaultErrorMessage;
> ```

Call through to other constuctor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75)*

**Comment by coreywoodfield** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 24 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUd7SWK27Mu3I0RMhkC:-KUd8dsyvsWmDx29rVan:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f3318e64aecd7b961991b2ae4d21258db6a6a370/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Extract this as a psf
</details>
Done.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallback.java, line 32 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-KUd8-aqPIXp2iNcI6SJ:-KUd8GB2uHWtsDrmMvvJ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f3318e64aecd7b961991b2ae4d21258db6a6a370/support/src/main/java/edu/byu/support/retrofit/ByuCallback.java#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Call through to other constuctor
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/75#-:-KUdADlSZj7HsXvxpnnl:bnfp4nl)*

**Pull request merged**
