### PR TITLE
Feature/sync

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/386)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 20 of 20 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 9 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qR-3_mgvzyLeeUpo:-Kh9qR-3_mgvzyLeeUpp:boye36h) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6476486f9625615ee5c6a7b6566e208843c55cdd/app/src/main/AndroidManifest.xml#L9)):*
> ```XML
> 	<uses-feature android:name="android.hardware.screen.portrait" />
> 
> 	<uses-permission android:name="android.permission.INTERNET" />
> ```

Why were we able to get rid of these?

---

*[support/src/main/AndroidManifest.xml, line 13 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qYX_5y_HbxSIw87s:-Kh9qYX_5y_HbxSIw87t:b-4492lq) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/AndroidManifest.xml#L13)):*
> ```XML
> 	<uses-permission android:name="android.permission.MANAGE_ACCOUNTS" />
> 	<uses-permission android:name="android.permission.USE_CREDENTIALS" />
> 	<uses-permission android:name="android.permission.READ_SYNC_STATS" />
> ```

Explain these to me

---

*[support/src/main/AndroidManifest.xml, line 45 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qdindocSqbVCZhc3:-Kh9qdindocSqbVCZhc4:b7d76ll) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/AndroidManifest.xml#L45)):*
> ```XML
> 		
> 		<service
> 				android:name=".login.account.sync.Iceberg"
> ```

Oh my goodness... It's spelled totally differently!!!! :p

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 88 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qr18uRDM_jexmSuD:-Kh9qr18uRDM_jexmSuE:b-kc8bcs) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/LoginActivity.java#L88)):*
> ```Java
> 					Account account = createAccount(accountManager, username, password, token);
> 					// periodically (as triggered by the system) get information about their account (e.g. personId, name, etc.)
> 					ContentResolver.setSyncAutomatically(account, getString(R.string.fakeContentAuthority), true);
> ```

Can you explain to me the details of what this is actually going to do?

---

*[support/src/main/java/edu/byu/support/login/account/AccountInformation.java, line 115 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9r26yGt54brJyiMbh:-Kh9r26yGt54brJyiMbi:b-yhe1ux) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/AccountInformation.java#L115)):*
> ```Java
> 	}
> 
> 	private static Object handle;
> ```

What do you need this handle for?

---

*[support/src/main/java/edu/byu/support/login/account/AccountInformation.java, line 117 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qvvEYwsmEghXCgDM:-Kh9qvvEYwsmEghXCgDN:b-5dbw3w) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/AccountInformation.java#L117)):*
> ```Java
> 	private static Object handle;
> 
> 	public synchronized static void sync(final Context context, final Account account, final AccountInformationCallback callback) {
> ```

synchronized? Explain this function to me

---

*[support/src/main/java/edu/byu/support/login/account/sync/Iceberg.java, line 12 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rA81FFePd0vretM8:-Kh9rA81FFePd0vretM9:bu64u0q) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/sync/Iceberg.java#L12)):*
> ```Java
>  */
> 
> public class Iceberg /* cus it makes the titanic sync */ extends Service {
> ```

Nope. Stuff in comments I can do this, but class names need to be better than this

---

*[support/src/main/java/edu/byu/support/login/account/sync/StubContentProvider.java, line 15 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rJw3fNPVWRYmetdY:-Kh9rJw3fNPVWRYmetdZ:b-emyn05) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/sync/StubContentProvider.java#L15)):*
> ```Java
>  */
> 
> public class StubContentProvider extends ContentProvider {
> ```

What is this doing?

---

*[support/src/main/java/edu/byu/support/login/account/sync/Titanic.java, line 15 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rLwgJlHTpTwTwbv3:-Kh9rLwgJlHTpTwTwbv4:bb710yj) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/sync/Titanic.java#L15)):*
> ```Java
>  */
> 
> public class Titanic /* cus it syncs */ extends AbstractThreadedSyncAdapter {
> ```

Nope

---

*[support/src/main/res/drawable-hdpi/ic_menu_delete.png, line 0 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rR35w_OhMczLVg5E:-Kh9rR35w_OhMczLVg5F:b9d665k) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/res/drawable-hdpi/ic_menu_delete.png#L0)):*
What are all these images?

---

*[support/src/main/res/xml/titanic.xml, line 1 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rWcj3iVnopmYedzL:-Kh9rWcj3iVnopmYedzM:bb710yj) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/res/xml/titanic.xml#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

Nope

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 9 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qR-3_mgvzyLeeUpo:-KhOhVm0jkDBj4--Q6q9:bffdeq9) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6476486f9625615ee5c6a7b6566e208843c55cdd/app/src/main/AndroidManifest.xml#L9)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why were we able to get rid of these?
</blockquote></details>

What do we need internet for?

jk jk I put them in support

---

*[support/src/main/AndroidManifest.xml, line 13 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qYX_5y_HbxSIw87s:-KhOh_qtEafGk2fWOX4q:b-d0cy4p) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/AndroidManifest.xml#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Explain these to me
</blockquote></details>

They're required to sync stuff. You might say they're like large floating hunks of ice. you just can't sync stuff without em

---

*[support/src/main/AndroidManifest.xml, line 45 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qdindocSqbVCZhc3:-KhOgZCCea9RFvP2ArDn:bb7hquh) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/AndroidManifest.xml#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Oh my goodness... It's spelled totally differently!!!! :p
</blockquote></details>

huh?

---

*[support/src/main/java/edu/byu/support/login/LoginActivity.java, line 88 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qr18uRDM_jexmSuD:-KhOhijh4qOpkgxq1CK4:byxivo4) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/LoginActivity.java#L88)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can you explain to me the details of what this is actually going to do?
</blockquote></details>

yeah we tell the phone that it should sync their account info every so often, and then the phone does.

---

*[support/src/main/java/edu/byu/support/login/account/AccountInformation.java, line 115 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9r26yGt54brJyiMbh:-KhOgf6xCxdSZZ10slBk:b-fwm0m5) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/AccountInformation.java#L115)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What do you need this handle for?
</blockquote></details>

for handling... things
https://developer.android.com/reference/android/content/ContentResolver.html#addStatusChangeListener(int, android.content.SyncStatusObserver) 

---

*[support/src/main/java/edu/byu/support/login/account/AccountInformation.java, line 117 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9qvvEYwsmEghXCgDM:-KhOgpXiS0UWv8oqOe-s:be4n74e) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/AccountInformation.java#L117)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

synchronized? Explain this function to me
</blockquote></details>

it's synchronized so the handle doesn't get changed, but I just realized that won't work, cus the handle is used in an asynchronous call. I'll have to make a queue of handles...

---

*[support/src/main/java/edu/byu/support/login/account/sync/Iceberg.java, line 12 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rA81FFePd0vretM8:-KhOh1x4xa4F4vo-1KZM:bp5ex0e) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/sync/Iceberg.java#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Nope. Stuff in comments I can do this, but class names need to be better than this
</blockquote></details>

awwww Eric come on that's a super descriptive class name

---

*[support/src/main/java/edu/byu/support/login/account/sync/StubContentProvider.java, line 15 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rJw3fNPVWRYmetdY:-KhOh7FKWh28dFPBdepy:b1caxw) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/sync/StubContentProvider.java#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this doing?
</blockquote></details>

it's satisfying silly requirements. see the url at the top for more info

---

*[support/src/main/java/edu/byu/support/login/account/sync/Titanic.java, line 15 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rLwgJlHTpTwTwbv3:-KhOhFtMVP2rtKngnK_u:bnay2mz) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/sync/Titanic.java#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Nope
</blockquote></details>

:cry: 

---

*[support/src/main/res/drawable-hdpi/ic_menu_delete.png, line  at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rR35w_OhMczLVg5E:-KhOhJqeZhWNr2ZsGSmU:b-wl9no) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/res/drawable-hdpi/ic_menu_delete.png#L)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What are all these images?
</blockquote></details>

i dunno. they weren't used though. i think we just copied them from v1

---

*[support/src/main/res/xml/titanic.xml, line 1 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rWcj3iVnopmYedzL:-KhOhTCHur_9B4fk9KoU:b-8elstz) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/res/xml/titanic.xml#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Nope
</blockquote></details>

:sob:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/login/account/sync/StubContentProvider.java, line 15 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-Kh9rJw3fNPVWRYmetdY:-KhOih8Y0Iy9wrvhcQzY:b-vlhh3x) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b3a3f591f2cc262417c3192f9f3d38d6e5607a28/support/src/main/java/edu/byu/support/login/account/sync/StubContentProvider.java#L15)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

it's satisfying silly requirements. see the url at the top for more info
</blockquote></details>

also https://developer.android.com/training/sync-adapters/creating-stub-provider.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386)*

**Comment by romrell4** [comment]
Reviewed 2 of 22 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/AndroidManifest.xml, line 14 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-KhOs8of2xCfWkNrxt0E:-KhOs8of2xCfWkNrxt0F:b-6n44sg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f04675890ce9f11451b96990fc8fc1994fe11010/support/src/main/AndroidManifest.xml#L14)):*
> ```XML
> 	<uses-permission android:name="android.permission.USE_CREDENTIALS" />
> 	<uses-permission android:name="android.permission.READ_SYNC_STATS" />
> 	<uses-permission android:name="android.permission.READ_SYNC_SETTINGS" />
> ```

Maybe look into removing these

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386)*

**Comment by coreywoodfield** [comment]
Review status: 15 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/AndroidManifest.xml, line 14 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-KhOs8of2xCfWkNrxt0E:-KhP41Yxwd5EgoHrJdBR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f04675890ce9f11451b96990fc8fc1994fe11010/support/src/main/AndroidManifest.xml#L14)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Maybe look into removing these
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/login/account/AccountInformation.java, line 112 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-KhT2EgqY0KkcI1PVJ_k:-KhT2EgrGSIGwFg-GdDK:b8ryoy2) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/86ef1fa7e9c2b72737e8d14d9ea1310820a750c6/support/src/main/java/edu/byu/support/login/account/AccountInformation.java#L112)):*
> ```Java
> 
> 	public static void sync(final Context context, final Account account, final AccountInformationCallback callback) {
> 		new Thread() {
> ```

Comments throughout this function

---

*[support/src/main/java/edu/byu/support/login/account/AccountInformation.java, line 122 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-KhT2VNcPU2EaoX1iXb9:-KhT2VNcPU2EaoX1iXbA:bwsjy6r) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/86ef1fa7e9c2b72737e8d14d9ea1310820a750c6/support/src/main/java/edu/byu/support/login/account/AccountInformation.java#L122)):*
> ```Java
> 			}
> 
> 			private void runCallback(final AccountInformation accountInformation) {
> ```

I'm good inlining this function. It's short enough and is similar enough to be in the run() code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386)*

**Comment by coreywoodfield** [comment]
Review status: 18 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/login/account/AccountInformation.java, line 112 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-KhT2EgqY0KkcI1PVJ_k:-KhYZe45ap5vNsOVoMWV:bsiinh3) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/86ef1fa7e9c2b72737e8d14d9ea1310820a750c6/support/src/main/java/edu/byu/support/login/account/AccountInformation.java#L112)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comments throughout this function
</blockquote></details>

I decided to make it self documenting instead. does that suffice?

---

*[support/src/main/java/edu/byu/support/login/account/AccountInformation.java, line 122 at r5](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386#-KhT2VNcPU2EaoX1iXb9:-KhYYEJmSqhs8tQB1Dtz:b3ksm) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/86ef1fa7e9c2b72737e8d14d9ea1310820a750c6/support/src/main/java/edu/byu/support/login/account/AccountInformation.java#L122)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'm good inlining this function. It's short enough and is similar enough to be in the run() code
</blockquote></details>

k

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/386)*

**Pull request merged**
