### PR TITLE
Fix/learning suite

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/270)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/270#-KeAxN7Uv7_iA87yApzL:-KeAxN7Uv7_iA87yApzM:b-qs8y02) (no related file):*
Do what we talked about

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/270)*

**Comment by coreywoodfield** [comment]
Review status: 3 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/270#-KeAxN7Uv7_iA87yApzL:-KeB7MkU-nbOIE6n2ikm:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do what we talked about
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/270)*

**Comment by romrell4** [comment]
Reviewed 12 of 28 files at r2, 1 of 15 files at r3, 14 of 19 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/270)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/270#-:-KeBP9RoS9qEc--51xiF:bnfp4nl)*

**Pull request merged**
