### PR TITLE
Fix dialog messages

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/118)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 149 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/118#-K__iBbQegeYZdGB2x_E:-K__iBbQegeYZdGB2x_F:b8gsfc8) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/54afbe7de4a17451da0aa6213ab598ce4c2d3c1c/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L149)):*
> ```Java
> 
> 	public void showProgressDialog(boolean cancelable) {
> 		showProgressDialog("Loading...", cancelable);
> ```

Call through

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/118)*

**Comment by poolguy** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 149 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/118#-K__iBbQegeYZdGB2x_E:-K__jC-TL6al46s8PliS:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/54afbe7de4a17451da0aa6213ab598ce4c2d3c1c/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L149)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Call through
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/118)*

**Comment by poolguy** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 149 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/118#-K__iBbQegeYZdGB2x_E:-K__jCl7so4ABEkAmFjF:bjtlixm) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/54afbe7de4a17451da0aa6213ab598ce4c2d3c1c/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L149)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well sort of.. I did a PSF instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/118)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/118)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/118#-:-K__jmMUxCS2ItoiYL1Q:bnfp4nl)*

**Pull request merged**
