### PR TITLE
Check for empty string in getter of Event object

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/397)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/model/Event.java, line 79 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397#-KjsBykDazAv-2iBPlnk:-KjsBykDazAv-2iBPlnl:b-fgh8u1) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/97fada4d56b0dfa09a2c95ee4b871d272cf5d7b4/app/src/main/java/edu/byu/suite/features/calendars/model/Event.java#L79)):*
> ```Java
> 
> 	public String getLowPrice() {
> 		return lowPrice.isEmpty() ? "0" : lowPrice;
> ```

Move this to the client

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397)*

**Comment by poolguy** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/model/Event.java, line 79 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397#-KjsBykDazAv-2iBPlnk:-Kjso1P-oRa-VA098_8T:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/97fada4d56b0dfa09a2c95ee4b871d272cf5d7b4/app/src/main/java/edu/byu/suite/features/calendars/model/Event.java#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Move this to the client
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 60 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397#-KjsqruEdVuBKaWdu48U:-KjsqruEdVuBKaWdu48V:b-kc0t6n) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a59435416438ca5b925b8e61beebe908b8f9d3cc/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L60)):*
> ```Java
> 			listItems.add(new EventListItem(getString(R.string.event_end_title_text), getString(R.string.calendar_long_date_time_format, event.getEndDateTime()), EventListItemType.DEFAULT_WITH_DETAIL));
> 		}
> 		if (event.isTicketsExist()) {
> ```

Check this against the swift code I sent you

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397)*

**Comment by romrell4** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397)*

**Comment by poolguy** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 60 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397#-KjsqruEdVuBKaWdu48U:-KjstjXELKk150T_6h-F:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a59435416438ca5b925b8e61beebe908b8f9d3cc/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L60)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check this against the swift code I sent you
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 60 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397#-KjsqruEdVuBKaWdu48U:-KjytHEFt2fSUCzz7HPM:b-jqbfog) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/a59435416438ca5b925b8e61beebe908b8f9d3cc/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L60)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Were there any discrepancies?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/397)*

**Pull request merged**
