### PR TITLE
Reformat EventActivity: closes #214

### LINKED ISSUE #214: Calendars Event View
Event view layout needs to be redone. Look at iOS for pointers

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/268)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/268#-Ke5yLTRDEpeHN_uMgwq:-Ke5yLTRDEpeHN_uMgwr:b6v65jf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/211b586e2b21b610d375e1aa6296c98bc53b84e6/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L32)):*
> ```Java
> 
> 		//Set the default text for all views
> 		((TextView) findViewById(R.id.event_title_header).findViewById(R.id.textView)).setText(R.string.event_title_header_text);
> ```

Can we not just use a recycler view to do this? It seems that this is sorta overkill

---

*[support/src/main/java/edu/byu/support/utils/ViewUtils.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/268#-KeAhgNj03QzcDWMZaXj:-KeAhgNj03QzcDWMZaXk:bbgbveq) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/211b586e2b21b610d375e1aa6296c98bc53b84e6/support/src/main/java/edu/byu/support/utils/ViewUtils.java#L26)):*
> ```Java
> 	}
> 
> 	public static void setTextOrHide(TextView view, View viewToHide, View viewToHide2, CharSequence text) {
> ```

We shouldn't need this if we got to a recycler view

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/268)*

**Comment by poolguy** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/268#-Ke5yLTRDEpeHN_uMgwq:-KeF52Ba05lA5KqMDc9E:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d1d47a98ad65e8ddc59b7efffc7f6dc3539a46ae/app/src/main/java/edu/byu/suite/features/calendars/controller/EventActivity.java#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can we not just use a recycler view to do this? It seems that this is sorta overkill
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/utils/ViewUtils.java, line 26 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/268#-KeAhgNj03QzcDWMZaXj:-KeF53jM7tImmrXU6HRi:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d1d47a98ad65e8ddc59b7efffc7f6dc3539a46ae/support/src/main/java/edu/byu/support/utils/ViewUtils.java#L26)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We shouldn't need this if we got to a recycler view
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/268)*

**Comment by romrell4** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/268)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/268#-:-KeF6XU_0eYqvPvkAPfg:bnfp4nl)*

**Pull request merged**
