### PR TITLE
Bug fix for when the service returns an exam with no building. public…

### PR DESCRIPTION
**Pull request by poolguy**
… static final strings

---
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/111)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZNSjwMy2EITjF7xQvr:-KZNSjwMy2EITjF7xQvs:b-m94uor) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9b6d20f3b16b2692e5330c02cfca4f587c6fb8db/app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java#L77)):*
> ```Java
> 		List<Building> buildings = new ArrayList<>();
> 		// We use an Iterator here to remove an exam if the building is null
> 		Iterator<Exam> iterator = exams.iterator();
> ```

Ask Corey about the CollectionUtils filterWithPredicate function that he wrote. I think that should be able to do this for you

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by poolguy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZNSjwMy2EITjF7xQvr:-KZNjvWJdGw-BLlXDKnl:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9b6d20f3b16b2692e5330c02cfca4f587c6fb8db/app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java#L77)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Ask Corey about the CollectionUtils filterWithPredicate function that he wrote. I think that should be able to do this for you
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by romrell4** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZRrm27b-Vc4v5pKp1a:-KZRrm27b-Vc4v5pKp1b:b-szjznh) (no related file):*
Also, we are renaming this feature to "My Finals Schedule". Could you rename the feature in the manifest as well as any files that should be changed?

---

*[app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZNSjwMy2EITjF7xQvr:-KZS52MnI8MWb9svMGHm:b-a415yp) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9b6d20f3b16b2692e5330c02cfca4f587c6fb8db/app/src/main/java/edu/byu/suite/features/mapMyFinals/controller/ExamMapFragment.java#L77)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry... Corey's CollectionUtils class didn't actually do everything that I thought it did. However, this is still better. Now that you don't have to remove anymore, you can probably use foreach loops rather than for "i" loops

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZRrm27b-Vc4v5pKp1a:-KZSCflwkY_gRX2YYcqX:bkeq6p0) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Also, we are renaming this feature to "My Finals Schedule". Could you rename the feature in the manifest as well as any files that should be changed?
</blockquote></details>

I can do that. Would you like me to change the names of all the files as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZRrm27b-Vc4v5pKp1a:-KZSD2OXGnW-qRCT5b3U:b-d6egzk) (no related file):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

I can do that. Would you like me to change the names of all the files as well?
</blockquote></details>

Yes please. Anything that used to references "MapMyFinals" or anything similar should now be "MyFinalsSchedule". The only thing that can't change is the featureId in the manifest

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by poolguy** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZRrm27b-Vc4v5pKp1a:-KZSFRG7dRedu-93kdCx:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yes please. Anything that used to references "MapMyFinals" or anything similar should now be "MyFinalsSchedule". The only thing that can't change is the featureId in the manifest
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/ExamMapFragment.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZNSjwMy2EITjF7xQvr:-KZSFNy9Clm15nfruisz:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9b6d20f3b16b2692e5330c02cfca4f587c6fb8db/app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/ExamMapFragment.java#L77)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Sorry... Corey's CollectionUtils class didn't actually do everything that I thought it did. However, this is still better. Now that you don't have to remove anymore, you can probably use foreach loops rather than for "i" loops
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by romrell4** [comment]
Reviewed 5 of 19 files at r3.
Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/ExamMapFragment.java, line 72 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZSFnILphiyOwFWLdPW:-KZSFnILphiyOwFWLdPX:bakqpj3) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/da258dcff309cc29621d1356bba7569e374a653c/app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/ExamMapFragment.java#L72)):*
> ```Java
> 		// We use CollectionUtils here to remove all exams whose building attribute is null
> 		CollectionUtils.filter(exams, exam -> exam.getBuilding() == null);
> 		for (Exam exam : exams) {
> ```

Put a TODO above this line saying that we should be able to use CollectionUtils to do this later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by romrell4** [comment]
Reviewed 14 of 19 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by poolguy** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/ExamMapFragment.java, line 72 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-KZSFnILphiyOwFWLdPW:-KZSHREYLmn-RvDBkr3N:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/da258dcff309cc29621d1356bba7569e374a653c/app/src/main/java/edu/byu/suite/features/myFinalsSchedule/controller/ExamMapFragment.java#L72)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put a TODO above this line saying that we should be able to use CollectionUtils to do this later
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111)*

**Comment by romrell4** [comment]
:lgtm:

---

Reviewed 1 of 19 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/111#-:-KZSHUIRDPW4yq0xqmJF:bnfp4nl)*

**Pull request merged**
