### PR TITLE
Hotfix/login

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/125)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/res/values/strings.xml, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOm6c7-2EIfXTt7mzN:-KaOm6cA6NXxIyct_yWx:b-5lgx00) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2ba7befd03a36bdda900a6a21ae92e9c9be742d4/app/src/main/res/values/strings.xml#L21)):*
> ```XML
> 	<string name="logged_out">Logged out</string>
> 	<string name="logged_in_format">Logged in as %s</string>
> 	<string name="logged_in_no_info">Logged in but unable to load user info.</string>
> ```

Logged in. Unable to get personal information.

---

*[support/src/main/res/values/strings.xml, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOmTNZ08oWx_c4KO3H:-KaOmTNZ08oWx_c4KO3I:bjpsk1u) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2ba7befd03a36bdda900a6a21ae92e9c9be742d4/support/src/main/res/values/strings.xml#L6)):*
> ```XML
> 	<string name="empty_string" />
> 	<string name="feature_icon_description">Icon representing the feature</string>
> 	
> ```

I think there might be a way to not have to do this... Talk to me :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOmYk0-1X1lB8FTBOu:-KaOmYk0-1X1lB8FTBOv:bfghnkc) (no related file):*
Do what we talked about (making the request any time the person name isn't loaded)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/res/values/strings.xml, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOm6c7-2EIfXTt7mzN:-KaOqPw2EtIdcfUvD6PR:bsszb2l) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2ba7befd03a36bdda900a6a21ae92e9c9be742d4/app/src/main/res/values/strings.xml#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Logged in. Unable to get personal information.
</blockquote></details>

Logged in as unable to get personal information

How does that sound? Then we wouldn't need another string resource

---

*[support/src/main/res/values/strings.xml, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOmTNZ08oWx_c4KO3H:-KaOqMBIlAUhiQmYJBTn:b-6tb0et) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2ba7befd03a36bdda900a6a21ae92e9c9be742d4/support/src/main/res/values/strings.xml#L6)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think there might be a way to not have to do this... Talk to me :)
</blockquote></details>

There is but it'd be kind of a pain

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/res/values/strings.xml, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOm6c7-2EIfXTt7mzN:-KaOr0H7T6wEXILyGa3n:b-zcjvte) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2ba7befd03a36bdda900a6a21ae92e9c9be742d4/app/src/main/res/values/strings.xml#L21)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Logged in as unable to get personal information

How does that sound? Then we wouldn't need another string resource
</blockquote></details>

Thanks

---

*[support/src/main/res/values/strings.xml, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOmTNZ08oWx_c4KO3H:-KaOr-N41Rvh087QqC0B:b-zcjvte) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/2ba7befd03a36bdda900a6a21ae92e9c9be742d4/support/src/main/res/values/strings.xml#L6)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

There is but it'd be kind of a pain
</blockquote></details>

Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125)*

**Comment by coreywoodfield** [comment]
Review status: 5 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOmYk0-1X1lB8FTBOu:-KaOtCiSAJNdhNPjxQMU:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do what we talked about (making the request any time the person name isn't loaded)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125)*

**Comment by romrell4** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 190 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOvb7DfdiATq1M7Wwf:-KaOvb7E8PCs-Bvn3CTR:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0915f3f42e3b4a1e2debed1931d5ab310ba0034a/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L190)):*
> ```Java
> 				loginMenuItem.setVisible(false);
> 				logoutMenuItem.setVisible(true);
> 				AccountInformation.sync(this, result -> {
> ```

Comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125)*

**Comment by coreywoodfield** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java, line 190 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-KaOvb7DfdiATq1M7Wwf:-KaP--gisqb3NLPq6sOs:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0915f3f42e3b4a1e2debed1931d5ab310ba0034a/app/src/main/java/edu/byu/suite/mainScreen/FavoritesActivity.java#L190)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/125#-:-KaP-saVJ8YUqGu4btTw:bnfp4nl)*

**Pull request merged**
