### PR TITLE
Added CollectionUtils.transform

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/135)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/ytime/service/YTimeClient.java, line 126 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-KblXiNDCQ8wef2p6g2h:-KblXiNExZj71jsfeuS2:b-w1b9ut) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1b8933498ad5c454d00bbb21924c6709989fa371/app/src/main/java/edu/byu/suite/features/ytime/service/YTimeClient.java#L126)):*
> ```Java
> 	private class YTimeListDeserializer implements JsonDeserializer<List<YTimeJob>> {
> 		@Override
> 		public List<YTimeJob> deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
> ```

Comments about why we use JsonElement

---

*[app/src/main/java/edu/byu/suite/features/ytime/service/YTimeClient.java, line 127 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-KblXkwI3liZ8F0-LLbu:-KblXkwI3liZ8F0-LLbv:b-q0a2lz) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1b8933498ad5c454d00bbb21924c6709989fa371/app/src/main/java/edu/byu/suite/features/ytime/service/YTimeClient.java#L127)):*
> ```Java
> 		@Override
> 		public List<YTimeJob> deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
> 			if (json.isJsonArray()) {
> ```

Fake some data and test to make sure this works

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/client/registrationClient/model/YearTermHelper.java, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-KblY2ECVOjIntF2SsiS:-KblY2ECVOjIntF2SsiT:bye3k30) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1b8933498ad5c454d00bbb21924c6709989fa371/support/src/main/java/edu/byu/support/client/registrationClient/model/YearTermHelper.java#L23)):*
> ```Java
> 			case '4':
> 				return "Summer " + year;
> 			case '5':
> ```

Add case '6'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/client/registrationClient/model/YearTermHelper.java, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-KblY4ks5fb1cq8c13FX:-KblY4ks5fb1cq8c13FY:bris3mh) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1b8933498ad5c454d00bbb21924c6709989fa371/support/src/main/java/edu/byu/support/client/registrationClient/model/YearTermHelper.java#L24)):*
> ```Java
> 				return "Summer " + year;
> 			case '5':
> 				return "Fall " + year;
> ```

Remove helper and put into the object

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/ytime/service/YTimeClient.java, line 126 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-KblXiNDCQ8wef2p6g2h:-KblZCe0rarTvtBHb6io:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1b8933498ad5c454d00bbb21924c6709989fa371/app/src/main/java/edu/byu/suite/features/ytime/service/YTimeClient.java#L126)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comments about why we use JsonElement
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/ytime/service/YTimeClient.java, line 127 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-KblXkwI3liZ8F0-LLbu:-KblciKPhrrmy-AJp7cN:b968j32) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1b8933498ad5c454d00bbb21924c6709989fa371/app/src/main/java/edu/byu/suite/features/ytime/service/YTimeClient.java#L127)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Fake some data and test to make sure this works
</blockquote></details>

It works. I actually tested it.

---

*[support/src/main/java/edu/byu/support/client/registrationClient/model/YearTermHelper.java, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-KblY2ECVOjIntF2SsiS:-Kbl_P-Rk6Jc4X0Ayv-e:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1b8933498ad5c454d00bbb21924c6709989fa371/support/src/main/java/edu/byu/support/client/registrationClient/model/YearTermHelper.java#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add case '6'
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/client/registrationClient/model/YearTermHelper.java, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-KblY4ks5fb1cq8c13FX:-Kbl_PKEs5UPfiOpgi5f:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1b8933498ad5c454d00bbb21924c6709989fa371/support/src/main/java/edu/byu/support/client/registrationClient/model/YearTermHelper.java#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove helper and put into the object
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/135#-:-KbldbMuQflg8XUdO4qI:bnfp4nl)*

**Pull request merged**
