### PR TITLE
Fixes #168 and generally improves IdCardActivity

### LINKED ISSUE #168: ID Card: NullPointerException
Name of Tester: Corey
Feature: ID Card

How to produce error:
Open ID Card

Expected Result:
I got a NullPointerException on line 151 of IdCardActivity - haven't been able to recreate

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/189)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 132 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/189#-KceYId_iTutuskVqNfJ:-KceYId_iTutuskVqNfK:bhea75s) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/82cef95e87eb7d699f85aed1155a1eb3f2e1331d/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L132)):*
> ```Java
> 			canvas.drawBitmap(idCardBase, null, new Rect(0, 0, photoWidth, photoHeight), paint);
> 
> 			if (photo != null) {
> ```

Just pop them back when the photo isn't retrieved correctly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/189)*

**Comment by coreywoodfield** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 132 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/189#-KceYId_iTutuskVqNfJ:-KceZTPfnnltyk-mye3f:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/82cef95e87eb7d699f85aed1155a1eb3f2e1331d/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L132)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Just pop them back when the photo isn't retrieved correctly
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/189)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/189)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/189#-:-KceZjtEqhHZ3lURa1Pa:bnfp4nl)*

**Pull request merged**
