### PR TITLE
Hotfix/recyclerViewActivity

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/231)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDu1u1PLoga6r1Gfgo:-KdDu1u1PLoga6r1Gfgp:b-pgn03i) (no related file):*
I have an idea. We should make the ByuRecyclerViewActivity an abstract class with a method called `getEmptyDataText()`. Then you would just have to fill in the method rather than always remembering to use the `switchViewIfWhatever` method. Thoughts?

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDtGNhEu2uN97tMZL-:-KdDtGNhEu2uN97tMZL0:b-dy6efy) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/31f8712b8a8a90db114d64edab2c0b4d666c525d/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L6)):*
> ```Java
> import android.os.Bundle;
> 
> import java.util.Arrays;
> ```

Go through each of the files changed and optimize the imports. I don't know if you need these

---

*[app/src/main/java/edu/byu/suite/features/cannonCommons/controller/CannonCommonsCategoryActivity.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDtZuD8WqnB-rSAgDS:-KdDtZuD8WqnB-rSAgDT:b-bxas29) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/31f8712b8a8a90db114d64edab2c0b4d666c525d/app/src/main/java/edu/byu/suite/features/cannonCommons/controller/CannonCommonsCategoryActivity.java#L31)):*
> ```Java
> 
> 		ArrayList<MenuWrapper.Menu.Recipe> recipes = getIntent().getParcelableArrayListExtra(RECIPES);
> 		super.recyclerView.setAdapter(new DefaultRecyclerAdapter<>(
> ```

No switchIfNeeded here?

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDtkvDmNu7papO7ZoB:-KdDtkvDmNu7papO7ZoC:b-80z19o) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/31f8712b8a8a90db114d64edab2c0b4d666c525d/app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java#L16)):*
> ```Java
>  */
> 
> //Todo: make sure messages are in place if they need to be
> ```

TODO?

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java, line 27 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDtjwdsdIaQ1hyrnji:-KdDtjwdsdIaQ1hyrnjj:b32vmt) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/31f8712b8a8a90db114d64edab2c0b4d666c525d/app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java#L27)):*
> ```Java
> 			public void onSuccess(Call<ClassScheduleResponseWrapper> call, retrofit2.Response<ClassScheduleResponseWrapper> response) {
> 				UniversityClassScheduleListActivity.super.recyclerView.setAdapter(getPopulatedAdapter(response.body().getRegOfferingsService().getResponse()));
> 				switchViewIfNeeded("No ");
> ```

??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDucj1kQhBv9Vl7ehD:-KdDucj1kQhBv9Vl7ehE:b-4njhzm) (no related file):*
Why do we only use use the `switchViewIf` method sometimes? Should we always be ready for empty data?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231)*

**Comment by poolguy** [comment]
Review status: 2 of 35 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDu1u1PLoga6r1Gfgo:-KdS5PO0Vb10xcNVv3Be:bb6un1j) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I have an idea. We should make the ByuRecyclerViewActivity an abstract class with a method called `getEmptyDataText()`. Then you would just have to fill in the method rather than always remembering to use the `switchViewIfWhatever` method. Thoughts?
</blockquote></details>

Done

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDucj1kQhBv9Vl7ehD:-KdDvE1xm9BoTTO9ek-V:b-jijbif) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why do we only use use the `switchViewIf` method sometimes? Should we always be ready for empty data?
</blockquote></details>

I only did it if I saw an explicit possibility that the list might be returned empty from the service.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java, line 6 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDtGNhEu2uN97tMZL-:-KdS5nedhfFXgzEdOAtW:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/680205c95b34949b4c5cb30aed5bb401c2f0c73b/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarsMainActivity.java#L6)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Go through each of the files changed and optimize the imports. I don't know if you need these
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/cannonCommons/controller/CannonCommonsCategoryActivity.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDtZuD8WqnB-rSAgDS:-KdSLT3VhQYG0mc6oen8:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/680205c95b34949b4c5cb30aed5bb401c2f0c73b/app/src/main/java/edu/byu/suite/features/cannonCommons/controller/CannonCommonsCategoryActivity.java#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

No switchIfNeeded here?
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java, line 16 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDtkvDmNu7papO7ZoB:-KdSLUQaX7CrGVZZnp0I:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/680205c95b34949b4c5cb30aed5bb401c2f0c73b/app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java#L16)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

TODO?
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java, line 27 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdDtjwdsdIaQ1hyrnji:-KdSLUtkOtu0SNezeBiv:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/680205c95b34949b4c5cb30aed5bb401c2f0c73b/app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231)*

**Comment by romrell4** [comment]
Reviewed 33 of 33 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java, line 25 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdSPVm3uawojCgEh-WI:-KdSPVm48dA7DUsruFbo:b4y26xf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ff044e6ebdedda87d1d1b36a025d74d15199ac1b/app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java#L25)):*
> ```Java
> 			@Override
> 			public void onSuccess(Call<ClassScheduleResponseWrapper> call, retrofit2.Response<ClassScheduleResponseWrapper> response) {
> 				UniversityClassScheduleListActivity.this.setAdapter(getPopulatedAdapter(response.body().getRegOfferingsService().getResponse()));
> ```

See if you can just call setAdapter here

---

*[app/src/main/java/edu/byu/suite/features/departmentDirectory/controller/DepartmentDirectoryMainActivity.java, line 44 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdSQzct5IhJNlfCJ9zr:-KdSQzcuXYUed00FAT4n:bxwv1yl) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ff044e6ebdedda87d1d1b36a025d74d15199ac1b/app/src/main/java/edu/byu/suite/features/departmentDirectory/controller/DepartmentDirectoryMainActivity.java#L44)):*
> ```Java
> 	@Override
> 	protected String getEmptyDataText() {
> 		return "No department information found at this time.\nPlease try again later.";
> ```

Don't use a newline. Just use a space. That way it will only wrap when it needs to

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 78 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdSSU7E-nXIS9-gOCdB:-KdSSU7E-nXIS9-gOCdC:bmo9ua7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ff044e6ebdedda87d1d1b36a025d74d15199ac1b/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L78)):*
> ```Java
> 	}
> 
> 	protected abstract String getEmptyDataText();
> ```

Make non-abstract

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 4 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdSSZr46Aka00LPI-V5:-KdSSZr46Aka00LPI-V6:b-z2r6ri) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ff044e6ebdedda87d1d1b36a025d74d15199ac1b/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L4)):*
> ```Java
> 
> import android.os.Bundle;
> import android.support.v7.widget.RecyclerView;
> ```

Optimize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java, line 25 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdSPVm3uawojCgEh-WI:-KdSTFY0nvWrZgSi3Uam:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ff044e6ebdedda87d1d1b36a025d74d15199ac1b/app/src/main/java/edu/byu/suite/features/classSchedule/UniversityClassScheduleListActivity.java#L25)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

See if you can just call setAdapter here
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/departmentDirectory/controller/DepartmentDirectoryMainActivity.java, line 44 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdSQzct5IhJNlfCJ9zr:-KdSTN2jcvilfa_s-q07:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ff044e6ebdedda87d1d1b36a025d74d15199ac1b/app/src/main/java/edu/byu/suite/features/departmentDirectory/controller/DepartmentDirectoryMainActivity.java#L44)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Don't use a newline. Just use a space. That way it will only wrap when it needs to
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 4 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdSSZr46Aka00LPI-V5:-KdSTZSVEHDp-2s9vfh3:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ff044e6ebdedda87d1d1b36a025d74d15199ac1b/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L4)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Optimize
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java, line 78 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-KdSSU7E-nXIS9-gOCdB:-KdSTgA0F7Teupb_3jMH:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ff044e6ebdedda87d1d1b36a025d74d15199ac1b/support/src/main/java/edu/byu/support/activity/ByuRecyclerViewActivity.java#L78)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make non-abstract
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231)*

**Comment by romrell4** [comment]
Reviewed 16 of 16 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/231#-:-KdSW7AeoDom1wf6ZLIU:bnfp4nl)*

**Pull request merged**
