### PR TITLE
Switched "OK" to android.R.string.ok (and "Cancel"). Closes #360

### LINKED ISSUE #360: We should use android strings
e.g. `android.R.string.ok` is "OK" - we should use that instead of all our oks. There's a few others too

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/363)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 247 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/363#-KfrlugsuP8oWHJiI48B:-KfrlugsuP8oWHJiI48C:bj3kaxp) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/dc0fb8812a94081b5744b373885cc8a3d87ee29f/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L247)):*
> ```Java
> 				dismissProgressDialog();
> 				Log.d(TAG, "onCreateVehicleFailure: " + byuError.getDebugMessage());
> 				alertBuilder.setMessage(byuError.getReadableMessage())
> ```

shouldn't this be doing a showError? Look for these and replace them in this pull request as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/363)*

**Comment by coreywoodfield** [comment]
Review status: 23 of 24 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 247 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/363#-KfrlugsuP8oWHJiI48B:-Kfrvnh2Y1lXDxw1yBP_:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/dc0fb8812a94081b5744b373885cc8a3d87ee29f/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L247)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

shouldn't this be doing a showError? Look for these and replace them in this pull request as well
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/363)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/363)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/363#-:-KfrxxS7sGoiTVqAToTV:bnfp4nl)*

**Pull request merged**
