### PR TITLE
Feature/id card

### PR DESCRIPTION
**Pull request by hammadjaved**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/64)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 273 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgOnAEbDa_Wt25-_3C:-KSgOnAFhnpTs35wMigY:b-xe9lyh) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/AndroidManifest.xml#L273)):*
> ```XML
> 				android:name="requiresLogin"
> 				android:value="true" />
> 			<meta-data
> ```

Need description

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 36 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgOvv4jfCdqY-g1LYf:-KSgOvv4jfCdqY-g1LYg:bz613n0) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L36)):*
> ```Java
> public class IdCardActivity extends ByuActivity {
> 
> 	private Call<ResponseBody> imageRequest;
> ```

Make this List<Call> calls

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 59 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgPkT-xpSpO-NbYgS5:-KSgPkT-xpSpO-NbYgS6:b-yznh4f) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L59)):*
> ```Java
> 	}
> 
> 	private void loadIdCardData() {
> ```

Add api here instead of in onCreate

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 79 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgPn2FV82FCkAszjkG:-KSgPn2FV82FCkAszjkH:b-yznh4f) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L79)):*
> ```Java
> 	}
> 
> 	private void loadImage() {
> ```

Add api here instead of in onCreate

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 98 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgPwZvyVXEeGgYR9m6:-KSgPwZvyVXEeGgYR9m7:b-m1l3yk) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L98)):*
> ```Java
> 
> 	private static Bitmap getBasicIdCardBitmap(final IdCardData data, final Resources res) {
> 		final int whichIdCard = (data.isDtf() ? 0x0002 : 0x0000) | (data.isBeard() ? 0x0001 : 0x0000);
> ```

Simplify the crap out of this

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 117 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgQ3u1X8KQy_bvJ_sy:-KSgQ3u1X8KQy_bvJ_sz:b7w1qop) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L117)):*
> ```Java
> 
> 	private static class IdCardDrawable extends Drawable {
> 		private static final int idw = 690;
> ```

Let's rename these variables to photoWidth/photoHeight

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 143 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgQOaYZsMl37fu8vdp:-KSgQOaYZsMl37fu8vdq:bvnuk7b) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L143)):*
> ```Java
> 		@Override
> 		public void draw(final Canvas canvas) {
> 			final Paint paint = new Paint();
> ```

Needs lots of comments

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 177 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgQYaXiCTACAyRmE4h:-KSgQYaXiCTACAyRmE4i:bt4l403) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L177)):*
> ```Java
> 
> 	@Override
> 	public void onDestroy() {
> ```

This will now just be `for (Call call in calls) { call.cancel() }`

---

*[app/src/main/java/edu/byu/suite/features/idCard/model/IdCardData.java, line 10 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgQo8j8F6FF1jBDOgV:-KSgQo8j8F6FF1jBDOgW:b3da1j1) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/model/IdCardData.java#L10)):*
> ```Java
> public class IdCardData {
> 
> 	@SerializedName("photo_URL")
> ```

Shoot Corey a message asking about the JSON underscore converter

---

*[app/src/main/java/edu/byu/suite/features/idCard/model/IdCardData.java, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgQlX26J12JJ7jw2IX:-KSgQlX3o53exyDnj9aZ:b-16p8lh) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/model/IdCardData.java#L21)):*
> ```Java
> 	private String issueNumber;
> 	private boolean dtf;
> 	@SerializedName("beard")
> ```

Remove this one

---

*[app/src/main/java/edu/byu/suite/features/idCard/model/IdCardWrapper.java, line 8 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgR0PIooEijtslDk0T:-KSgR0PIooEijtslDk0U:b-k0km2x) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/model/IdCardWrapper.java#L8)):*
> ```Java
>  * Created by hammadja on 9/16/16.
>  */
> ```

Remove empty spaces

---

*[app/src/main/java/edu/byu/suite/features/idCard/service/IdCardClient.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgR3OkhojFNpCe2r6R:-KSgR3OkhojFNpCe2r6S:b-nz3tgv) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/service/IdCardClient.java#L18)):*
> ```Java
> 	@Override
> 	public String getBaseUrl() {
> 		return "https://api.byu.edu:/domains/legacy/identity/person/PRO/personidcard/v1/";
> ```

Remove : and trailing /

---

*[app/src/main/java/edu/byu/suite/features/idCard/service/IdCardClient.java, line 32 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgRIjJB3XTXhscEMIW:-KSgRIjJB3XTXhscEMIX:b8pnwcl) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/service/IdCardClient.java#L32)):*
> ```Java
> 
> 	public interface IdCardApi {
> 		@GET("{personId}")
> ```

Add / here

---

*[app/src/main/java/edu/byu/suite/features/idCard/service/ImageExtractionClient.java, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgRScu2GUru_-mjPJF:-KSgRScu2GUru_-mjPJG:b-tvu64g) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/service/ImageExtractionClient.java#L19)):*
> ```Java
> 	@Override
> 	public String getBaseUrl() {
> 		return "https://api.byu.edu/domains/legacy/identity/person/";
> ```

Remove trailing slash here

---

*[app/src/main/java/edu/byu/suite/features/idCard/service/ImageExtractionClient.java, line 34 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgROOaWbJwOYcGO_V5:-KSgROOaWbJwOYcGO_V6:b-bc9u0z) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/service/ImageExtractionClient.java#L34)):*
> ```Java
> 
> 	public interface ByuImageApi {
> 		@GET("idphoto/")
> ```

Put / on the beginning and remove from the end

---

*[app/src/main/res/layout/id_card_activity.xml, line 12 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgRacCV6WnwhdnhEdi:-KSgRacCV6WnwhdnhEdj:b-ufeusa) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/res/layout/id_card_activity.xml#L12)):*
> ```XML
> 		layout="@layout/toolbar" />
> 
> 	<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
> ```

Look into removing this?

---

*[app/src/main/res/layout/id_card_activity.xml, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgRfxyJM2Dg-P6y4rJ:-KSgRfxyJM2Dg-P6y4rK:b-cazdcp) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/res/layout/id_card_activity.xml#L24)):*
> ```XML
> 
> 			<ImageView
> 				android:id="@+id/byu_id_card_qr"
> ```

What is this image?

---

*[app/src/main/res/layout/id_card_activity.xml, line 33 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgRkrTpFUy6LTmAyCH:-KSgRkrTpFUy6LTmAyCI:b30kani) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/res/layout/id_card_activity.xml#L33)):*
> ```XML
> 				android:visibility="gone" />
> 
> 			<Button
> ```

Remove maybe?

---

*[app/src/main/res/values/strings.xml, line 82 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgSENwZPSTvQToLlX4:-KSgSENxzoi-PdnqjDxY:b-zbnjf0) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/res/values/strings.xml#L82)):*
> ```XML
> 	<string name="missing_person">No results found.</string>
> 	<string name="person_out_to_lunch">The server took too long to respond. Please try again later.</string>
> 	<string name="title_activity_id_card">IdCardActivity</string>
> ```

Try removing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64)*

**Comment by romrell4** [comment]
Don't forget next time to push commits at each working state :)

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 143 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgQOaYZsMl37fu8vdp:-KSgpEcxaZXLrbyrB9GH:btixv0j) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L143)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Needs lots of comments
</details>
Awesome comments! Add a new line before each comment to make it more readable.

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 59 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgorXk2_hhGRAaUjHJ:-KSgorXk2_hhGRAaUjHK:b-bluspv) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/dc67ccf1a6e49a91814f7fa431b2d7795b6e6570/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L59)):*
> ```Java
> 		calls.add(api.getIdCardData(personId));
> 		ByuProgressDialog dialog = ByuProgressDialog.createAndShowProgressDialog(this, LOAD_MESSAGE, false);
> 		calls.get(0).enqueue(new ByuCallback<IdCardWrapper>() {
> ```

Look below at comment

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 80 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgomjVfiU6ZjAVkzxt:-KSgomjWTP0qxIuJH-EW:b8nroaz) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/dc67ccf1a6e49a91814f7fa431b2d7795b6e6570/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L80)):*
> ```Java
> 		ImageExtractionClient.ByuImageApi imageApi = (ImageExtractionClient.ByuImageApi) new ByuApiGenerator().createApi(this, new ImageExtractionClient());
> 		calls.add(imageApi.getImageResponse(personId));
> 		calls.get(1).enqueue(new ByuCallback<ResponseBody>() {
> ```

Don't use calls.get(1). Just save it as a local variable first

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 99 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgovsIUUDXlkQCQ02j:-KSgovsIUUDXlkQCQ02k:b-zd56sr) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/dc67ccf1a6e49a91814f7fa431b2d7795b6e6570/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L99)):*
> ```Java
> 		if(data.isBeard() && data.isDtf()){
> 			whichIdCard = 3; //if both dtf and beard
> 		}
> ```

Put the else on the same line as the } (CMD-OPT-L should do this for you). Also, instead of setting whichIdCard to something, just do the logic for is (that is in the case statement)

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 168 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgpNtTFrr-fud1sFEY:-KSgpNtTFrr-fud1sFEZ:b-as5yv6) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/dc67ccf1a6e49a91814f7fa431b2d7795b6e6570/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L168)):*
> ```Java
> 			//Adds the image of the User's Image onto the already drawn idcard base
> 			canvas.drawBitmap(photo, null, new Rect(46, 47, 298, bp), paint);
> 			//sets the text lines to be added to the card
> ```

Capitalize "sets"

---

*[app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java, line 176 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgpZWRaxqR2u2Uyz8x:-KSgpZWRaxqR2u2Uyz8y:b-2swqec) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/dc67ccf1a6e49a91814f7fa431b2d7795b6e6570/app/src/main/java/edu/byu/suite/features/idCard/controller/IdCardActivity.java#L176)):*
> ```Java
> 			//Writes each line in the appropriate location.
> 			for (int i = length; i >= 0; i--) {
> 				canvas.drawText(lines[i], 46f, locationBelowPicture - ((length - i) * lineHeight), paint);
> ```

Let's save all of the "magic numbers" floating around as private static final at the top with good names for what they are used for

---

*[app/src/main/java/edu/byu/suite/features/idCard/service/IdCardClient.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-KSgR3OkhojFNpCe2r6R:-KSgplvCf7ld5fX9UDvJ:bss48g3) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/b5cfa7f56549d8a45fc14060fddc463ea235c29b/app/src/main/java/edu/byu/suite/features/idCard/service/IdCardClient.java#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove : and trailing /
</details>
Remove :

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-:-KSgqAx466e3VEw0nQlJ:b-ji3qt4)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64)*

**Comment by hammadjaved** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64)*

**Comment by romrell4** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/64#-:-KSh7hzYat7Gd-gzlLLw:bnfp4nl)*

**Pull request merged**
