### PR TITLE
Added functionality to ByuMapFragment to include added markers

### PR DESCRIPTION
**Pull request by cwoodfie**
I added the desired functionality to ByuMapFragment and simplified the code in printers a bit. We realized that you can add arbitrary data to a marker using setTag(Object o) so we got rid of the map we had used in printers to keep track of which marker represented which printer.

---
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/60)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSDrbq1BWlCQVHEm2nQ:-KSDrbq1BWlCQVHEm2nR:bi151lr) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8eee98039d425c2463dcd4bf04ffa02d5d79cac7/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L29)):*
> ```Java
> //Override setters at bottom to change default map behavior
> public abstract class ByuMapFragment extends ByuFragment implements OnMapReadyCallback {
> 	private static final int MAP_PADDING = 12;
> ```

Increase a tad

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 47 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSDsETHWUEemdMHHBl1:-KSDsETHWUEemdMHHBl2:bt6u4qj) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8eee98039d425c2463dcd4bf04ffa02d5d79cac7/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L47)):*
> ```Java
> 
> 	// If you've been adding markers using this.addMarker this will zoom to include campus and all the markers
> 	protected void zoomToCampusWithMarkers() {
> ```

Pass through to zoomToMarkers( pass in default )

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 56 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSDsOSg8n78oqWYX0QE:-KSDsOSg8n78oqWYX0QF:be1829k) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8eee98039d425c2463dcd4bf04ffa02d5d79cac7/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L56)):*
> ```Java
> 
> 	// Use this to zoom to include all the markers, but not necessarily all of campus
> 	protected void zoomToMarkersOnly() {
> ```

Take in default locations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSDrbq1BWlCQVHEm2nQ:-KSO6zpGbqTbuQOunINT:bi5on7k) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8eee98039d425c2463dcd4bf04ffa02d5d79cac7/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Increase a tad
</details>
A little bit more ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60)*

**Comment by cwoodfie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 29 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSDrbq1BWlCQVHEm2nQ:-KSOA9qj6bgOrjUpoK_C:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8eee98039d425c2463dcd4bf04ffa02d5d79cac7/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L29)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> A little bit more ;)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSOBN_b1rp2UIc59CoS:-KSOBN_b1rp2UIc59CoT:bq0s93d) (no related file):*
Fix Printers

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 40 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSOAqHo0gO5-8ngLKTf:-KSOAqHo0gO5-8ngLKTg:bauc9fk) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9e2db75afbc4e66302391c4dd88ff159e6481fee/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L40)):*
> ```Java
> 
> 	private GoogleMap map = null;
> 	private static final LatLngBounds campusBounds = new LatLngBounds(new LatLng(40.244190, -111.656089), new LatLng(40.255760, -111.643141));
> ```

Make this CAMPUS_BOUNDS

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 68 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSOAwqXC0dY12mVVyge:-KSOAwqYM6Mf6cbvi9IC:b6zxm51) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9e2db75afbc4e66302391c4dd88ff159e6481fee/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L68)):*
> ```Java
> 		if (markerLocations.size() == 0) {
> 			zoomToCampus();
> 		} else if (markerLocations.size() == 1) {
> ```

Add comment here

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 75 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSOBlAI-CQvCMMMz8GC:-KSOBlAI-CQvCMMMz8GD:b2niaam) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9e2db75afbc4e66302391c4dd88ff159e6481fee/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L75)):*
> ```Java
> 				public void onFinish() {
> 					CameraPosition cameraPosition = map.getCameraPosition();
> 					if (cameraPosition.zoom > 17f) {
> ```

psf

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 100 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSOBtUCdEChD3eUQwiP:-KSOBtUCdEChD3eUQwiQ:bxeljnx) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9e2db75afbc4e66302391c4dd88ff159e6481fee/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L100)):*
> ```Java
> 		}
> 		if (ActivityCompat.checkSelfPermission(getActivity(), Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED) {
> 			if (googleApiClient.isConnected()) {
> ```

Comment here "Probably won't happen first time..."

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 167 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSOC1NL_YkqP0vKZZNL:-KSOC1NMl5UjqvCU2px6:btqou0e) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9e2db75afbc4e66302391c4dd88ff159e6481fee/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L167)):*
> ```Java
> 	@Override
> 	public void onConnected(@Nullable Bundle bundle) {
> 		if (!locationSet && ActivityCompat.checkSelfPermission(getActivity(), Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED) {
> ```

Fix this

---

*[support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java, line 170 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60#-KSOCA7DiHze3RSuMHI4:-KSOCA7DiHze3RSuMHI5:b-r8otvu) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9e2db75afbc4e66302391c4dd88ff159e6481fee/support/src/main/java/edu/byu/support/fragment/ByuMapFragment.java#L170)):*
> ```Java
> 			Location location = LocationServices.FusedLocationApi.getLastLocation(googleApiClient);
> 			if (location != null) {
> 				float[] result = new float[1];
> ```

Comment here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/60)*

**Pull request merged**
