### PR TITLE
Hotfix/parking

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/377)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 688 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/377#-KgtbPoRRysApSk7Yyni:-KgtbPoRRysApSk7Yynj:b2s2ria) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/47ce8d16e2da95aab2cde41869518818a1fac9e8/app/src/main/AndroidManifest.xml#L688)):*
> ```XML
> 			android:label="Add Vehicle"
> 			android:parentActivityName=".features.parking.controller.ParkingMainActivity"
> 			android:windowSoftInputMode="adjustResize" />
> ```

What is this?

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java, line 307 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/377#-KgtbXnwQJJ-e1_9trdw:-KgtbXnwQJJ-e1_9trdx:bdas150) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/47ce8d16e2da95aab2cde41869518818a1fac9e8/app/src/main/java/edu/byu/suite/features/parking/controller/AddVehicleActivity.java#L307)):*
> ```Java
> 
> 				if (data.codeSetId == null) {
> 					if (data.vehicleAttributeTitle.equals(getString(R.string.vehicle_model))) {
> ```

Comment before this if statement about what each of these is doing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/377)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/AndroidManifest.xml, line 688 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/377#-KgtbPoRRysApSk7Yyni:-KgtgYX4n0lV59hS06TQ:bluyzni) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/47ce8d16e2da95aab2cde41869518818a1fac9e8/app/src/main/AndroidManifest.xml#L688)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Instead of moving the activity up just to show whatever text view is in focus, it resizes the whole activity so that it fits above the keyboard. This makes it so you can see the register button and scroll up and down in the list of inputs even when the keyboard is visible
</blockquote></details>

Could you send me a screenshot and/or video of what this looks like (before and after)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/377)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/AndroidManifest.xml, line 688 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/377#-KgtbPoRRysApSk7Yyni:-KgtotQgxPt8UURm8tIU:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/47ce8d16e2da95aab2cde41869518818a1fac9e8/app/src/main/AndroidManifest.xml#L688)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Could you send me a screenshot and/or video of what this looks like (before and after)?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/377)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/377#-:-KgtwlWC8waW5V1QJtWF:bnfp4nl)*

**Pull request merged**
