### PR TITLE
Feature/toggle favorite

### PR DESCRIPTION
**Pull request by romrell4**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/346)

### CODE REVIEW

**Comment by coreywoodfield** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfSa4T2-3pE2UqclZsf:-KfSa4T2-3pE2UqclZsg:bauvd8o) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java#L18)):*
> ```Java
> public class FavoriteToggleIcon extends AppCompatImageView {
> 	private FavoritesManager favoritesManager;
> 	private Feature feature;
> ```

You wouldn't need to save the feature if you pass it in to `setImage()`. Both ways work fine, but just wanted to point it out in case you hadn't realized and would prefer to do it that way.

---

*[support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfSafGDe3GdDT0cJrt0:-KfSafGEANgOlao0aPpb:b3rkhzm) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java#L20)):*
> ```Java
> 	private Feature feature;
> 
> 	public FavoriteToggleIcon(Context context, AttributeSet attrs) {
> ```

If you want Android Studio to recognize this as a view in the xml layout gui, then you need the three view constructors

---

*[support/src/main/java/edu/byu/support/feature/FeatureViewHolder.java, line 33 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfSaT6YRrjqe-o4_ZoK:-KfSaT6YRrjqe-o4_ZoL:b8rujtd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FeatureViewHolder.java#L33)):*
> ```Java
> 		featureIconView.setImageResource(feature.getImageResId());
> 		featureNameView.setText(feature.getName());
> 		featureAddButton.setFeature(feature);
> ```

I would put this in an else of the following if statement. No point setting the feature if you're just gonna remove the image

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java, line 7 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfScmCCdM2Z81GQo8Sg:-KfScmCCdM2Z81GQo8Sh:b7wyhri) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java#L7)):*
> ```Java
> import android.support.v7.widget.AppCompatImageView;
> import android.util.AttributeSet;
> import android.util.Log;
> ```

Also remove unused imports (control + option + o)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346)*

**Comment by coreywoodfield** [comment]
Merge dev again

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-:-KfSd_9WK-rk0Dy7GCdD:b-rau8t4)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java, line 7 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfScmCCdM2Z81GQo8Sg:-KfSg9RK-gvcbjfQiR-7:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java#L7)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Also remove unused imports (control + option + o)
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java, line 18 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfSa4T2-3pE2UqclZsf:-KfSg7rsEmKl6GrGIbxS:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java#L18)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

You wouldn't need to save the feature if you pass it in to `setImage()`. Both ways work fine, but just wanted to point it out in case you hadn't realized and would prefer to do it that way.
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfSafGDe3GdDT0cJrt0:-KfSgBZPK28fRpVDCg6I:b-oek234) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java#L20)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

If you want Android Studio to recognize this as a view in the xml layout gui, then you need the three view constructors
</blockquote></details>

Help me with this one

---

*[support/src/main/java/edu/byu/support/feature/FeatureViewHolder.java, line 33 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfSaT6YRrjqe-o4_ZoK:-KfSgEHDL19HlGn3RLDA:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FeatureViewHolder.java#L33)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

I would put this in an else of the following if statement. No point setting the feature if you're just gonna remove the image
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346)*

**Comment by coreywoodfield** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-KfSafGDe3GdDT0cJrt0:-KfSiBZzmCeVuEdmCebG:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8a837f554ad13411176db3c3c8cc9a60ba46fc80/support/src/main/java/edu/byu/support/feature/FavoriteToggleIcon.java#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Help me with this one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346)*

**Comment by coreywoodfield** [comment]
:lgtm:

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/346#-:-KfSl70Uc_54qk0i-R-G:bnfp4nl)*

**Pull request merged**
