### PR TITLE
Feature/calendar search

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/320)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 82 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/320#-KeuSbciPh8DkzESxe3z:-KeuSbciPh8DkzESxe4-:bn5gdhs) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7da85af0532efcacc76fe46ba7b2f32af55a7093/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L82)):*
> ```Java
> 	@Override
> 	protected String getEmptyDataText() {
> 		return adapter.unfilteredList.isEmpty() ? "No events found for this calendar" : "";
> ```

Can you look into this for all the other ones?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/320)*

**Comment by coreywoodfield** [comment]
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java, line 82 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/320#-KeuSbciPh8DkzESxe3z:-KeuXxjdFOHpyDUblpvs:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7da85af0532efcacc76fe46ba7b2f32af55a7093/app/src/main/java/edu/byu/suite/features/calendars/controller/CalendarActivity.java#L82)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can you look into this for all the other ones?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/320)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/320)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/320#-:-KeuYQssGZFFps4HyKbM:bnfp4nl)*

**Pull request merged**
