### PR TITLE
Made add funds button disappear if the user is not able to add funds

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/195)

### CODE REVIEW

**Comment by coreywoodfield** [comment]
This fixes #188

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/195)*

**Comment by romrell4** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java, line 87 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/195#-Kctp195rzq90NRJqUtI:-Kctp196Fogoir1LryeS:brtq2vo) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8730b8a579a3f437b398c205a96c81df1ecdec56/app/src/main/java/edu/byu/suite/features/cougarCash/controller/CougarCashMainActivity.java#L87)):*
> ```Java
> 				((TextView) findViewById(R.id.balanceText)).setText(NumberFormat.getCurrencyInstance().format(response.body().getBalance()));
> 				if (response.body().isCanAddFunds()) {
> 					addFundsButton.setEnabled(true);
> ```

Here use setVisibility(View.VISIBLE). The button should never be disabled, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/195)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/195)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/195#-:-KcttyfB0oGznanp4RuZ:bnfp4nl)*

**Pull request merged**
