### PR TITLE
Feature/snackbar

### PR DESCRIPTION
**Pull request by coreywoodfield**
this does cool stuff.

"Note: The Snackbar class supersedes Toast. While Toast is currently still supported, Snackbar is now the preferred way to display brief, transient messages to the user." - https://developer.android.com/training/snackbar/index.html

---
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/77)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivity.java, line 154 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUNuVGyYDkZw19FyDyJ:-KUNuVGzziBWz2THo19r:b-s3sbzc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0ac6959be0215803b9c0d3f908e52e6f304e57cf/app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivity.java#L154)):*
> ```Java
> 			Snackbar.make(findViewById(R.id.favorites_container), feature.getName() + " removed from favorites", Snackbar.LENGTH_SHORT)
> 					.setAction("Undo", v -> {
> 						FavoritesUtil.getInstance(FavoritesActivity.this).addFavorite(feature).apply();
> ```

Are we worried about the position that it's inserted at?

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivityBehavior.java, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUNubqYMBerEZSc_-g4:-KUNubqYMBerEZSc_-g5:b32vmt) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0ac6959be0215803b9c0d3f908e52e6f304e57cf/app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivityBehavior.java#L1)):*
> ```Java
> package edu.byu.suite.mainScreen.controller;
> ```

??

---

*[support/src/main/java/edu/byu/support/adapter/ByuRecyclerAdapter.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUNuvbpAIIVBFZbope0:-KUNuvbpAIIVBFZbope1:b32vmt) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0ac6959be0215803b9c0d3f908e52e6f304e57cf/support/src/main/java/edu/byu/support/adapter/ByuRecyclerAdapter.java#L54)):*
> ```Java
> 
> 	public void addAllToList(List<DataType> list) {
> 		int size = this.list.size();
> ```

??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77)*

**Comment by coreywoodfield** [comment]
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivity.java, line 154 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUNuVGyYDkZw19FyDyJ:-KUTYhaFljqrcPutuT8j:b-886gsx) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ad67b7bd442a01818f067b76dad98ba6e38138e6/app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivity.java#L154)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Are we worried about the position that it's inserted at?
</details>
Fixed

---

*[app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivityBehavior.java, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUNubqYMBerEZSc_-g4:-KUTZBRROnqcoSJVQb7e:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ad67b7bd442a01818f067b76dad98ba6e38138e6/app/src/main/java/edu/byu/suite/mainScreen/controller/FavoritesActivityBehavior.java#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> ??
</details>
Done.

---

*[support/src/main/java/edu/byu/support/adapter/ByuRecyclerAdapter.java, line 54 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUNuvbpAIIVBFZbope0:-KUTZDSGkDDNM6GBnMLZ:b-dgvfx8) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/ad67b7bd442a01818f067b76dad98ba6e38138e6/support/src/main/java/edu/byu/support/adapter/ByuRecyclerAdapter.java#L54)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> ??
</details>
These are in calendars too but since that's not on dev yet and i wanted to use (at least one of) them, I added them all here as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77)*

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesUtil.java, line 42 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUTcwAgBI4MP-KhMGNI:-KUTcwAgBI4MP-KhMGNJ:bgoa8t1) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/afba55741f4728e4788499501efa5a610207bf79/app/src/main/java/edu/byu/suite/mainScreen/FavoritesUtil.java#L42)):*
> ```Java
> 
>     public FavoritesUtil addFavorite(Feature feature) {
>         feature.setFavorite(true);
> ```

Do we not need to do this anymore?

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesUtil.java, line 48 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUTcuTnHuaKikzFMfdG:-KUTcuTnHuaKikzFMfdH:brn2f9g) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/afba55741f4728e4788499501efa5a610207bf79/app/src/main/java/edu/byu/suite/mainScreen/FavoritesUtil.java#L48)):*
> ```Java
> 
>     public FavoritesUtil removeFavorite(Feature feature) {
>         feature.setFavorite(false);
> ```

Do you not need to do this anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesUtil.java, line 42 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUTcwAgBI4MP-KhMGNI:-KUTeNCZ6MvH10RNCYB0:b7u03hh) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/afba55741f4728e4788499501efa5a610207bf79/app/src/main/java/edu/byu/suite/mainScreen/FavoritesUtil.java#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Do we not need to do this anymore?
</details>
Correct

---

*[app/src/main/java/edu/byu/suite/mainScreen/FavoritesUtil.java, line 48 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-KUTcuTnHuaKikzFMfdG:-KUTeOE0QHPkYFNjwA5Q:b7u03hh) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/afba55741f4728e4788499501efa5a610207bf79/app/src/main/java/edu/byu/suite/mainScreen/FavoritesUtil.java#L48)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Do you not need to do this anymore?
</details>
Correct

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/77#-:-KUTeTobLpsmUPJ-i6x2:bnfp4nl)*

**Pull request merged**
