### PR TITLE
Hotfix/ls

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/136)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/136#-Kbv_-OPv0ahkIWoFGTB:-Kbv_-OQA18qD7x6EGlY:byp18fd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/58884096146f75de29281ec69e1eb636c52c60d1/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L28)):*
> ```Java
>  */
> public abstract class ByuActivity extends AppCompatActivity implements ByuCallManager {
> 	private static final String TAG = ByuActivity.class.getSimpleName();
> ```

Remove

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 66 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/136#-Kbv_BDP-84txuQp_vzv:-Kbv_BDQVSMBgHxVU2IB:bvpks9s) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f7907cfd0ca03296b5a997bf46777ba4c89ebd89/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L66)):*
> ```Java
> 			return view;
> 		} else {
> 			throw new NullPointerException("Retrieval of the specified resource returned null");
> ```

Keep this, but change the error case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/136)*

**Comment by coreywoodfield** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/136#-Kbv_-OPv0ahkIWoFGTB:-Kbva8wBvNRxlTQ-S9sm:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/58884096146f75de29281ec69e1eb636c52c60d1/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 66 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/136#-Kbv_BDP-84txuQp_vzv:-Kbva9Q6NGmS_GT7nBMK:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f7907cfd0ca03296b5a997bf46777ba4c89ebd89/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L66)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Keep this, but change the error case
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/136)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/136)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/136#-:-KbvaMQVwtlGyUSDp9ZS:bnfp4nl)*

**Pull request merged**
