### PR TITLE
Updated sick/vac error message to make more sense. Resolves #164

### LINKED ISSUE #164: Sick/Vacation Balances: Crashing
Name of Tester: Seth
Feature: Cougar Cash

How to produce error:
Not certain if it's just the phone I'm using, but the feature crashes every time I open it

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/187)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/sickVacation/controller/SickVacationMainActivity.java, line 43 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187#-KceOnRn-z69iuSAZyox:-KceOnRo6CIOEpDcZFEl:b-6rsv63) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6ccf6c816fb2cf711c7fb2714dc88998b4ea7892/app/src/main/java/edu/byu/suite/features/sickVacation/controller/SickVacationMainActivity.java#L43)):*
> ```Java
> 			public void onFailure(Call<LeaveDataWrapper> call, ByuError byuError) {
> 				dismissProgressDialog();
> 				showErrorDialog("No sick/vacation balances were found.");
> ```

Check out what the debug message is (and the throwable)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187)*

**Comment by coreywoodfield** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/sickVacation/controller/SickVacationMainActivity.java, line 43 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187#-KceOnRn-z69iuSAZyox:-KceRSjPTEdhUZLET5c9:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6ccf6c816fb2cf711c7fb2714dc88998b4ea7892/app/src/main/java/edu/byu/suite/features/sickVacation/controller/SickVacationMainActivity.java#L43)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check out what the debug message is (and the throwable)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/sickVacation/controller/SickVacationMainActivity.java, line 44 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187#-KceRgioRCeg2wZS9ydX:-KceRgioRCeg2wZS9ydY:b-63eatr) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7ddc02e45ef9b1069c2f6e36357bdd1bcc60be71/app/src/main/java/edu/byu/suite/features/sickVacation/controller/SickVacationMainActivity.java#L44)):*
> ```Java
> 			public void onFailure(Call<LeaveDataWrapper> call, ByuError byuError) {
> 				dismissProgressDialog();
> 				if (byuError.getThrowable() != null && byuError.getThrowable() instanceof JsonParseException) {
> ```

Comment what this means (and why the stupid service does it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187)*

**Comment by coreywoodfield** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/sickVacation/controller/SickVacationMainActivity.java, line 44 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187#-KceRgioRCeg2wZS9ydX:-KceTFenbxku07YKBKRE:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7ddc02e45ef9b1069c2f6e36357bdd1bcc60be71/app/src/main/java/edu/byu/suite/features/sickVacation/controller/SickVacationMainActivity.java#L44)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment what this means (and why the stupid service does it)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/187#-:-KceTHmXxSHu4DCkbnfH:bnfp4nl)*

**Pull request merged**
