### PR TITLE
Fix/galleriesquality

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/206)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 2 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 56 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD1PAsUVFni35BdVIg:-KdD1PAt4zsMIRpqUYpM:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5ba3db787193d2409eb85c3a6ff77ead91cb14f1/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L56)):*
> ```Java
> 			public void onSuccess(Call<ArtworkResponseWrapper> call, Response<ArtworkResponseWrapper> response) {
> 				artworkList = response.body().getArtworkList();
> 				GridView gridView = (GridView) findViewById(R.id.gridView);
> ```

Comment

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 47 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD29Oo9AU0gHQHgBiD:-KdD29Oo9AU0gHQHgBiE:byp18fd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5ba3db787193d2409eb85c3a6ff77ead91cb14f1/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L47)):*
> ```Java
> 		((TextView) view.findViewById(R.id.descriptionText)).setText(artwork.getDescription());
> 
> 		view.setOnClickListener(view1 -> descriptionLayout.setVisibility(visibility = visibility == View.GONE ? View.VISIBLE : View.GONE));
> ```

Remove

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 55 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD2KmA_6F2n91SRbFr:-KdD2KmA_6F2n91SRbFs:b7r5xui) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5ba3db787193d2409eb85c3a6ff77ead91cb14f1/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L55)):*
> ```Java
> 	@Override
> 	public View getView() {
> 		descriptionLayout.setVisibility(visibility);
> ```

Comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206)*

**Comment by coreywoodfield** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 56 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD1PAsUVFni35BdVIg:-KdD2z4T0pB8lX4NXbQG:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5ba3db787193d2409eb85c3a6ff77ead91cb14f1/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L56)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 47 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD29Oo9AU0gHQHgBiD:-KdD30CKHY14RUkZVgwI:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5ba3db787193d2409eb85c3a6ff77ead91cb14f1/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L47)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 55 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD2KmA_6F2n91SRbFr:-KdD3Atb4zfxoEexr6es:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5ba3db787193d2409eb85c3a6ff77ead91cb14f1/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L55)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 47 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD29Oo9AU0gHQHgBiD:-KdD46JhmhiYPWNOU8Mo:bo7qxtn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5ba3db787193d2409eb85c3a6ff77ead91cb14f1/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L47)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Try again please :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 47 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD29Oo9AU0gHQHgBiD:-KdD4h2qQPzsBVbdV37y:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/5ba3db787193d2409eb85c3a6ff77ead91cb14f1/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L47)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Try again please :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 48 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD50xfpvo9I6W5n3C_:-KdD50xfpvo9I6W5n3Ca:bot9y4x) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d182d7c9f0565dce49b56581e46ea7a774efc08f/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L48)):*
> ```Java
> 
> 		view.setOnClickListener(v -> {
> 			visibility = visibility == View.GONE ? View.VISIBLE : View.GONE
> ```

Parenthesis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206)*

**Comment by coreywoodfield** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 48 at r4](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-KdD50xfpvo9I6W5n3C_:-KdD5MJlMX-OkFs7fyMi:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/d182d7c9f0565dce49b56581e46ea7a774efc08f/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L48)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Parenthesis
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/206#-:-KdD5WIa7AHttJq3jQv2:bnfp4nl)*

**Pull request merged**
