### PR TITLE
Hotfix/vending

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/131)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 38 of 38 files at r1.
Review status: 36 of 38 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMjiRP8Kbt-yjOQ_Vo:-KbMjiRP8Kbt-yjOQ_Vp:b3bmlp6) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c35095000c72b558ff8b9f2aeac834ccf65c4222/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java#L23)):*
> ```Java
> 
> 	public static final String MAP_TYPE_KEY = "MapType";
> 	public static final int MACHINE_KEY = 0;
> ```

Do you prefer ints over an enum?

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMjs2OydpE5NgDTCsw:-KbMjs2OydpE5NgDTCsx:b-9l8bdt) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/019801db37c7a0e81731b11aa9a9e9aa69c0d7de/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java#L77)):*
> ```Java
> 
> 	@Override
> 	public boolean onOptionsItemSelected(MenuItem item) { //This is used to send the user from one directory to the older one rather then to the parent.
> ```

directory? Is this comment copied and pasted?

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapFragment.java, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMkKVaIShwdfELPdtv:-KbMkKVaIShwdfELPdtw:byp1ktf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c35095000c72b558ff8b9f2aeac834ccf65c4222/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapFragment.java#L15)):*
> ```Java
> 
> public class VendingMapFragment extends ByuMapFragment {
> 	public static final String VENDING_ELEMENTS = "vendingElements";
> ```

Rename

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapFragment.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMkr5tcuM4n34MSEjP:-KbMkr5tcuM4n34MSEjQ:b-r8h40s) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c35095000c72b558ff8b9f2aeac834ccf65c4222/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapFragment.java#L41)):*
> ```Java
> 			// After the service is fixed and has lats and lngs for all vending machines, this if statement will be unnecessary
> 			if (machine.getLat() != null && machine.getLng() != null) {
> 				addMarker(new MarkerOptions().position(new LatLng(machine.getLat(), machine.getLng())).title(machine.getDescription()), machine);
> ```

Comment this

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingProductsActivity.java, line 61 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMlJIRdHQSHaLxnbay:-KbMlJISaDTZfSlcRk7_:b-2g6efl) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c35095000c72b558ff8b9f2aeac834ccf65c4222/app/src/main/java/edu/byu/suite/features/vending/controller/VendingProductsActivity.java#L61)):*
> ```Java
> 			});
> 		} else {
> 			getSupportActionBar().setTitle("Products");
> ```

Did we just not have this before? Was there a null title?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java, line 23 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMjiRP8Kbt-yjOQ_Vo:-KbMtLGnl8IHYYi-a4tK:bvn4y7d) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c35095000c72b558ff8b9f2aeac834ccf65c4222/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you prefer ints over an enum?
</blockquote></details>

In this case, when they're being put into an intent as extras, yes. For an enum you have to use intent.getSerializableExtra but for an int you can just use getIntegerExtra. I figured that was better

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMjs2OydpE5NgDTCsw:-KbMt_LPCP6DtvyqtzPk:bcpho6i) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/019801db37c7a0e81731b11aa9a9e9aa69c0d7de/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java#L77)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

directory? Is this comment copied and pasted?
</blockquote></details>

Probably. It's Hammad's comment, not mine

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapFragment.java, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMkKVaIShwdfELPdtv:-KbMtuvSbu_1AFkOTG4B:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c35095000c72b558ff8b9f2aeac834ccf65c4222/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapFragment.java#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Rename
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapFragment.java, line 41 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMkr5tcuM4n34MSEjP:-KbMtz_x4e7ApIBkNDvT:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c35095000c72b558ff8b9f2aeac834ccf65c4222/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapFragment.java#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment this
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingProductsActivity.java, line 61 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMlJIRdHQSHaLxnbay:-KbMu3WfA291vpo92y83:b-l52he6) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/c35095000c72b558ff8b9f2aeac834ccf65c4222/app/src/main/java/edu/byu/suite/features/vending/controller/VendingProductsActivity.java#L61)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Did we just not have this before? Was there a null title?
</blockquote></details>

No, Hammad passed in a category that only had a title, which I thought was silly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMjs2OydpE5NgDTCsw:-KbMziDxungGZS5PXQ8o:b-hxp66a) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/019801db37c7a0e81731b11aa9a9e9aa69c0d7de/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java#L77)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

Probably. It's Hammad's comment, not mine
</blockquote></details>

Go ahead and fix it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131)*

**Comment by coreywoodfield** [comment]
Review status: 37 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java, line 77 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-KbMjs2OydpE5NgDTCsw:-KbN-NEdqfyDqPQ0Fslc:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/019801db37c7a0e81731b11aa9a9e9aa69c0d7de/app/src/main/java/edu/byu/suite/features/vending/controller/VendingMapActivity.java#L77)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Go ahead and fix it :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/131#-:-KbN-rgLSuS4MBZhZI0c:bnfp4nl)*

**Pull request merged**
