### PR TITLE
Fixes #172. click listener now either opens the next activity or sets…

### LINKED ISSUE #172: Galleries - NullPointerException
I clicked on one of the images in 'Past Exhibitions' in the MOA gallery and got a null pointer exception:

```
java.lang.NullPointerException
    at edu.byu.support.utils.BitmapUtils.compressBitmapToByteArray(BitmapUtils.java:95)
    at edu.byu.suite.features.galleries.model.ArtworkResponseWrapper$Artwork.writeToParcel(ArtworkResponseWrapper.java:96)
    at android.os.Parcel.writeParcelable(Parcel.java:1285)
    ...
    at edu.byu.suite.features.galleries.controller.AlbumActivity$ImageAdapter.lambda$-edu_byu_suite_features_galleries_controller_AlbumActivity$ImageAdapter_lambda$1(AlbumActivity.java:129)
    at edu.byu.suite.features.galleries.controller.-$Lambda$261.$m$0(Unknown Source)
    at edu.byu.suite.features.galleries.controller.-$Lambda$261.onClick(Unknown Source)
```

### PR DESCRIPTION
**Pull request by coreywoodfield**
… a flag to open it when ready

---
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/182)

### CODE REVIEW

**Comment by romrell4** [comment]
Why was this one needed?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/182#-:-KcZ-wxdIsQtUvJzGwTc:bq2o05e)*

**Comment by romrell4** [comment]
Got it

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 109 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/182#-KcdTql-XD3N9WvMGlS8:-KcdTql-XD3N9WvMGlS9:b-p714yn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/51482624f261853c74b63f27db046574f7089d1b/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L109)):*
> ```Java
> 			startActivity(new Intent(this, ArtworkActivity.class).putParcelableArrayListExtra(ArtworkActivity.ARTWORK_LIST, artworkList).putExtra(ArtworkActivity.POSITION, position));
> 		} else {
> 			startArtworkActivityAtPosition = position;
> ```

This method of fixing this error is cool, but I think I would prefer just making it non-clickable. Or not populating the collection view until the data comes back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/182#-:-KcdULdLsf3jFjY2PeaB:btn461w)*

**Comment by coreywoodfield** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 109 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/182#-KcdTql-XD3N9WvMGlS8:-Kcdg1KZ2gLjR02S2aII:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/51482624f261853c74b63f27db046574f7089d1b/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L109)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This method of fixing this error is cool, but I think I would prefer just making it non-clickable. Or not populating the collection view until the data comes back
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/182)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/182)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/182#-:-Kcdgm2ffZykNBNGLbvn:bnfp4nl)*

**Pull request merged**
