### PR TITLE
Feature/person json

### PR DESCRIPTION
**Pull request by cwoodfie**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/58)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/model/Person.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRowE5sgLodYP6uMg0h:-KRowE5sgLodYP6uMg0i:b-p9tzlc) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/model/Person.java#L31)):*
> ```Java
> 		personId = in.readString();
> 		email = in.readString();
> 		homeAddressBlock = in.readParcelable(Address.class.getClassLoader());
> ```

Add a comment here as well

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRouZK9pb-oGSGwTnLx:-KRouZK9pb-oGSGwTnLy:b1lx3xu) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java#L24)):*
> ```Java
> 
> 	@Override
> 	public void write(JsonWriter out, Address value) throws IOException {
> ```

Comment here explaining that we currently don't use this, but the code should work

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java, line 66 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRoumTSM3UaHoCFWqVw:-KRoumTSM3UaHoCFWqVx:bkdjtpj) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java#L66)):*
> ```Java
> 		}
> 		List<String> addressLines = new ArrayList<>(4);
> 		for (in.nextName(); in.peek() == JsonToken.STRING; in.nextName()) {
> ```

Combine with while loop

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java, line 79 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRoueNldpBBEqWqWiWT:-KRoueNldpBBEqWqWiWU:b-wf5q3r) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java#L79)):*
> ```Java
> 		String address = addressLines.isEmpty() ? null : TextUtils.join("\n", addressLines);
> 
> 		while (in.hasNext()) {
> ```

Comment before this explaining that you have to read the full JSON object before in.endObject()

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java, line 84 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRov7YGNuVxq_LsCyDf:-KRov7YGNuVxq_LsCyDg:b5x5yfq) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java#L84)):*
> ```Java
> 		in.endObject();
> 
> 		return address == null && phone == null ? null : new Address(address, phone);
> ```

Change this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58)*

**Comment by cwoodfie** [comment]
Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/model/Person.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRowE5sgLodYP6uMg0h:-KRp5LDQL8VU1vTv-YLl:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/model/Person.java#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Add a comment here as well
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java, line 24 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRouZK9pb-oGSGwTnLx:-KRp5XV5yRcGDuynDOln:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment here explaining that we currently don't use this, but the code should work
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java, line 66 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRoumTSM3UaHoCFWqVw:-KRp5ZzcAePyItC0HxQg:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java#L66)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Combine with while loop
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java, line 79 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRoueNldpBBEqWqWiWT:-KRp5ZUmmnWEndYVsoC0:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Comment before this explaining that you have to read the full JSON object before in.endObject()
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java, line 84 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-KRov7YGNuVxq_LsCyDf:-KRp5d50OVlUHfVYUP4g:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/7739b525500d852e4cfdb89e4ff97da4a3a39795/app/src/main/java/edu/byu/suite/features/personDirectory/service/AddressTypeAdapter.java#L84)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Change this?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/58#-:-KRp82vBC9o0_ul3MGOK:bnfp4nl)*

**Pull request merged**
