### PR TITLE
Added Lab Computers feature

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/102)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 342 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102#-KXhAq0UsURgcz5eBGl7:-KXhAq0UsURgcz5eBGl8:b-tdvmp2) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6113ecd92fad428b0ec9db9c33469dabd4b12b4d/app/src/main/AndroidManifest.xml#L342)):*
> ```XML
> 			<meta-data
> 					android:name="description"
> 					android:value="Find available on-campus computers." />
> ```

Get iOS description

---

*[app/src/main/java/edu/byu/suite/features/labComputers/controller/LabComputersMainActivity.java, line 42 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102#-KXhB6IJSn9-S29vc0BP:-KXhB6IJSn9-S29vc0BQ:b-c85yqs) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6113ecd92fad428b0ec9db9c33469dabd4b12b4d/app/src/main/java/edu/byu/suite/features/labComputers/controller/LabComputersMainActivity.java#L42)):*
> ```Java
> 				for (Building building : buildings) {
> 					int available = 0;
> 					for (Building.Room room : building.getRooms()) {
> ```

We might be able to do this with a filter (if it makes it simpler). Then you can just use the length of the resulting list

---

*[app/src/main/java/edu/byu/suite/features/labComputers/service/LabComputersClient.java, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102#-KXhBglhwL_eA5MeKNlu:-KXhBglhwL_eA5MeKNlv:b-f1bgtg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6113ecd92fad428b0ec9db9c33469dabd4b12b4d/app/src/main/java/edu/byu/suite/features/labComputers/service/LabComputersClient.java#L17)):*
> ```Java
> 	@Override
> 	public String getBaseUrl() {
> 		return "http://open-computers.lib.byu.edu/";
> ```

I believe there is a WSO2 url for this one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102)*

**Comment by coreywoodfield** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/labComputers/controller/LabComputersMainActivity.java, line 42 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102#-KXhB6IJSn9-S29vc0BP:-KXhHO2-1-6kie2hu4_N:bjtyqsq) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6113ecd92fad428b0ec9db9c33469dabd4b12b4d/app/src/main/java/edu/byu/suite/features/labComputers/controller/LabComputersMainActivity.java#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We might be able to do this with a filter (if it makes it simpler). Then you can just use the length of the resulting list
</blockquote></details>

I don't understand

---

*[app/src/main/java/edu/byu/suite/features/labComputers/service/LabComputersClient.java, line 17 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102#-KXhBglhwL_eA5MeKNlu:-KXhHJPz9aIPBZ18gV6x:b-4qijp1) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6113ecd92fad428b0ec9db9c33469dabd4b12b4d/app/src/main/java/edu/byu/suite/features/labComputers/service/LabComputersClient.java#L17)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I believe there is a WSO2 url for this one
</blockquote></details>

Yeah but this is a web view

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102)*

**Comment by romrell4** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 342 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102#-KXhAq0UsURgcz5eBGl7:-KXhHiA2n8HSiyuSu8K_:b84npwg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6113ecd92fad428b0ec9db9c33469dabd4b12b4d/app/src/main/AndroidManifest.xml#L342)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Get iOS description
</blockquote></details>

"BYU offers free use of lab computers in select buildings around campus. This feature will help you find available lab computers."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102)*

**Comment by romrell4** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102)*

**Comment by coreywoodfield** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/AndroidManifest.xml, line 342 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102#-KXhAq0UsURgcz5eBGl7:-KXhJEos6c1gRE3NXw4A:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/6113ecd92fad428b0ec9db9c33469dabd4b12b4d/app/src/main/AndroidManifest.xml#L342)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

"BYU offers free use of lab computers in select buildings around campus. This feature will help you find available lab computers."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/102#-:-KXhJMtlB2zAO8-fp26S:bnfp4nl)*

**Pull request merged**
