### PR TITLE
Feature/call me maybe

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/70)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 71 of 71 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVsIUkXHFJG0wUaEeB:-KTVsIUkXHFJG0wUaEeC:b-edm2ty) (no related file):*
Look for warnings

---

*[app/src/main/java/edu/byu/suite/features/campusBuildings/controller/CampusBuildingMainActivity.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVraVhaxOu_GZulTmR:-KTVraVhaxOu_GZulTmS:bc4lrne) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/app/src/main/java/edu/byu/suite/features/campusBuildings/controller/CampusBuildingMainActivity.java#L45)):*
> ```Java
> 		setContentView(R.layout.campus_building_activity_main);
> 
> 		adapter = new CampusBuildingAdapter(null);
> ```

Move up top

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/PreviousVehiclesActivity.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVsl-nkeRUVjUeiT4k:-KTVsl-o_ZxZp9EJ4ZIQ:b-w11noq) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/app/src/main/java/edu/byu/suite/features/parking/controller/PreviousVehiclesActivity.java#L31)):*
> ```Java
> 
> public class PreviousVehiclesActivity extends ByuActivity {
> 	private static final String TAG = PreviousVehiclesActivity.class.getSimpleName();
> ```

Make everyone do this!!!

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScheduleFragment.java, line 87 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVtRgApqrHZboV2_J8:-KTVtRgApqrHZboV2_J9:bukk0la) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScheduleFragment.java#L87)):*
> ```Java
> 			@Override
> 			public void onFailure(Call<Hours> call, ByuError byuError) {
> 				activity.showErrorDialog(byuError.getReadableMessage());
> ```

Inline

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 137 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVtmpkZTCkQfZ9_4XG:-KTVtmpkZTCkQfZ9_4XH:b22lvnq) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L137)):*
> ```Java
> 	public void addCall(Call call) {
> 		calls.add(call);
> 		Log.d(TAG, "addCall: adding Call " + call.request().toString());
> ```

Remove logs

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 147 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVtzZFClDSB8bQFmHq:-KTVtrh4XKKJjZ3QvSo0:bukqgb6) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L147)):*
> ```Java
> 
> 	@Override
> 	public void cancelCall(Call call) {
> ```

Add javadoc

---

*[support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java, line 146 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVuEJy8Vy9bX0xJcME:-KTVuEJy8Vy9bX0xJcMF:b5x5yfq) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java#L146)):*
> ```Java
> 	protected void loadImage() {
> 		if (!cameraFeedRequest.isExecuted()) {
> 			((ByuActivity) getActivity()).addCall(cameraFeedRequest);
> ```

Change this?

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVuRjdmiIAWEuVKtp3:-KTVuRjdmiIAWEuVKtp4:b-bdp9fg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L15)):*
> ```Java
>  */
> public abstract class ByuFragment extends Fragment implements ByuCallManager {
> 	private Set<Call> calls = new HashSet<>(2);
> ```

Move to ByuCallManager as 5?

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallManager.java, line 11 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVugBcrExRstnXb5ug:-KTVugBcrExRstnXb5uh:b1kpvgn) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/retrofit/ByuCallManager.java#L11)):*
> ```Java
> public interface ByuCallManager {
> 	// Add a call to a collection of calls, to cancel in onDestroy
> 	void addCall(Call call);
> ```

Make these javadocs

---

*[support/src/test/java/edu/byu/support/ExampleUnitTest.java, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVunOhnvWJkFL8izks:-KTVunOhnvWJkFL8izkt:b22quet) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/test/java/edu/byu/support/ExampleUnitTest.java#L1)):*
> ```Java
> package edu.byu.support;
> ```

Remove this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70)*

**Comment by coreywoodfield** [comment]
Review status: 63 of 71 files reviewed at latest revision, 10 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/campusBuildings/controller/CampusBuildingMainActivity.java, line 45 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVraVhaxOu_GZulTmR:-KTVvQVj1W-Na_QAeHEZ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/app/src/main/java/edu/byu/suite/features/campusBuildings/controller/CampusBuildingMainActivity.java#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Move up top
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/PreviousVehiclesActivity.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVsl-nkeRUVjUeiT4k:-KTVvY6uo0hrT1N_g1XL:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/app/src/main/java/edu/byu/suite/features/parking/controller/PreviousVehiclesActivity.java#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Make everyone do this!!!
</details>
Done.

---

*[app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScheduleFragment.java, line 87 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVtRgApqrHZboV2_J8:-KTVvcziqR5gxT1bFyzu:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/app/src/main/java/edu/byu/suite/features/testingcenter/controller/ScheduleFragment.java#L87)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Inline
</details>
Done.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 137 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVtmpkZTCkQfZ9_4XG:-KTVvs3jNdHqV13Ui8pH:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L137)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove logs
</details>
Done.

---

*[support/src/main/java/edu/byu/support/activity/ByuActivity.java, line 147 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVtzZFClDSB8bQFmHq:-KTVwzCGZ3yTq07O64if:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/activity/ByuActivity.java#L147)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Add javadoc
</details>
Done.

---

*[support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java, line 146 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVuEJy8Vy9bX0xJcME:-KTVx7R5navdOQ4gFD8Q:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java#L146)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Change this?
</details>
Done.

---

*[support/src/main/java/edu/byu/support/fragment/ByuFragment.java, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVuRjdmiIAWEuVKtp3:-KTVx8EHNGWuc8-hIoi8:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/fragment/ByuFragment.java#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Move to ByuCallManager as 5?
</details>
Done.

---

*[support/src/main/java/edu/byu/support/retrofit/ByuCallManager.java, line 11 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVugBcrExRstnXb5ug:-KTVxBPE09dABTC0bS48:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/main/java/edu/byu/support/retrofit/ByuCallManager.java#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Make these javadocs
</details>
Done.

---

*[support/src/test/java/edu/byu/support/ExampleUnitTest.java, line 1 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVunOhnvWJkFL8izks:-KTVxNNYOFdM4S8X3mqh:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/support/src/test/java/edu/byu/support/ExampleUnitTest.java#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary>
> Remove this
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70)*

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/parking/controller/PreviousVehiclesActivity.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-KTVsl-nkeRUVjUeiT4k:-KTVyTPDV1pwTETSWT2A:bqr47tf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/4dfd6db277ed185e8f14f3d93f922b5ae3382948/app/src/main/java/edu/byu/suite/features/parking/controller/PreviousVehiclesActivity.java#L31)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary>
> Done.
</details>
Almost

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70)*

**Comment by romrell4** [comment]
Reviewed 18 of 18 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/70#-:-KTW0QZOX-AGcj6KrmQa:bnfp4nl)*

**Pull request merged**
