### PR TITLE
Hotfix/galleries

### PR DESCRIPTION
**Pull request by poolguy**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/265)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 113 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Kdmj7h65QR2OkUqhXBE:-Kdmj7h65QR2OkUqhXBF:b9ro5zl) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L113)):*
> ```Java
> 						artworkList.remove(artwork);
> 					}
> 					imageAdapter.notifyDataSetChanged();
> ```

Do what we talked about here (notify only the item and call switchIfNeeded)

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 180 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-KdmjF__s7JWRiyc81s3:-KdmjF__s7JWRiyc81s4:byp18fd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L180)):*
> ```Java
> 		}
> 
> 		@Override
> ```

Remove

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-KdmjOkx4FNjB2B1bWso:-KdmjOkx4FNjB2B1bWsp:bhofei7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L21)):*
> ```Java
> 
> public class ArtworkFragment extends Fragment {
> 	public static final String POSITION = "position";
> ```

Delete?

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 30 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-KdmjMWVRjKfyISIb2Hw:-KdmjMWVRjKfyISIb2Hx:b2nhlry) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L30)):*
> ```Java
> 		ArtworkFragment fragment = new ArtworkFragment();
> 		Bundle args = new Bundle();
> 		args.putParcelable("artwork", artwork);
> ```

PSF

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-KdmjUlcw5wcXrQYyn5v:-KdmjUlcw5wcXrQYyn5w:b-708su2) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L57)):*
> ```Java
> 		});
> 
> 		((ViewSwitcher) view.findViewById(R.id.viewSwitcher)).setDisplayedChild(artwork.getBitmap() == null ? 0 : 1);
> ```

Can't you do this above in the if statement you already wrote?

---

*[app/src/main/res/layout/galleries_artwork_card.xml, line 34 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Kdmjs-HhlqzMUCD1qp8:-Kdmjs-HhlqzMUCD1qp9:b-t37o3z) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/res/layout/galleries_artwork_card.xml#L34)):*
> ```XML
> 	</ViewSwitcher>
> 
> 	
> ```

Change to match old TODO: "Todo: make this ripple work on v21+ devices"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265)*

**Comment by poolguy** [comment]
Review status: 5 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 113 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Kdmj7h65QR2OkUqhXBE:-Ke52FmhPo3JBuNNKW-s:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L113)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do what we talked about here (notify only the item and call switchIfNeeded)
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 180 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-KdmjF__s7JWRiyc81s3:-Ke52I6mb7ydSM4VqcWL:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L180)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 21 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-KdmjOkx4FNjB2B1bWso:-Ke52UuvlsYnpy4r6xOI:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Delete?
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 30 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-KdmjMWVRjKfyISIb2Hw:-Ke52VB9dtka6j4Odv2X:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L30)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

PSF
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265)*

**Comment by romrell4** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 121 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5JQLOT0Va8belSW5m:-Ke5JQLQSuICp6pbpjKE:bmfkcy5) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L121)):*
> ```Java
> 					}
> 
> 					int index = artworkList.indexOf(artwork);
> ```

inline it if we can't use it for the imageAdapter as well

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 66 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5K85t_v-zkPKxYPpS:-Ke5K85t_v-zkPKxYPpT:b8gluqf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L66)):*
> ```Java
> 	public View getView() {
> 		// This gets called consistently when the fragment comes into view, other methods are not. We use this one to make sure they all have the same visibility
> 		if (descriptionLayout != null) {
> ```

Why did you need to add this? When would it be null?

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 73 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5KArBZ-Fngvx42iSU:-Ke5KArBZ-Fngvx42iSV:b8gluqf) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L73)):*
> ```Java
> 
> 	public void switchViewsIfNeeded() {
> 		if (getView() != null) {
> ```

Why did you need to add this? When would it be null?

---

*[app/src/main/res/layout/galleries_activity_album.xml, line 18 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5KHQ_vZFIoO8920Ei:-Ke5KHQ_vZFIoO8920Ej:bf7b7i2) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/res/layout/galleries_activity_album.xml#L18)):*
> ```XML
> 		android:layout_width="match_parent"
> 		android:layout_height="match_parent"
> 		android:layout_below="@id/toolbar" >
> ```

CMD-OPT-L

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 121 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5JQLOT0Va8belSW5m:-Ke5QeoMcWnLCbroGKMZ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L121)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

inline it if we can't use it for the imageAdapter as well
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 57 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-KdmjUlcw5wcXrQYyn5v:-Ke5Qz_XyOJFF04Uh05h:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can't you do this above in the if statement you already wrote?
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 66 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5K85t_v-zkPKxYPpS:-Ke5UFTwk4sw-BKGBKvB:b-tyksyp) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L66)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did you need to add this? When would it be null?
</blockquote></details>

This needs to be checked for the same reason as the comment below. switchViewsIfNeeded calls getView()

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 73 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5KArBZ-Fngvx42iSU:-Ke5StOqxx6_RsQOl9Dx:b-mq7ijh) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did you need to add this? When would it be null?
</blockquote></details>

It appears that it is null sometimes because "onCreateView()" is not called immediately after newInstance(). It appears that onCreateView() is only called when the fragment is going to be shown. Not exactly sure why the pagerAdapter handles it this way, I only know that it does. 

Therefore, when we call "notifyItemChanged()" on a fragment, it is possible that onCreateView has not been called yet, and therefore "getView()" will return null.

---

*[app/src/main/res/layout/galleries_activity_album.xml, line 18 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5KHQ_vZFIoO8920Ei:-Ke5QM1gjysNF0OWwAEQ:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/res/layout/galleries_activity_album.xml#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

CMD-OPT-L
</blockquote></details>

Done.

---

*[app/src/main/res/layout/galleries_artwork_card.xml, line 34 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Kdmjs-HhlqzMUCD1qp8:-Ke5QTjG8qlJvl2FCKTi:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/1d4f6143fd8a0b4b9bef1559a036d50c3b687198/app/src/main/res/layout/galleries_artwork_card.xml#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change to match old TODO: "Todo: make this ripple work on v21+ devices"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265)*

**Comment by romrell4** [comment]
Reviewed 5 of 5 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 119 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5W_6uEGBhq21ZFcS4:-Ke5W_6uEGBhq21ZFcS5:bp9qjfm) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0890dbba602534b0539c417f2bf63a6315e9b09f/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L119)):*
> ```Java
> 					}
> 
> 					pagerAdapter.notifyItemChanged(finalI);
> ```

replace finalI with `artworkList.indexOf(artwork)` and make this a for each loop

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 73 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5KArBZ-Fngvx42iSU:-Ke5X-O-A8agTbRf18XO:biz6ukk) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L73)):*
<details><summary><i>Previously, poolguy (Seth Donaldson) wrote…</i></summary><blockquote>

It appears that it is null sometimes because "onCreateView()" is not called immediately after newInstance(). It appears that onCreateView() is only called when the fragment is going to be shown. Not exactly sure why the pagerAdapter handles it this way, I only know that it does. 

Therefore, when we call "notifyItemChanged()" on a fragment, it is possible that onCreateView has not been called yet, and therefore "getView()" will return null.
</blockquote></details>

Put this into a comment here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265)*

**Comment by poolguy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java, line 119 at r3](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5W_6uEGBhq21ZFcS4:-Ke5Y80pMZoDRukOtg38:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/0890dbba602534b0539c417f2bf63a6315e9b09f/app/src/main/java/edu/byu/suite/features/galleries/controller/AlbumActivity.java#L119)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

replace finalI with `artworkList.indexOf(artwork)` and make this a for each loop
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java, line 73 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-Ke5KArBZ-Fngvx42iSU:-Ke5YpvMWqg0dlmevgJR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e7305c8c67c9b5c83e73a255fd8e9fe0bca949a3/app/src/main/java/edu/byu/suite/features/galleries/controller/ArtworkFragment.java#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Put this into a comment here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/265#-:-Ke5ZXq12sxwXLfoJnnd:bnfp4nl)*

**Pull request merged**
