### PR TITLE
Feature/labcomps. Closes #291

### LINKED ISSUE #291: Lab Computers
Eric,

I am Greg Reeve, a web developer in the HBLL. We are creating a new version of the Open Computers lab application that you reference in the BYU mobile app. We currently have the new and old version of the apps running concurrently. The old/current version is found at:

http://open-computers.lib.byu.edu/available

The new version is at:

https://labusage.lib.byu.edu/available/

Let me know when you are able to make this change in the mobile apps or if you have any other questions.

Thanks,
Greg

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/353)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTUpUGa5iA0Biq2SmH:-KfTUpUGa5iA0Biq2SmI:b-5oorar) (no related file):*
Why is the order or the labs upside down from the old version?

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTWHH7pemCcZc66Lu8:-KfTV7Y9dFAPWDFkXgrh:bm3ujf4) (no related file):*
If you think it would be cool/fun, maybe implementing a progress bar showing the fraction of computers taken up. Talk to me if you're interested

---

*[app/src/main/java/edu/byu/suite/features/labComputers/model/Lab.java, line 53 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTVT7URsnIy5SkphGu:-KfTVT7URsnIy5SkphGv:byxz6tu) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f9d089e09394d1688f60fb96e2d2034ac19a9ab1/app/src/main/java/edu/byu/suite/features/labComputers/model/Lab.java#L53)):*
> ```Java
> 		List<DefaultRow> rows = new ArrayList<>(2);
> 		if (numberWindows != 0) {
> 			rows.add(new DefaultRow("Windows", String.format(AVAILABLE_FORMAT, numberAvailableWindows, numberWindows)));
> ```

Is this the same string that we're checking in the LabActivity? If so, definitely PSF

---

*[app/src/main/java/edu/byu/suite/features/labComputers/service/LabComputersClient.java, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTW2r6PVK6Ct8eBWlD:-KfTW2r6PVK6Ct8eBWlE:b-7ffxux) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f9d089e09394d1688f60fb96e2d2034ac19a9ab1/app/src/main/java/edu/byu/suite/features/labComputers/service/LabComputersClient.java#L28)):*
> ```Java
> 	@Override
> 	public ByuApiGenerator.AuthType getAuthType() {
> 		return ByuApiGenerator.AuthType.NONE;
> ```

Add TODO: Resolve issues with WSO2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTUpUGa5iA0Biq2SmH:-Kfh7B577S2Qr-Z67qk6:b-i6p6v4) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why is the order or the labs upside down from the old version?
</blockquote></details>

I decided it made the most sense to order them by the floor they're on (which happens to be the opposite of their natural ordering in the web service). I can alternatively order them alphabetically, or just use the ordering we get back normally

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTWHH7pemCcZc66Lu8:-Kfh7Ty8-KXLAhTCEt3e:b-thyj7) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

If you think it would be cool/fun, maybe implementing a progress bar showing the fraction of computers taken up. Talk to me if you're interested
</blockquote></details>

else {
// todo: add what corey should do if he's not interested
}

---

*[app/src/main/java/edu/byu/suite/features/labComputers/model/Lab.java, line 53 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTVT7URsnIy5SkphGu:-Kfh9ZFcMBgJumvm_FSS:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f9d089e09394d1688f60fb96e2d2034ac19a9ab1/app/src/main/java/edu/byu/suite/features/labComputers/model/Lab.java#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this the same string that we're checking in the LabActivity? If so, definitely PSF
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/labComputers/service/LabComputersClient.java, line 28 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTW2r6PVK6Ct8eBWlD:-Kfh7yGUhJryQEWA5Dpt:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/f9d089e09394d1688f60fb96e2d2034ac19a9ab1/app/src/main/java/edu/byu/suite/features/labComputers/service/LabComputersClient.java#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add TODO: Resolve issues with WSO2
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTUpUGa5iA0Biq2SmH:-Kfh9vX1HPmk09SJBts9:bsn9opf) (no related file):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

I decided it made the most sense to order them by the floor they're on (which happens to be the opposite of their natural ordering in the web service). I can alternatively order them alphabetically, or just use the ordering we get back normally
</blockquote></details>

I would say matching the ordering of the web page would be best

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353)*

**Comment by coreywoodfield** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-KfTUpUGa5iA0Biq2SmH:-KfhBNIRma-Y--tCh47o:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I would say matching the ordering of the web page would be best
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/353#-:-KfhBXeS1d0YGdWsvlpP:bnfp4nl)*

**Pull request merged**
