### PR TITLE
Feature/dining

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/389)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 391 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-3uUJw14VWN8Ap9N:-Kig-3uVXdx1rrAlR574:byzlf3n) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/AndroidManifest.xml#L391)):*
> ```XML
> 		<activity
> 			android:name=".features.dining.controller.DiningMainActivity"
> 			android:icon="@drawable/icon_dining_account"
> ```

Add correct icon

---

*[app/src/main/AndroidManifest.xml, line 402 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-5xIbLn12Q4XFI0t:-Kig-5xIbLn12Q4XFI0u:byp18fd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/AndroidManifest.xml#L402)):*
> ```XML
> 		</activity>
> 
> 		
> ```

Remove

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-R0zoO0pfP88xXCG:-Kig-R0zoO0pfP88xXCH:b-ktzwu2) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L31)):*
> ```Java
> 		showProgressDialog();
> 
> 		DiningClient.Api api = new DiningClient().getApi(this);
> ```

inline? Was there a reason this was saved?

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-cQe43hp9y0hm6dj:-Kig-cQe43hp9y0hm6dk:b87atx) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L52)):*
> ```Java
> 					dismissProgressDialog();
> 				} else {
> 					dismissProgressDialog();
> ```

Can't you just put this function outside of the if and else?

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 53 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-fz9pKCim6yw9cWW:-Kig-fz9pKCim6yw9cWX:bx62r1m) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L53)):*
> ```Java
> 				} else {
> 					dismissProgressDialog();
> 					showErrorDialog("You don't have a meal plan");
> ```

"You are not listed as having a meal plan. Contact BYU Dining Services if you think this is in error."

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 37 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig2AGMviYqRhkukWCr:-Kig2AGMviYqRhkukWCs:b-7nif5w) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8f67423f4de3ad8aee05104405ca5d4e2f6405c3/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L37)):*
> ```Java
> 				MealPlan mealPlan = response.body();
> 				if (mealPlan.hasMealPlan) {
> 					((TextView) findViewById(R.id.yourBalance)).setText(getString(R.string.$$$$, mealPlan.balance));
> ```

NumberFormatter

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 37 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig2Jn6l6a1bIz7zQ_u:-Kig2Jn6l6a1bIz7zQ_v:b-i1miej) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8f67423f4de3ad8aee05104405ca5d4e2f6405c3/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L37)):*
> ```Java
> 				MealPlan mealPlan = response.body();
> 				if (mealPlan.hasMealPlan) {
> 					((TextView) findViewById(R.id.yourBalance)).setText(getString(R.string.$$$$, mealPlan.balance));
> ```

Need a lot of comments in here

---

*[app/src/main/java/edu/byu/suite/features/dining/model/MealPlan.java, line 10 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-xS6_N7iz0vmgTG3:-Kig-xS6_N7iz0vmgTG4:bcta3xo) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/java/edu/byu/suite/features/dining/model/MealPlan.java#L10)):*
> ```Java
> 
> public class MealPlan {
> 	public Date beginDate;
> ```

Punk. :p Make getters! Also, only save the ones you need. We'll remove the other ones from the service

---

*[app/src/main/res/values/strings.xml, line 257 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig1bnsRqL9iwxF7n3j:-Kig1bnsRqL9iwxF7n3k:buw4dze) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8f67423f4de3ad8aee05104405ca5d4e2f6405c3/app/src/main/res/values/strings.xml#L257)):*
> ```XML
> 	<string name="difference">Difference:</string>
> 	<string name="recommended_daily_spending">Recommended Daily Spending:</string>
> 	<string name="$$$$">$%.2f</string>
> ```

If we can't get NumberFormatter to work, I'll give you $_format

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[app/src/main/AndroidManifest.xml, line 391 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-3uUJw14VWN8Ap9N:-Kig3H-S12jR5LnBERIu:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/AndroidManifest.xml#L391)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add correct icon
</blockquote></details>

Done.

---

*[app/src/main/AndroidManifest.xml, line 402 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-5xIbLn12Q4XFI0t:-Kig3Jqie_lupMBK9I6l:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/AndroidManifest.xml#L402)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-R0zoO0pfP88xXCG:-Kig3NVUnzpshGc8qFj2:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

inline? Was there a reason this was saved?
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 52 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-cQe43hp9y0hm6dj:-Kig3QkiIs_WfLV1RAXI:b-ivk6b) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can't you just put this function outside of the if and else?
</blockquote></details>

I could, but I want to dismiss it either *after* I've set all the text or *before* I show the error dialog

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 53 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-fz9pKCim6yw9cWW:-Kig3fij9uKDSzgnNSR3:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L53)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

"You are not listed as having a meal plan. Contact BYU Dining Services if you think this is in error."
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 37 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig2AGMviYqRhkukWCr:-Kig3NsdWq4HdQUGKXxT:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8f67423f4de3ad8aee05104405ca5d4e2f6405c3/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L37)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

NumberFormatter
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 37 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig2Jn6l6a1bIz7zQ_u:-Kig3OMtuNsnrxypYSCw:b2ni78k) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8f67423f4de3ad8aee05104405ca5d4e2f6405c3/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L37)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Need a lot of comments in here
</blockquote></details>

lol

---

*[app/src/main/java/edu/byu/suite/features/dining/model/MealPlan.java, line 10 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig-xS6_N7iz0vmgTG3:-Kig3h4Nw-GWR-A3AqXt:b-b6ptpg) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/cca82e4cc113f010d9b82bebd3c320f2dea521e7/app/src/main/java/edu/byu/suite/features/dining/model/MealPlan.java#L10)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Punk. :p Make getters! Also, only save the ones you need. We'll remove the other ones from the service
</blockquote></details>

Oh yeah I was gonna do that

---

*[app/src/main/res/values/strings.xml, line 257 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig1bnsRqL9iwxF7n3j:-Kig3kFeUo-LdX_O6kH8:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8f67423f4de3ad8aee05104405ca5d4e2f6405c3/app/src/main/res/values/strings.xml#L257)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

If we can't get NumberFormatter to work, I'll give you $_format
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389)*

**Comment by romrell4** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 37 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig2Jn6l6a1bIz7zQ_u:-Kig4XWKKmVi5uUSuxP6:b-41vf0q) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8f67423f4de3ad8aee05104405ca5d4e2f6405c3/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L37)):*
<details><summary><i>Previously, coreywoodfield (Corey Woodfield) wrote…</i></summary><blockquote>

lol
</blockquote></details>

Try again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389)*

**Comment by romrell4** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389)*

**Comment by coreywoodfield** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java, line 37 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-Kig2Jn6l6a1bIz7zQ_u:-Kig5iJdok5kOLcStHDc:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/8f67423f4de3ad8aee05104405ca5d4e2f6405c3/app/src/main/java/edu/byu/suite/features/dining/controller/DiningMainActivity.java#L37)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Try again
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389)*

**Comment by romrell4** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/389#-:-Kig9l7P9oRMm89zNzco:bnfp4nl)*

**Pull request merged**
