### PR TITLE
Fix/bugs

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/179)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-KcYlrAUFs-1SxdOjKHy:-KcYlrAUFs-1SxdOjKHz:b-vm95vz) (no related file):*
A lot of this code is confusing to me. It would probably make more sense if you explained it to me, but I would also add some more comments. Try to make it so that someone can understand the intuition of what you did. Also, respond to this  with an english representation of what the problem was as well as what the solution ended up as

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java, line 205 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-KcYjuryKt9usdGuM4AY:-KcYjuryKt9usdGuM4AZ:b-vmzfnd) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9920701066a00f7bc7364cd7b3317911ad2f21f0/app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java#L205)):*
> ```Java
> 		viewPager.setCurrentItem(1);
> 
> 		fragmentPagerAdapter.executeCodeOnFragment(getFragmentManager(), 1, fragment -> ((ClassMapFragment) fragment).showBuildingMarker(data));
> ```

What is this doing? Could we get a comment here?

---

*[support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-KcYlhcz39930uw6nWYC:-KcYlhcz39930uw6nWYD:b2s2ria) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9920701066a00f7bc7364cd7b3317911ad2f21f0/support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java#L31)):*
> ```Java
>  */
> public class ByuCameraFeedFragment extends ByuFragment {
> 	private final String TAG = "" + this;
> ```

What is this?

---

*[support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java, line 151 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-KcYmRyd6n0ZyoXZGVvS:-KcYmRyd6n0ZyoXZGVvT:b-vqve8) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9920701066a00f7bc7364cd7b3317911ad2f21f0/support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java#L151)):*
> ```Java
> 	}
> 
> 	private class LoggingRunnable implements Runnable {
> ```

Why is this called a LoggingRunnable? It seems that it just wraps the exception catching...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179)*

**Comment by coreywoodfield** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-KcYlrAUFs-1SxdOjKHy:-KcYnscHDO_KFisW0Nyc:bk3qrc1) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

A lot of this code is confusing to me. It would probably make more sense if you explained it to me, but I would also add some more comments. Try to make it so that someone can understand the intuition of what you did. Also, respond to this  with an english representation of what the problem was as well as what the solution ended up as
</blockquote></details>

The problem was that the fragment manager, when restoring state, didn't use the same fragments as had existed before the activity was destroyed. It created new instances and passed in the saved state. We were saving references to the fragments in the activity but those references were (after restoring activity state) pointing to different fragments than the ones that were actually displayed. This code ensures that any code run on fragments through the adapter is run on the actual fragment that is being displayed, and not on some random fragment we instantiated that's not being used anywhere. If the fragment hasn't finished being restored yet, it stores the code in a lambda, and runs it as soon as the fragment is instantiated.

---

*[app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java, line 205 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-KcYjuryKt9usdGuM4AY:-KcYnd8jjj9dSrRS6Hdq:be0g4p7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9920701066a00f7bc7364cd7b3317911ad2f21f0/app/src/main/java/edu/byu/suite/features/mapMyClasses/MapMyClassesMainActivity.java#L205)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this doing? Could we get a comment here?
</blockquote></details>

it's doing the same thing that the other code was doing, just more safely. It tells the adapter to get the fragment and run the lambda on it if it's available, or run the lambda on it once it gets instantiated

---

*[support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java, line 31 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-KcYlhcz39930uw6nWYC:-KcYnHX-CuHYHc3CdIg-:b-lp1xkr) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9920701066a00f7bc7364cd7b3317911ad2f21f0/support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

It's a logging tag, that includes the reference to the object so you can tell if it's the same one as another one ;)

---

*[support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java, line 151 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-KcYmRyd6n0ZyoXZGVvS:-KcYnO3Y6LfY0Cf2hTmn:bxltsog) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/9920701066a00f7bc7364cd7b3317911ad2f21f0/support/src/main/java/edu/byu/support/fragment/ByuCameraFeedFragment.java#L151)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why is this called a LoggingRunnable? It seems that it just wraps the exception catching...
</blockquote></details>

Because it logs the exception. Most useful for debugging, but if we have some sort of crash reporting, it would be useful in prod too. another thing it could do is just ignore the exception, and then the scheduled task would continue to run on schedule, instead of silently stopping

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179)*

**Comment by romrell4** [comment]
Reviewed 1 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/179#-:-KcYqiwvd0Yfm6fh8FwR:bnfp4nl)*

**Pull request merged**
