### PR TITLE
Feature/default

### PR DESCRIPTION
**Pull request by coreywoodfield**
This change is [Reviewable](https://reviewable.io/reviews/byu-oit-appdev/android-byu-suite-v2/144)

### CODE REVIEW

**Comment by romrell4** [comment]
Reviewed 90 of 90 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java, line 22 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKpBc0AC4Csh3xjxkS:-KcKpBc0AC4Csh3xjxkT:bit6r06) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java#L22)):*
> ```Java
> public class AssignmentsFragment extends LearningSuiteListFragment {
> 	private DefaultHeaderAdapter<Assignment> adapter = new DefaultHeaderAdapter<>(null, R.layout.default_list_item_detail_below_indicator,
> 																				  (data, view, position) -> replaceFragment(LearningSuiteDetailFragment.newInstance(data)), Assignment::getText, Assignment::getDetailText);
> ```

Look at this guy and Announcement

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CalendarFragment.java, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKpFb_lIMZGeSIfcXt:-KcKpFb_lIMZGeSIfcXu:bb6zqys) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CalendarFragment.java#L19)):*
> ```Java
> public class CalendarFragment extends LearningSuiteListFragment {
> 	private DefaultHeaderAdapter<CalendarItem> adapter = new DefaultHeaderAdapter<>(null, R.layout.default_list_item_indicator, (data, view, position) -> replaceFragment(CalendarItemFragment.newInstance(data)),
> 																					CalendarItem::getText,
> ```

Look

---

*[app/src/main/java/edu/byu/suite/features/offCampusHousing/controller/OchMainActivity.java, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKpfhEmMGwMhfLK_KZ:-KcKpfhEmMGwMhfLK_K_:brhg7gb) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/app/src/main/java/edu/byu/suite/features/offCampusHousing/controller/OchMainActivity.java#L20)):*
> ```Java
> 		setContentView(R.layout.activity_recycler_view);
> 		((ByuRecyclerView) findViewById(R.id.recyclerView)).setAdapter(
> 				new DefaultRecyclerAdapter<>(Arrays.asList(new DefaultRow(OchMapActivity.MEN_TEXT), new DefaultRow(OchMapActivity.WOMEN_TEXT), new DefaultRow(OchMapActivity.FAMILY_TEXT), new DefaultRow(OchMapActivity.GRADUATE_TEXT)),
> ```

Add new lines

---

*[support/src/main/java/edu/byu/support/client/campusLocation/model/BuildingsWrapper.java, line 59 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKq90A0kenrXy27H0S:-KcKq90A0kenrXy27H0T:bigvds0) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/support/src/main/java/edu/byu/support/client/campusLocation/model/BuildingsWrapper.java#L59)):*
> ```Java
> 		}
> 
> 		public CharSequence getAcronym() {
> ```

I'm cool with that

---

*[support/src/main/java/edu/byu/support/defaults/GetterViewHolder.java, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKm4vRyRpoGViYQwxW:-KcKm4vRyRpoGViYQwxX:b-l63tdo) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/support/src/main/java/edu/byu/support/defaults/GetterViewHolder.java#L15)):*
> ```Java
>  */
> 
> public class GetterViewHolder<DataType> extends ByuViewHolder<DataType> {
> ```

Let's make this DefaultViewHolder

---

*[support/src/main/java/edu/byu/support/defaults/TextGetter.java, line 7 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKmCTRqYrJC2pn0TYf:-KcKmCTRqYrJC2pn0TYg:b-xproj7) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/support/src/main/java/edu/byu/support/defaults/TextGetter.java#L7)):*
> ```Java
>  */
> 
> public interface TextGetter<T> {
> ```

Combine them :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144)*

**Comment by romrell4** [comment]
Reviewed 2 of 90 files at r1, 18 of 20 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 49 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKwuYXFSkioEWz3N6y:-KcKwuYXFSkioEWz3N6z:b-hdg7di) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/756d910038df9258a006a21cbd01adf5b10ccdde/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L49)):*
> ```Java
> 		addRowIfNotEmpty(rows, "Section Fee: ", section.getCourseFee());
> 
> 		((ByuRecyclerView) findViewById(R.id.recyclerView)).setAdapter(new DefaultRecyclerAdapter<>(rows, R.layout.default_list_item, null, data -> data, null));
> ```

Comment this one

---

*[support/src/main/java/edu/byu/support/defaults/DefaultViewHolder.java, line 15 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKxntdwmRcTs35I5wp:-KcKxntdwmRcTs35I5wq:b-7ql9bj) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/756d910038df9258a006a21cbd01adf5b10ccdde/support/src/main/java/edu/byu/support/defaults/DefaultViewHolder.java#L15)):*
> ```Java
>  */
> 
> public class DefaultViewHolder<DataType> extends ByuViewHolder<DataType> {
> ```

final

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144)*

**Comment by coreywoodfield** [comment]
Review status: 36 of 85 files reviewed at latest revision, 8 unresolved discussions.

---

*[app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java, line 49 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKwuYXFSkioEWz3N6y:-KcKy4YlB1PsB24IrP0c:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/756d910038df9258a006a21cbd01adf5b10ccdde/app/src/main/java/edu/byu/suite/features/classSchedule/SectionDetailsActivity.java#L49)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Comment this one
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java, line 22 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKpBc0AC4Csh3xjxkS:-KcKy61ISRzwbP6Tc7uC:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/AssignmentsFragment.java#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Look at this guy and Announcement
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CalendarFragment.java, line 19 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKpFb_lIMZGeSIfcXt:-KcKy6fQGYJYREoxhDMp:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/app/src/main/java/edu/byu/suite/features/learningSuite/fragment/CalendarFragment.java#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Look
</blockquote></details>

Done.

---

*[app/src/main/java/edu/byu/suite/features/offCampusHousing/controller/OchMainActivity.java, line 20 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKpfhEmMGwMhfLK_KZ:-KcKy7AkyHDKLWdCfdv8:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/app/src/main/java/edu/byu/suite/features/offCampusHousing/controller/OchMainActivity.java#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add new lines
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/client/campusLocation/model/BuildingsWrapper.java, line 59 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKq90A0kenrXy27H0S:-KcKyS-SCdddYgm2OcPg:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/support/src/main/java/edu/byu/support/client/campusLocation/model/BuildingsWrapper.java#L59)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'm cool with that
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/defaults/DefaultViewHolder.java, line 15 at r2](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKxntdwmRcTs35I5wp:-KcKya94uoeuuG87kmeR:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/756d910038df9258a006a21cbd01adf5b10ccdde/support/src/main/java/edu/byu/support/defaults/DefaultViewHolder.java#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

final
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/defaults/TextGetter.java, line 7 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKmCTRqYrJC2pn0TYf:-KcKyauF03ovDTs9_sDB:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/support/src/main/java/edu/byu/support/defaults/TextGetter.java#L7)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Combine them :)
</blockquote></details>

Done.

---

*[support/src/main/java/edu/byu/support/defaults/GetterViewHolder.java, line 15 at r1](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-KcKm4vRyRpoGViYQwxW:-KcKybKjRbbGxecERNc1:b-896fix) ([raw file](https://github.com/byu-oit-appdev/android-byu-suite-v2/blob/e95ddf461a03a027a0b792f4e286339a345be1c5/support/src/main/java/edu/byu/support/defaults/GetterViewHolder.java#L15)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's make this DefaultViewHolder
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144)*

**Comment by coreywoodfield** [comment]
None of the default adapters can extend DefaultRecyclerAdapter because they all inherit vital functionality from an abstract class that extends ByuRecyclerAdapter. It'd be great if we could inherit the default functionality from the DefaultRecyclerAdapter but that would be more complicated than it's worth

---

Review status: 36 of 87 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-:-KcL7mSK7Nn0QsJxUoH4:bqsgbuf)*

**Comment by romrell4** [comment]
Reviewed 1 of 20 files at r2, 51 of 51 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144)*

**Comment by romrell4** [comment]
Reviewed 1 of 90 files at r1, 10 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144)*

**Comment by romrell4** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/byu-oit-appdev/android-byu-suite-v2/144#-:-KcOH2rqVQDOOQ0xmFi5:bnfp4nl)*

**Pull request merged**
